### ISSUE TITLE
Copy-DbaDatabase sometimes chooses incorrect path for restore step

### ISSUE THREAD

**Issue by Bendy22** [sqlcollaborative/dbatools#3225] opened 2018-02-13 00:39 UTC
## Bug Report
I am using `Copy-DbaDatabase` to migrate several databases from clustered instances of SQL 2008 R2 to SQL 2016. Most of the databases work fine, but there are a few on each instance that fail. The backup step works fine and backs up to the `-NetworkShare` path I provide. But for a few databases, they do not use the `-NetworkShare` path for the restore step and seem to use some old path that the original database was restored from on the source instance.

### General Troubleshooting steps
`Copy-DbaDatabase -Source DCPTSQLC01INT03.decepticons.amsod\EIQ -Destination AP11DBC01N09 -Database CustomerDefault -BackupRestore -NetworkShare \\backupa.gc.local\source11\DCPT -Force`

I'm using `-Force` so I don't have to delete the destination database that I have restored manually in the past in case the command actually completes.

The basic error is:
`WARNING: [Invoke-DbaAdvancedRestore][15:18:04] Failed to restore db CustomerDefault, stopping | Exception calling "SqlRestore" with "1" argument(s): "Restore failed for Server 'AP11DBC01N09'. "`

Running `$error[0] | select *` gives me

```
Type                     Name            Status Notes                     
----                     ----            ------ -----                     
Database (BackupRestore) CustomerDefault Failed Failed to restore database
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Exception calling "SqlRestore" with "1" argument(s): "Restore failed for Server 'AP11DBC01N09'. " ---> System.Management.Automation.MethodInvocationException: Exception 
                        calling "SqlRestore" with "1" argument(s): "Restore failed for Server 'AP11DBC01N09'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Restore failed for Server 
                        'AP11DBC01N09'.  ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> 
                        System.Data.SqlClient.SqlException: Cannot open backup device 'J:\Microsoft SQL Server\MSSQL10_50.EIQ\MSSQL\Backup\CustomerDefault_EIQRestore'. Operating system error 3(The system cannot 
                        find the path specified.).
                        RESTORE DATABASE is terminating abnormally.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType, Boolean retry)
                           at Microsoft.SqlServer.Management.Smo.BackupRestoreBase.ExecuteSql(Server server, StringCollection queries)
                           at Microsoft.SqlServer.Management.Smo.Restore.SqlRestore(Server srv)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Smo.Restore.SqlRestore(Server srv)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at Invoke-DbaAdvancedRestore<End>(Closure , FunctionContext )
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaAdvancedRestore,Stop-Function
ErrorDetails          : Exception calling "SqlRestore" with "1" argument(s): "Restore failed for Server 'AP11DBC01N09'. "
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, <No file>: line 193
                        at Invoke-DbaAdvancedRestore<End>, <No file>: line 293
                        at Restore-DbaDatabase<End>, <No file>: line 662
                        at Copy-DbaDatabase<Process>, <No file>: line 1071
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```
- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2
 - PowerShell Version: 5.1.14409.1012
 - SQL Server (Edition|Version): Source: 2008 R2  Destination: 2016

## Steps to Reproduce
Run the above `Copy-DbaDatabase` command on the misbehaving databases and it will fail every time.

[dbatoolslog.zip](https://github.com/sqlcollaborative/dbatools/files/1718166/dbatoolslog.zip)

 - [X] Attach any screenshots (if possible/allowed)
 - [X] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [X] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
Copy-DbaDatabase should always use the path given in the `-NetworkShare` parameter for the restore step.

### Additional information
I believe the path in the large error above is a full file path and not a folder path. When I run this command on the other misbehaving databases, I get paths terminating in .bak files. So I believe CustomerDefault_EIQRestore was a filename with no extension and not a folder.

**Comment by Stuart-Moore** [comment] 2018-02-13 10:00
Hi @Bendy22 could you run `Get-DbaBackupHistory -LastFull` against the database please and let us know the results.

And then `Get-DbaBackupHistory -LastFull -IncludeCopyOnly`

My guess is that it's getting the path of the real full backup rather than the one that Copy-DbaDatabase is performing.

Tests may not work if there's been another full since the last fail. Don't know if you'd be able to rerun the copy if so?

**Comment by Stuart-Moore** [comment] 2018-02-20 08:43
Hi,
not forgotten, just having trouble reproing which means I'm guessing. Think I know where it's happening, jsut trying come up with a solid solution

**Comment by Bendy22** [comment] 2018-03-30 16:30
Running into this issue again. I will attempt separate backup and restore steps for the databases that suffer from this problem for now. Thanks in advance for your help on getting this fixed.

**Comment by duncfair** [comment] 2018-05-22 17:47
same problem. Never had any problems with this until I updated DBATools...

**Comment by janeztr** [comment] 2018-09-28 08:06
Hi, same here.
But it only fails on one database (same) out of seven.

`Copy-DbaDatabase -Source $SourceInstance -Destination $DestinationInstance -BackupRestore -NetworkShare $BackupSharedFolderUNC -Database $DB -ReuseSourceFolderStructure  -WithReplace -Force -Verbose:$Verbose`

`WARNING: [09:25:34][Copy-DbaDatabase] Failure attempting to restore DW_Metadata to GENINGDWHTEST01 | System.Data.SqlClient.SqlError: Cannot open backup device 'C:\Program Files\Microsoft SQL Server\MSSQL11
.MSSQLSERVER\MSSQL\Backup\{D828C1D5-7E1C-454A-A904-03F81736F1C7}1'. Operating system error 2(The system cannot find the file specified.).
`
Path C:\Program Files\Microsoft SQL Server\MSSQL11  doesn't exist nor on source nor on destination  server.

I can succesfully restore backup files which are left after Copy-DbaDatabase error with 
`Set-Location $BackupSharedFolderUNC`
`Get-ChildItem  | Restore-DbaDatabase -SqlInstance $DestinationInstance  -WithReplace -ReuseSourceFolderStructure `

**Comment by janeztr** [comment] 2018-11-16 12:46
Hi, just updated to version 0.9.517 and still get the same error.

**Comment by niphlod** [comment] 2018-11-16 13:02
that's different ... seems you have backups done by an external party ... unless you have files named Backup{
D828C1D5-7E1C-454A-A904-03F81736F1C7}1

**Comment by janeztr** [comment] 2018-11-16 13:17
Yeah, we use  MS DPM ...

**Comment by niphlod** [comment] 2018-11-16 13:22
Yeah "we do have files named like that" or "yeah, we use DPM which doesn't leave files around" ?
Because if the latter is true, you can't use Copy-DbaDatabase if you keep having DPM actively backing up your instances.

**Comment by Bendy22** [comment] 2018-11-16 14:44
I am sorry, but I am no longer have access to the client with this environment where I can re-test.

**Comment by potatoqualitee** [comment] 2018-11-16 14:46
d'oh! down to @duncfair 

thank you both for responding and thanks niph for handling it

**Comment by Stuart-Moore** [comment] 2018-11-16 14:51
Looks like my PR tag didn't make it into this one. This was one of the issues that the the Get-DbaBackuphistory/Backup-DbaDatabase  fixes should fix as it was most likely either:
1) Picking up a higher LSN backup from another ForkID
2) Picking up a concurrent 'proper' backup

**Comment by potatoqualitee** [comment] 2018-11-16 14:53
fantastic news, thank you, @Stuart-Moore! Marking as closed.

**Closed by potatoqualitee** 2018-11-16 14:53 UTC
Labels: bugs_life

**Comment by janeztr** [comment] 2018-11-16 15:02
Ok, thx for the explanation. I'm not familiar with DPM, don't know how it names backup files nor where it leaves them.  Still, Copy-DbaDatabase works fine for 6 out of 7 DBs,  all of them backed up using DPM.

**Comment by Bendy22** [comment] 2018-11-16 15:14
Thanks for fixing this!

**Comment by niphlod** [comment] 2018-11-16 16:32
hum, not really.
irregardless of the backup software, the backup history is there. That's why there are ALREADY switches to identify virtual or disk backups.
The "grin" here is that get-dbabackuphistory does play well in most cases, EXCEPT backup forks (because they dirsupt the natural order of lsns, and get-dbabackuphistory follows strictly lsn order).
Main issue of get-dbabackuphistory -Last stands (given forks are allowed in MSSQL, lsn order can't always be trusted). Now, recent commits tame the "error" tring to restrict the set with -LastLsn and/or fetch infos from other sources, but the problem stll stays, albeit in a more "restricted corner".
The problem with Copy-DbaDatabase here is multifold, but basically the root cause is backup-dbadatabase using get-dbadbhistory to get the properties of the backup "just done". If you fall in the "restricted corner", the backup still happens, but the output object comes from a different "line in msdb".

We can tame more doing -DeviceType Disk (at least for the moment since backup-dbadatabase doesn't support anything else) and/or -Since (notloolongago), but the problem with get-dbabackuphistory and forks will still be there, just in more and more restricted corners, without solving the root cause (which would be a PITA, but it's technically solvable)

**Comment by duncfair** [comment] 2018-11-16 17:51
Hi Chrissy,

I am at another company site working on a project that includes the migration of multiple db’s (It was only supposed to be 2).

Go live is tonight but we have been using the copy-dbafatabase command extensively (and successfully) as recently as 3 days ago. Any updates since then?

Thanks,

Duncan

Best Regards,

Duncan Fairweather
805-907-8869
________________________________

**Comment by potatoqualitee** [comment] 2018-11-16 18:55
awesome, that's great news @duncfair - thank you! No changes since then, looks like stuart's earlier changes worked 🎉

**Comment by janeztr** [comment] 2018-12-10 11:44
Hi, 0.9.533 update resolved my issue, thx!

**Comment by potatoqualitee** [comment] 2018-12-10 11:45
fantastic! thanks for the update @janeztr 💯
