### ISSUE TITLE
[Bug] New-DbaAgentOperator default values not correct

### ISSUE THREAD

**Issue by cmuncan** [sqlcollaborative/dbatools#7193] opened 2021-03-15 20:19 UTC
Attempting to use the `New-DbaAgentOperator` to create a "dummy" email operator.  We use this for completion of jobs so that any job that is run can email the person who requested it.  for instance, I would traditionally create a "dummy" operator like this:

```
USE [msdb]
GO
EXEC msdb.dbo.sp_add_operator @name=N'myemail@domain.com', 
		@enabled=1, 
		@pager_days=0, 
		@email_address=N'myemail@domain.com'
GO
```

When I attempt to do the same with the `New-DbaAgentOperator` I initially coded it as such:

`New-DbaAgentOperator    -SqlInstance $connectedInstance -Operator $OperatorEmail -EmailAddress $OperatorEmail -WhatIf:$WhatIf -Verbose:$Verbose -Force 
`

Assuming that the -Force flag would use the defaults but it seems that if I do this, I get the following error:

```WARNING: [16:07:15][New-DbaAgentOperator] Issue creating operator. | String was not recognized as a valid TimeSpan.```

My workaround for this is to use the `-PagerDay EveryDay` flag but I didn't think I had to.

#### Host used

- [ ] powershell.exe
- [X] ISE
- [X] VS Code
- [ ] Other (please specify)

#### Errors Received

```WARNING: [16:07:15][New-DbaAgentOperator] Issue creating operator. | String was not recognized as a valid TimeSpan.```

```
writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: String was not recognized as a valid TimeSpan. ---> System.Management.Automation.SetValueInvocationException: Exception setting "SaturdayPagerStartTime":     
                        "Cannot convert value "" to type "System.TimeSpan". Error: "String was not recognized as a valid TimeSpan."" ---> System.Management.Automation.PSInvalidCastException: Cannot   
                        convert value "" to type "System.TimeSpan". Error: "String was not recognized as a valid TimeSpan." ---> System.FormatException: String was not recognized as a valid TimeSpan. 
                           at System.Globalization.TimeSpanParse.TimeSpanResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String
                        failureArgumentName)
                           at System.Globalization.TimeSpanParse.TryParseTimeSpan(String input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
                           at System.Globalization.TimeSpanParse.Parse(String input, IFormatProvider formatProvider)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.LanguagePrimitives.ConvertViaParseMethod.ConvertWithCulture(Object valueToConvert, Type resultType, Boolean recursion, PSObject
                        originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
TargetObject          : CPCWVCDTSQLD29,25600
CategoryInfo          : InvalidOperation: (CPCWVCDTSQLD29,25600:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_New-DbaAgentOperator,Stop-Function
ErrorDetails          : String was not recognized as a valid TimeSpan.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.141\allcommands.ps1: line 87807
                        at New-DbaAgentOperator<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.141\allcommands.ps1: line 51344
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.141
Culture of OS             : en-US
```

**Comment by lancasteradam** [comment] 2021-03-16 14:56
@cmuncan, this appears to be a duplicate of #7187. The pull request submitted for #7187 has not yet been merged and released.

**Comment by jpomfret** [comment] 2021-04-18 16:49
Closing this sine #7187 is now fixed and this is a duplicate. Please reopen if you are still having issues.

**Closed by jpomfret** 2021-04-18 16:49 UTC
Labels: bugs_life
