### ISSUE TITLE
[Bug] Copy-DbaDBMail setting wrong SMTP Server during copy

### ISSUE THREAD

**Issue by octaviancretu** [sqlcollaborative/dbatools#7147] opened 2021-02-19 13:26 UTC
### Report
While running Copy-DbaDbMail -Source $instanceSource -Destination $instanceDestination , The target e-mail accounts will contain as a target server the server name of the SQL Server destination instance instead of the SMTP Server name. This has been tested with dbatools version 1.0.106

Additionally SMTP authentication properties are not being copied.

#### Host used

- [x ] powershell.exe
- [ x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received
No Errors

#### Steps to Reproduce
-Create DBMail Account and profile. DBMail account should contain a smtp server name and SMTP authentication basic authenticaion.
-Run powershell command:
Copy-DbaDbMail -Source $instanceSource -Destination $instanceDestination

#### Expected Behavior
I would expect for the right SMTP Server to be copied.
Also the SMTP Authentication should be copied

#### Actual Behavior
The SMTP Server name contains the actual SQL Server Name (Host\Instance)

### Environmental information
PowerShell Version        : 5.1.14393.3471
dbatools latest installed :
Culture of OS             : en-US

DBATools version: 1.0.106 - I Saw that there were no changes for this component since this version.

#### SQL Server:
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
us_english

**Comment by lancasteradam** [comment] 2021-02-26 19:01
@octaviancretu, I'm able to see the issue however it is transient in nature because the command does complete the transfer of the mail server info. Here is the code workflow:

In the Process block the account info is transferred before the mail server. 
https://github.com/sqlcollaborative/dbatools/blob/9e76c051b70295f9de49502211313bc9e173054c/functions/Copy-DbaDbMail.ps1#L387-L393

An interesting point here is that the SMO $account.Script() does not include the mail server info, which explains why after this step there is the host\instance value in the smtp server field.
https://github.com/sqlcollaborative/dbatools/blob/9e76c051b70295f9de49502211313bc9e173054c/functions/Copy-DbaDbMail.ps1#L175-L189

When the mailserver is copied all of the fields for the server including auth are successfully stored. The host\instance value that was previously there is successfully replaced with the correct value.
https://github.com/sqlcollaborative/dbatools/blob/9e76c051b70295f9de49502211313bc9e173054c/functions/Copy-DbaDbMail.ps1#L306-L320

For next steps I suggest the following:

1. Confirm if there is anything else in your environment that could be adding to the scenario. If anything new is discovered please add that info to the Steps to Reproduce section above.
2. Run the scenario once more and include the -Verbose param. This may help to reveal if all sections of the code are actually running.

**Comment by andreasjordan** [comment] 2021-05-18 16:57
I will close this for now, but you can reopen it if you have further questions.

**Closed by andreasjordan** 2021-05-18 16:57 UTC
Labels: bugs_life
