### ISSUE TITLE
Sync-DbaSqlLoginPermission does not work to Sync Logins and Users on AG databases

### ISSUE THREAD

**Issue by DeveshEncore** [sqlcollaborative/dbatools#3646] opened 2018-05-30 15:55 UTC
Hi,

We are trying to sync the permissions between two servers built on AG with one Primary and other one as READ Secondary Replica. But the Powershell command is not able to Sync the permissions and even returns the error mentioned. This is not working on any of the Synchronized database on AG. I can create login and assign DB permissions manually on secondary databases.

## Steps to Reproduce

```powershell

**Sync-DbaSqlLoginPermission -source AG Primary -Destination AG Secondary**

```
## Actual Behavior

**[Update-SqlPermissions][08:40:20] Failed to perform Grant on CONNECT to "domain account" on "Synchronized Database on AG Secondary" on "Secondary Read Replica". | Exception calling "Grant" with "3" argument(s): "Grant failed for Database 'Synchronized Database on AG Secondary'. "**

## Environmental data

 - PowerShell: 
PSVersion                      4.0                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                           
BuildVersion                   6.3.9600.18968                                                                                                                            
PSCompatibleVersions           
{1.0, 2.0, 3.0, 4.0}                                                                                                                      
PSRemotingProtocolVersion
2.2

 - - SQL Server: 2017 Standard.

**Comment by wsmelton** [comment] 2018-05-31 23:06
That is by design. You cannot modify database level permissions for a database that resides on the secondary replica of an AG. Those are changed on the primary replica only.

**Comment by niphlod** [comment] 2018-10-24 19:10
closing this, @DeveshEncore feel free to reopen in case you're missing something

**Closed by niphlod** 2018-10-24 19:10 UTC
