### ISSUE TITLE
Restore-DBADatabase failing on wrong case

### ISSUE THREAD

**Issue by josh-simar** [sqlcollaborative/dbatools#2500] opened 2017-10-24 04:37 UTC
## Bug Report
- [ X ] Verified running latest release of dbatools?
- [ X ] Verified errors are not related to permissions?
- [ X ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System Windows 2012
 - PowerShell Version: 4.0
 - SQL Server SQL 2014 (N/A)

## Steps to Reproduce

1. Have backups from Ola's scripts.
2. Take a manual Ola backup e.g. EXEC usp_BackupDB_Full_1_File @DBName = "Different case than your DB" ex. AdventureWorks becomes adventureworks
3. Have log backups as well.
4. Try restoring database

This will error out Restore-DBADatabase on line 580 as it is trying to pass a list at that point to Restore-DBFromFilteredArray -OldDatabaseName where it expects a String. I fixed this by modifying line 574 on my local copy from $OldDatabaseName = ($FilteredFiles | Select-Object -Property DatabaseName -unique).DatabaseName to $OldDatabaseName = ($FilteredFiles | Select-Object -Property DatabaseName -unique- First 1).DatabaseName. I'll submit the code change soon as I don't believe it to break anything else.

**Comment by wsmelton** [comment] 2017-11-08 13:50
@josh-simar a PR that reworked the restore command a good bit was just merged this morning. Can you retest your case and see if you still have the same issue.

**Comment by niphlod** [comment] 2017-11-30 21:10
@josh-simar : please do retest, I tried and couldn't reproduce.

**Comment by niphlod** [comment] 2018-03-01 23:00
@josh-simar : last call, going to close in a few days if we don't hear you back 

BTW: I still can't reproduce.

**Closed** 2018-10-15 20:59 UTC
