### ISSUE TITLE
Get-DbaSqlService not working with -Credential parameter in different AD

### ISSUE THREAD

**Issue by EmDBA** [sqlcollaborative/dbatools#2979] opened 2018-01-04 16:02 UTC
When I try to get sql service information from a server in another active directory, Get-DbaSqlService doesn't work correctly with -Credential parameter. I have the same issue with Restart-DbaSqlService.

Input from Fred in slack : 
This function kills the fqdn, which means it will afterwards only search without (which should be in the verbose output for the redacted names)
Since it first resolves the name, that's a killer here

## Steps to Reproduce
```
Get-DbaSqlService -ComputerName XXX -Credential XXX -Verbose
VERBOSE: [Resolve-DbaNetworkName][15:03:26] Connecting to XXX
VERBOSE: [Resolve-DbaNetworkName][15:03:26] IP Address from XXX is XXX
VERBOSE: [Resolve-DbaNetworkName][15:03:26] Getting computer information from XXX
VERBOSE: [Get-DbaCmObject][15:03:26] Configuration loaded | Cache disabled: False
VERBOSE: [Get-DbaCmObject][15:03:26] [XXX] Retrieving Management Information
VERBOSE: [Get-DbaCmObject][15:03:26] [XXX] Accessing computer using Cim over WinRM
VERBOSE: [Get-DbaCmObject][15:03:41] [XXX] Accessing computer using Cim over WinRM - Success!
VERBOSE: [Resolve-DbaNetworkName][15:03:41] Resolving XXX using .NET.Dns GetHostEntry
VERBOSE: [Get-DbaSqlService][15:03:41] Getting SQL Server namespace on XXX
VERBOSE: [Get-DbaCmObject][15:03:41] Configuration loaded | Cache disabled: False
VERBOSE: [Get-DbaCmObject][15:03:41] [XXX] Retrieving Management Information
WARNING: [Get-DbaSqlService][15:03:42] No ComputerManagement Namespace on XXX. Please note that this function is available from SQL 2005 up.
```
## Different tests : 
```
Get-DbaCmObject -ComputerName XXX -Credential XXX -NameSpace root\Microsoft\SQLServer -Query "Select Name FROM __NAMESPACE WHERE Name Like 'ComputerManagement%'"

Name                 PSComputerName
----                 --------------
ComputerManagement13 XXX

Get-DbaCmObject -ComputerName XXX -Credential XXX -NameSpace root\Microsoft\SQLServer -Query "Select Name FROM __NAMESPACE WHERE Name Like 'ComputerManagement%'" -EnableException | Sort-Object Name -Descending

Name                 PSComputerName
----                 --------------
ComputerManagement13 XXX
```

**Comment by FriedrichWeinmann** [comment] 2018-01-09 09:39
Sorry for the late reply, summing up the situation and requesting opinions:

Issue is our habit of calling `Resolve-DbaNetworkName`, which strips away the fqdn. This makes several of our commands inoperable acros domain boundaries. General consensus was to not translate input anymore.

With that in mind, I propose solving this like this:

 - Removing all internal use of `Resolve-DbaNetworkName`
 - Replacing the output PSObject with a strongly typed object defined in our library
 - Rewriting `Resolve-DbaNetworkName` so that instance connection information survives
 - Update `[DbaInstance]` to understand this type

This would allow users to pipe instance information through `Resolve-DbaNetworkName` before executing commands.
This would however constitute a breaking change in cases where users relied on our resolution methods.

Any comments on this solution?

Cheers,
Fred

**Comment by niphlod** [comment] 2018-01-09 10:50
if the problem is commands stripping the FQDN the solution is them using the correct property for what they need. If they need the qualified domain name of the underlying server as the DNS sees it, they should use FullComputerName.

**Comment by FriedrichWeinmann** [comment] 2018-01-09 11:15
Totally agree - if all I wanted to fix was the FQDN issue, `FullComputerName` would solve it.
I'm just not comfortable with automatically resolving it for the user, given time expense and loss of control over input.
The proposed solution's primary concern is usability of explicitly resolving names.

**Comment by niphlod** [comment] 2018-01-09 11:20
well, if a resolution is needed, either done via resolve-dbanetworkname or with anything else, the resolution would happen nonetheless, no ?

**Comment by FriedrichWeinmann** [comment] 2018-01-09 11:22
Sure, but should _we_ make the decision for the user when & whether to resolve it?
Cause currently it also resolves when it is not needed.

**Comment by niphlod** [comment] 2018-01-09 11:28
well, it should be the calling function that knows when to resolve and when to not to

**Comment by FriedrichWeinmann** [comment] 2018-01-09 11:35
Well, it can't really know it.
Imagine this input: `full.fqdn.local`
Before spending network time looking it up, the local code has no way to know:

 - Is it the full fqdn ready to target
 - Is it a cname? (It knows of course whether cnames work for it, but not whether it is one)
 - Is it cluster name? (It knows whether it'd need to resolve a cluster to the physical host of course)

Unless we have that information cached somewhere, at which point we open the can for the full caching question. As it is, we always resolve in the commands that use it, whether it was needed or not.

**Comment by niphlod** [comment] 2018-01-09 12:55
ahhhhh ok. it'd solve also "down the line I need the fqdn but an fqdn was already passed in so no time should be spent on it".... though, "it" needs to be sure that no matter the format passed in, full.fqdn.local is "correctly" resolved

**Comment by EmDBA** [comment] 2018-01-12 15:09
#3030 This merge solved the problem with Get-DbaSqlService but not with Restart-DbaSqlService.

**Comment by potatoqualitee** [comment] 2018-11-16 01:52
looks like the command now uses `FullComputerName` which was our ultimately solution. thanks to @nvarscar 's updates. This should be fixed, please reopen if it's not.

**Closed by potatoqualitee** 2018-11-16 01:52 UTC
Labels: bugs_life
