### ISSUE TITLE
Get-DbaDatabaseFile, wrong properties returned 

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1246] opened 2017-05-17 16:23 UTC
## Is this:
- [ ] *feature* 
- [x] *bug*:

When querying for UsedSpace for database snapshots size_on_disk_bytes from dm_io_virtual_file_stats should be used  to discern the actual usage of the sparse file.

Also, for Size, Used and Available I think calcs are plain wrong for all databases (not only snapshots)

**Comment by niphlod** [comment] 2017-05-17 23:04
hint: the correct calcs to update for every database would be 

`$result.Size / 128.0 * 1024 * 1024`

more on the snapshot later... I'd need someone to test them on a 2005 instance

**Comment by backintheday41** [comment] 2017-06-08 12:37
Just adding verification that some calculations are incorrect:

    PS> Get-DbaDatabaseFile -SqlInstance Server1 -Databases Db1 | Select TypeDescription,Size
    
    TypeDescription Size    
    --------------- ----    
    ROWS            38.68 TB
    LOG             1.38 TB 
    
    PS> Get-DbaDatabase -SqlInstance Server1 -Databases Db1 | Select SizeMB
    
        SizeMB
        ------
    328143.9375

Get-DbaDatabase is returning the correct size.

**Comment by dbaduck** [comment] 2017-07-14 01:00
Also on the Size, it gets returned as a string, so when you want to sort on the Size you get a weird sort order.  I think it should come out as a number and the label should be Size_GB or something it should be something that is in the documentation that indicates that it will be in GB, but it should be a number so it can be sorted.  Thanks.

**Comment by dbaduck** [comment] 2017-07-14 01:05
I think that the Size property should act like the Get-DbaDiskSpace function has the data for the sizes.  Whenever I do a Format-Table the sizes are all right aligned and the header have inGB instead of having GB or MB in the string.  But even if you wanted to keep the GB or MB then it should be right justified so that it looks better and lines up. Thanks.

**Comment by wsmelton** [comment] 2017-07-15 02:23
@dbaduck The right alignment is default nature of PowerShell.

With regards to having the unit measurement in the output is part of the custom types in the module. If you check the code you will notice we set the [type of the output property](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Get-DbaDatabaseFile.ps1#L213). That is as by design.

**Comment by wsmelton** [comment] 2017-07-15 02:27
However, @potatoqualitee @FriedrichWeinmann should note that this output prevents you from doing any comparison like:

```powershell
Get-DbaDatabaseFile -SqlInstance manatarms -Database AdventureWorks2012 | where Size -gt 300 | select Database, LogicalName, Size
```

**Comment by potatoqualitee** [comment] 2017-07-23 19:27
this appears to be completed, please let me know if that is not the issue and i'll repoen. but @wsmelton - your query did work for me

**Closed by potatoqualitee** 2017-07-23 19:27 UTC
Labels: Status: In Progress, Type: Bug
