### ISSUE TITLE
PS7 needs MultiSubnetFailover while connecting with Connect-DbaInstance in some situations

### ISSUE THREAD

**Issue by Tottenham84** [sqlcollaborative/dbatools#6454] opened 2020-04-03 13:05 UTC
### Environmental information

```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



#### dbatools Module version:

Name    : dbatools
Path    : D:\Users\usrname\Documents\PowerShell\Modules\dbatools\1.0.104\dbatools.psd1
Version : 1.0.104

Name    : dbatools
Path    : D:\Users\usrname\Documents\PowerShell\Modules\dbatools\1.0.102\dbatools.psd1
Version : 1.0.102



```

```powershell
LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)
```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU11) (KB4527378) - 13.0.5598.27 (X64)   Nov 27 2019 18:09:22   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 	

```

```sql
us_english
```

### Report
Recently with the release of Powershell 7 I've started testing dbatools to do some of my work. I've found that when contacting Availability Group Listeners that have multiple IP addresses specified it sometimes times out. 

Get-DbaAgReplica -SqlInstance <servername>

WARNING: [08:30:57][Get-DbaAvailabilityGroup] Failure. | The wait operation timed out.

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [x] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling `"Open`" with `"0`" argument(s): "Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=21004; handshake=0; "
                         ---> System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=21004; handshake=0; 
                         ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                        ClientConnectionId:0f486852-8855-4c54-b886-639bbd641d66
                        Error Number:-2,State:0,Class:11
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at Connect-DbaInstance<Process>(Closure , FunctionContext )
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : SqlException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Connect-DbaInstance<Process>, D:\Users\username\Documents\PowerShell\Modules\dbatools\1.0.102\allcommands.ps1: line 2569
                        at Connect-SqlInstance, D:\Users\username\Documents\PowerShell\Modules\dbatools\1.0.102\allcommands.ps1: line 75092
                        at Get-DbaAvailabilityGroup<Process>, D:\Users\username\Documents\PowerShell\Modules\dbatools\1.0.102\allcommands.ps1: line 19798
                        at Get-DbaAgReplica<Process>, D:\Users\username\Documents\PowerShell\Modules\dbatools\1.0.102\allcommands.ps1: line 19761
                        at <ScriptBlock>, <No file>: line 3
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
#### Steps to Reproduce

1. Create a few availability groups with multiple IP addresses set on the listener
2. Connect to them with the availability group name

Get-DbaAgReplica -SqlInstance <servername>
#### Expected Behavior
I expect it to not time out sometimes.

#### Actual Behavior
It sometimes times out

**Comment by garyhampson** [comment] 2020-05-11 16:08
I'm experiencing the same issue with PS 6.2.4. I don't have any issues with PS 5.1.
![image](https://user-images.githubusercontent.com/29409339/81583850-f0e6ab00-937f-11ea-9104-99c2c3f3e3f5.png)
![image](https://user-images.githubusercontent.com/29409339/81583871-f8a64f80-937f-11ea-8c72-6f163db8f222.png)

**Comment by garyhampson** [comment] 2020-05-11 16:19
Here's the configuration of my AG. Nothing out of the ordinary apart from both listener IP addresses being registered.
![image](https://user-images.githubusercontent.com/29409339/81584958-7585f900-9381-11ea-9a96-6d67d23d4f63.png)

**Comment by garyhampson** [comment] 2020-07-12 17:49
This is still reproducible.

**Comment by wsmelton** [comment] 2020-07-12 18:52
The pre-login handshake timeout is SQL Server side of the call, not with our module.

Have you tried increasing the -ConnectionTineout parameter with  Connect-DbaInstance? (Or you can check Get-DbatoolsConfig to get the property we use for it at the module level, unsure the exact name. You can then use Set-DbatoolsConfig to set that value for your session.)

Why it effects PowerShell 7 and not Windows PowerShell I'm not sure.

I'd note that we likely won't put any focus making the module work in PowerShell 6.2 because that goes out of support on September, and it is recommended by Microsoft to use 7.0 now as well.

**Comment by Tottenham84** [comment] 2020-07-12 20:50
Shawn,

It looks to be how .net core library is handling the DNS management of
connection to a multi subnet dns entry.

With ps5 the dbatools command handles this management fine without issue.

With pwsh 7 the same command doesn't handle dns of multisubnet dns entry
cleanly.

I have been able to work around this but it requires using a different
command with multisubnet failover option enabled to get the primary replica
of the AG. Then pass any future command the primary replica.

I am able to replicate the issue. Please let me know what other information
I can provide to help tract down the issue.


Justin

**Comment by wsmelton** [comment] 2020-07-12 20:53
Are you doing this test from the same Windows machine?

To fully test and debug we will have to get a network setup to verify if we can also the commands to handle it more efficiently.

**Comment by Tottenham84** [comment] 2020-07-12 23:14
Hi Shawn,

Yes, there is a single windows workspace connecting to all the availability
groups.

Please let me know next steps.

Thank you,
Justin

**Comment by andreasjordan** [comment] 2021-05-19 08:23
@Tottenham84 Sorry, has been lost from sight. Can you give me a quick hello here if you would like to work with me so solve the problem?

**Comment by andreasjordan** [comment] 2021-05-21 18:09
@Tottenham84 : Great to hear from you.
Can you do me a favor and retest with the current version of dbatools and also try the new code path inside of Connect-DbaInstance?
You activate the new code path by `Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true`. This will be valid for the current powershell session only.

I will have a look at this issue when I've setup my lab with AGs and also installed PowerShell 7.

**Comment by Tottenham84** [comment] 2021-05-21 19:35
Hi Andreas,

I've tested utilizing the latest version (I did update-dbatools to get
latest version) and still have the same issue.
---------
PS D:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS D:\> Get-InstalledModule dbatools

Version              Name                                Repository
   Description
-------              ----                                ----------
   -----------
1.0.149              dbatools                            PSGallery
  The community module that enables SQL Server Pros to automate database
development and server administration

PS D:\> Set-DbatoolsConfig -FullName sql.connection.experimental -Value
$true
PS D:\> Get-DbaAgReplica -SqlInstance <server>
WARNING: [15:31:28][Get-DbaAgReplica] Failure on <server> to obtain the
availability group  | The wait operation timed out.

---------

Please let me know what other information needed to help troubleshooting.

Thank you,
Justin

**Comment by andreasjordan** [comment] 2021-05-31 17:50
I would like you to try separating the connection to the server from gathering of information.

So instead of `Get-DbaAgReplica -SqlInstance <server>` try to do two steps:
```
$server = Connect-DbaInstance -SqlInstance <server>
$replica = Get-DbaAgReplica -SqlInstance $server
```
I would like to know which command timed out.

If you get `$server`, you could also try to get `$server.AvailabilityGroups` and `$server.AvailabilityGroups.AvailabilityReplicas`, which is what the commands basically do.

**Comment by Tottenham84** [comment] 2021-06-14 11:41
Hey Andreas,

Sorry for the late reply. The Connect-DBAInstance is what times out.

PS D:\Users\<user>> pwsh
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS D:\Users\<user>> $server = Connect-DbaInstance -SqlInstance <server>
Exception:
D:\Users\jproca\<user>\PowerShell\Modules\dbatools\1.0.149\allcommands.ps1:88694
 Line |
88694 |          throw $records[0]
      |          ~~~~~~~~~~~~~~~~~
      | The wait operation timed out.


However, if I add the flag -MultiSubnetFailover it will return immediately.
PS D:\Users\<user>> $server = Connect-DbaInstance -SqlInstance <server>
-MultiSubnetFailover
PS D:\Users\<user>> $server

ComputerName  Name      Product              Version   HostPlatform IsAzure
IsClustered ConnectedAs
------------  ----      -------              -------   ------------ -------
----------- -----------
<replica name> <AGName> Microsoft SQL Server 13.0.5865 Windows      False
 False       <domain>\<user>

With powershell 5.1 we are able to use Connect-DBAInstance and
Get-DBAAgReplica without having to add the -MultiSubnetFailover flag and
have 100% successful runs. It looks like the underlying driver or connector
has changed how it handles the listener lookup. I know some of the newer
drivers like jdbc have Transparent Network IP Resolution which essentially
does the MultiSubnetFailover flag when it comes to being able to connect
easily to a multi subnet listener . Using Transparent Network IP Resolution
- ODBC Driver for SQL Server | Microsoft Docs
<https://docs.microsoft.com/en-us/sql/connect/odbc/using-transparent-network-ip-resolution?view=sql-server-ver15>


I've been doing something similar in my scripts to bypass the issue. I use
the -MultiSubnetFailover flag in Connect-DBAInstance then use the primary
replica for the Get-DBAAG* commands, but with your insight I can look to
just use the properties under $server. to save an additional call for now.

I don't know what changed or what can be done to resolve, so we can use all
the Get-DBAAG* commands without timeout in pwsh 6/ pwsh 7.

Thank you,
Justin

**Comment by andreasjordan** [comment] 2021-06-14 14:59
If we agree that the problem is located inside me SMO - than there is nothing we can do.
I have written a blog post that might help here: https://blog.ordix.de/dbatools-a-simple-database-query-with-invoke-dbaquery
(Nearly) all commands take the input from SqlInstance and pass it on to Connect-DbaInstance. If you pass in a server SMO (that you get from Connect-DbaInstance), it is only just returned. So your workaround would be, to always first get `$server = Connect-DbaInstance -SqlInstance ... -MultiSubnetFailover` and then to use `$server` with all following calls to this instance as `-SqlInstance`. It would even be faster, because only one connection is used for all calls.

**Comment by andreasjordan** [comment] 2021-06-14 14:59
If you agree I would close this issue.

**Comment by Tottenham84** [comment] 2021-06-14 16:26
Andreas,

I don't agree. Please see below with some ideas.

Could you update the call to connect-dbainstance to always use multisubnet
failover flag? I don't think this will hurt performance of a listener that
has only 1 ip address?

Or

Can you provide a switch param MULTISUBNETFAILOVER
 for AG related functions? Right now for get-dbaavailabilitygroup calls the
internal function connect-sqlinstance will splat it into
connect-dbainstance the parms from the main function call.

I would also be interested if the new microsoft.data.sqlclient fixes this
issue. I understand it's in preview but looks like MS is suggestion this
will be the future.


Justin

**Comment by wsmelton** [comment] 2021-06-14 16:45
The ability for you to control the connection settings and then pass that to our commands it intentional and by design.

Environmental issues cannot be predicted for everyone, which is what this sounds like it is specific to your AG configuration. I don't see any reason right off to add a parameter for this, especially across all our AG commands.

**Comment by andreasjordan** [comment] 2021-06-14 16:53
We have some parameters for Connect-DbaInstance that have defaults fetched from config parameters. Maybe we can add that for MultiSubnetFailover as well? But as this switch just adds ";MultiSubnetFailover=True" to the connection string, we can also add a config parameter for `-AppendConnectionString` and you fill it with ";MultiSubnetFailover=True" - that would have the same result and would maybe serve some more cases.

**Comment by andreasjordan** [comment] 2021-06-15 09:26
I will change this from a bug report to a feature request.
As I have an open pull request for Connect-DbaInstance I will wait for this to be merged and then start working on this.

**Comment by Tottenham84** [comment] 2021-06-15 16:44
Thank you @andreasjordan  and @wsmelton for your help on this. 
Justin

**Comment by potatoqualitee** [comment] 2021-07-19 12:19
hey all -- we just updated our SMO a whole major version. We haven't released it to the PowerShell Gallery yet, but if you're able to test with the development branch, that will be helpful to us. I've got some hope that this will be addressed with our major changes.

**Comment by Tottenham84** [comment] 2021-07-27 21:34
Hey Chrissy,

I've tested the dev branch and I'm still hitting the same error.

Thank you,
Justin

**Comment by potatoqualitee** [comment] 2021-07-27 23:30
Nooooooooo 😭  K, ill submit a PR to add MultiSubnetFailover to our configs like we do with other connect parameters

**Comment by Tottenham84** [comment] 2021-07-28 02:29
Thank you Chrissy. You're the best! Been following you for many years now.
Amazing what you do for the community.

Justin

**Comment by potatoqualitee** [comment] 2021-07-28 02:30
Thank you, Justin! You made my day 😊

**Closed** 2021-07-28 06:55 UTC
Labels: feature, smo
