### ISSUE TITLE
Copy-SqlDatabase is causing stackoverflowexception error

### ISSUE THREAD

**Issue by jowee12** [sqlcollaborative/dbatools#1481] opened 2017-06-24 12:16 UTC
Copy-SqlDatabase -Source 2008svrs -Destination 2008svrd -BackupRestore -NetworkShare \\am-dmc1\dbtransfer  -Databases AdventureWorks,AdventureWorksLT -NoBackupCleanup -verbose

screenshot
![image](https://user-images.githubusercontent.com/5501528/27508541-b4d7f72a-58e7-11e7-88e0-4b379470a03b.png)

**Comment by wsmelton** [comment] 2017-06-24 23:12
I don't believe this is directly related to the command. If you start a new session and issue the command does it happen each time?

**Comment by jowee12** [comment] 2017-06-26 09:44
Yes it happens each time...

**Comment by jowee12** [comment] 2017-06-27 12:52
@wsmelton I ran the same cmdlets on win10 without any issue. Could this be OS problem/limitation?

**Comment by wsmelton** [comment] 2017-06-28 02:03
I don't know about limitation unless that machine is considerably small. What are version specifics about the machine?

**Comment by jowee12** [comment] 2017-06-28 06:17
Its Windows 7 Sp1, 2GB RAM, powershell v5.1, ssms 2008R2

**Comment by wsmelton** [comment] 2017-06-28 16:02
Only 2GB?!!? Yeah, I would say that is your problem.

How much RAM does that Windows 10 machine have?

**Comment by potatoqualitee** [comment] 2017-06-28 16:18
We have a Win7 test with 3GB of ram. I can test as well. brb

**Comment by jowee12** [comment] 2017-06-29 06:31
@wsmelton the Win10 have 12GB of RAM on it and its physical machine unlike the Win7 it's virtual! At first, i thought it has something to do with both source and destination servers, so I make changes to the MAXMEMORYPERSHELLMB but the problem persists.

@potatoqualitee what is the outcome of your test?

**Comment by wsmelton** [comment] 2017-06-29 15:59
I have a VDI on Windows 7 that is 3GB and can tell you I can't do anything in PowerShell on that VM. I don't even bother trying.

An overflow exception regardless is being thrown by PowerShell and is irrelevant what module you may be using. I mean if you do something equal of work with AD cmdlets or the sqlserver module you will likely get the same result.

**Comment by TomVergote** [comment] 2017-07-12 12:46
The windows event log shows these 2 events on every crash

Log Name:      Application
Source:        Application Error
Date:          7/12/2017 2:04:50 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      MC3-SQL1.mcthree.local
Description:
Faulting application name: powershell.exe, version: 10.0.10586.117, time stamp: 0x56bf0886
Faulting module name: clr.dll, version: 4.7.2053.0, time stamp: 0x58fa6bb3
Exception code: 0xc00000fd
Fault offset: 0x0001b35b
Faulting process id: 0x940
Faulting application start time: 0x01d2fb0702bddef7
Faulting application path: C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Report Id: 4e2a7be9-66fa-11e7-80da-005056922ec0
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-07-12T12:04:50.000000000Z" />
    <EventRecordID>6983</EventRecordID>
    <Channel>Application</Channel>
    <Computer>MC3-SQL1.mcthree.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>powershell.exe</Data>
    <Data>10.0.10586.117</Data>
    <Data>56bf0886</Data>
    <Data>clr.dll</Data>
    <Data>4.7.2053.0</Data>
    <Data>58fa6bb3</Data>
    <Data>c00000fd</Data>
    <Data>0001b35b</Data>
    <Data>940</Data>
    <Data>01d2fb0702bddef7</Data>
    <Data>C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe</Data>
    <Data>C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll</Data>
    <Data>4e2a7be9-66fa-11e7-80da-005056922ec0</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>


Log Name:      Application
Source:        Windows Error Reporting
Date:          7/12/2017 2:04:53 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      MC3-SQL1.mcthree.local
Description:
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: powershell.exe
P2: 10.0.10586.117
P3: 56bf0886
P4: clr.dll
P5: 4.7.2053.0
P6: 58fa6bb3
P7: c00000fd
P8: 0001b35b
P9: 
P10: 

Attached files:

These files may be available here:
C:\Users\tvg\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_powershell.exe_80ab64541c299c588a9a958871c71c8626417f3a_d0d55dfd_02cbd1b5

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4e2a7be9-66fa-11e7-80da-005056922ec0
Report Status: 2048
Hashed bucket: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-07-12T12:04:53.000000000Z" />
    <EventRecordID>6984</EventRecordID>
    <Channel>Application</Channel>
    <Computer>MC3-SQL1.mcthree.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>powershell.exe</Data>
    <Data>10.0.10586.117</Data>
    <Data>56bf0886</Data>
    <Data>clr.dll</Data>
    <Data>4.7.2053.0</Data>
    <Data>58fa6bb3</Data>
    <Data>c00000fd</Data>
    <Data>0001b35b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>C:\Users\tvg\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_powershell.exe_80ab64541c299c588a9a958871c71c8626417f3a_d0d55dfd_02cbd1b5</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>4e2a7be9-66fa-11e7-80da-005056922ec0</Data>
    <Data>2048</Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by TomVergote** [comment] 2017-07-12 12:48
Attached the output of New-DbatoolsSupportPackage
[dbatools_support_pack_2017_07_12-14_43_01.zip](https://github.com/sqlcollaborative/dbatools/files/1141975/dbatools_support_pack_2017_07_12-14_43_01.zip)

**Comment by TomVergote** [comment] 2017-07-12 13:02
Windows error reports zipped
[AppCrash.zip](https://github.com/sqlcollaborative/dbatools/files/1142039/AppCrash.zip)

**Comment by TomVergote** [comment] 2017-07-12 13:41
The same error occurs when running only Backup-DbaDatabase. I gathered a support package for this one too (please note, I can only generate support packages from within a new session as the session exhibiting the problem is already crashed hard)
[dbatools_support_pack_2017_07_12-15_29_06.zip](https://github.com/sqlcollaborative/dbatools/files/1142118/dbatools_support_pack_2017_07_12-15_29_06.zip)

**Comment by TomVergote** [comment] 2017-07-12 14:38
OK, So the problem is with the automatic conversion of the recoverymodel Enum to a string.

These three approaches fix it:

if ($Database.RecoveryModel -ne [Microsoft.SqlServer.Management.Smo.RecoveryModel]::Simple -and $Type -eq 'Log') {

OR

if ($Database.RecoveryModel.ToString() -ne 'Simple' -and $Type -eq 'Log') {

OR 

$dbRecovery = $Database.RecoveryModel.ToString()
if ($dbRecovery -ne 'Simple' -and $Type -eq 'Log') {

I'll look into creating a PR later today

**Comment by ConstantineK** [comment] 2017-12-18 16:12
Closing, merged.

**Closed by ConstantineK** 2017-12-18 16:12 UTC
Labels: bugs_life
