### ISSUE TITLE
Restore-DbaDatabase - WithReplace does not respect destination data directories

### ISSUE THREAD

**Issue by cpurules** [sqlcollaborative/dbatools#7956] opened 2021-11-17 15:39 UTC
### Verified issue does not already exist?

Yes

### What error did you receive?

No error as the command completes successfully but does not behave as expected.

Expected behavior: the database is restored and the data files reside in the appropriate location on the appropriate drive, i.e. where they already were:
- AdventureWorks -> S:\Data\AdventureWorks_Restored.mdf
- AdventureWorks_Index -> I:\Data\AdventureWorks_Restored_Index.ldf
- AdventureWorks_Log -> L:\Log\AdventureWorks_Restored.ldf

Actual behavior: the database is restored, **but the index file is moved to the Data location on the S: drive**:
- AdventureWorks -> S:\Data\AdventureWorks_Restored.mdf
- AdventureWorks_Index -> **S:\Data\AdventureWorks_Restored_Index.ldf**
- AdventureWorks_Log -> L:\Log\AdventureWorks_Restored.ldf

### Steps to Reproduce

Consider a backup file **AdventureWorks.bak** for a database **AdventureWorks**, which has 3 data files in the following locations:
- AdventureWorks (PRIMARY filegroup, rows) -> S:\Data\AdventureWorks.mdf
- AdventureWorks_Index (IndexGroup filegroup, rows) -> I:\Data\AdventureWorks_Index.ldf
- AdventureWorks_Log (log) -> L:\Log\AdventureWorks.ldf

Additionally consider a copy of the database on the same server that is the restore target, **AdventureWorks_Restored**, which has the data files in the same locations:
- AdventureWorks -> S:\Data\AdventureWorks_Restored.mdf
- AdventureWorks_Index -> I:\Data\AdventureWorks_Restored_Index.ldf
- AdventureWorks_Log -> L:\Log\AdventureWorks_Restored.ldf

The default data directories on the SQL Server:
- Data -> S:\Data\
- Log -> L:\Log\

Execute the below PowerShell, with variables adjusted as necessary
```powershell
# DUMMY VARIABLES #
$TargetInstance = 'Server1'
$TargetDBName = 'AdventureWorks_Restored'
$TargetFilePath = 'K:\AdventureWorks.bak'

# Restore Command
Restore-DbaDatabase     -SqlInstance $TargetInstance `
                            -DatabaseName $TargetDBName `
                            -Path $TargetFilePath `
                            -ReplaceDbNameInFile `
                            -WithReplace `
                            -WarningAction Stop `
                            -verbose
```

Expected behavior: the database is restored and the data files reside in the appropriate location on the appropriate drive, i.e.:
- AdventureWorks -> S:\Data\AdventureWorks_Restored.mdf
- AdventureWorks_Index -> I:\Data\AdventureWorks_Restored_Index.ldf
- AdventureWorks_Log -> L:\Log\AdventureWorks_Restored.ldf

Actual behavior: the database is restored, **but the index file is moved to the Data location on the S: drive**:
- AdventureWorks -> S:\Data\AdventureWorks_Restored.mdf
- AdventureWorks_Index -> **S:\Data\AdventureWorks_Restored_Index.ldf**
- AdventureWorks_Log -> L:\Log\AdventureWorks_Restored.ldf

### Are you running the latest release?

Yes

### Other details or mentions

I can see the following output in the verbose logging from the command:

```
VERBOSE: [10:27:22][Restore-DbaDatabase] Processing DatabaseName - AdventureWorks_Restored
VERBOSE: [10:27:22][Format-DbaBackupInformation] Starting
VERBOSE: [10:27:22][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [10:27:22][Format-DbaBackupInformation] New DbName (String) = AdventureWorks_Restored
VERBOSE: [10:27:22][Format-DbaBackupInformation]  1 PhysicalName = S:\Data\AdventureWorks_Restored_Data.mdf 
VERBOSE: [10:27:22][Format-DbaBackupInformation] PhysicalName = S:\Data\AdventureWorks_Restored_Data.mdf 
VERBOSE: [10:27:22][Format-DbaBackupInformation]  1 PhysicalName = I:\Data\adventureworks_restored_Index.ldf 
VERBOSE: [10:27:22][Format-DbaBackupInformation] PhysicalName = S:\Data\adventureworks_restored_Index.ldf 
VERBOSE: [10:27:22][Format-DbaBackupInformation]  1 PhysicalName = L:\Log\AdventureWorks_Restored_Log.ldf 
VERBOSE: [10:27:22][Format-DbaBackupInformation] PhysicalName = L:\Log\AdventureWorks_Restored_Log.ldf 
```

This also occurs without the `-ReplaceDbNameInFile` parameter.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

```
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.14393.4583                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14393.4583                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   
```

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-CU17) (KB5001092) - 13.0.5888.11 (X64)   Mar 19 2021 19:41:38   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.3870.0

**Comment by andreasjordan** [comment] 2021-11-17 16:10
Thanks for reporting this.

Here is the relevant code from Format-DbaBackupInformation:

```
if ($ReplaceDbNameInFile -eq $true) {
	$_.PhysicalName = $_.PhysicalName -Replace $History.OriginalDatabase, $History.Database
}
Write-Message -Message " 1 PhysicalName = $($_.PhysicalName) " -Level Verbose
$Pname = [System.Io.FileInfo]$_.PhysicalName
$RestoreDir = $Pname.DirectoryName
if ($_.Type -eq 'D' -or $_.FileType -eq 'D') {
	if ('' -ne $DataFileDirectory) {
		$RestoreDir = $DataFileDirectory
	}
} elseif ($_.Type -eq 'L' -or $_.FileType -eq 'L') {
	if ('' -ne $LogFileDirectory) {
		$RestoreDir = $LogFileDirectory
	} elseif ('' -ne $DataFileDirectory) {
		$RestoreDir = $DataFileDirectory
	}
} elseif ($_.Type -eq 'S' -or $_.FileType -eq 'S') {
	if ('' -ne $DestinationFileStreamDirectory) {
		$RestoreDir = $DestinationFileStreamDirectory
	} elseif ('' -ne $DataFileDirectory) {
		$RestoreDir = $DataFileDirectory
	}
}

$_.PhysicalName = $RestoreDir + $PathSep + $DatabaseFilePrefix + $Pname.BaseName + $DatabaseFileSuffix + $Pname.extension
Write-Message -Message "PhysicalName = $($_.PhysicalName) " -Level Verbose
```

Looks like `'' -ne $DataFileDirectory` is `$true` and so `$RestoreDir = $DataFileDirectory` is set.

Will continue to analyse...

**Comment by andreasjordan** [comment] 2021-11-17 16:17
Does it work correctly without `-WithReplace`? At the moment I cannot see the link to `-WithReplace`.

**Comment by andreasjordan** [comment] 2021-11-17 16:25
Ok, I can reproduce the issue. But this may be by design. When `-ReuseSourceFolderStructure` is used, the files should be placed in the correct directory.

**Comment by andreasjordan** [comment] 2021-11-17 16:30
Code from Backup-DbaDatabase says:

```
if ($PSCmdlet.ParameterSetName -eq "Restore") {
    $UseDestinationDefaultDirectories = $true
}

if (($null -ne $FileMapping) -or $ReuseSourceFolderStructure -or ($DestinationDataDirectory -ne '')) {
    $UseDestinationDefaultDirectories = $false
}
```

So you have to use `-ReuseSourceFolderStructure` in case you have a data file in a non-default directory.

Will close this, but you can reopen it, if you have further questions.

**Closed by andreasjordan** 2021-11-17 16:30 UTC
Labels: bugs life, triage required

**Comment by cpurules** [comment] 2021-11-17 16:37
> Does it work correctly without `-WithReplace`? At the moment I cannot see the link to `-WithReplace`.

We need to use -WithReplace because the target database already exists, at least in this scenario.

> Ok, I can reproduce the issue. But this may be by design. When `-ReuseSourceFolderStructure` is used, the files should be placed in the correct directory.

I see.  I think I skipped over this because I was interested in destination folder structure rather than source folder structure - even though it appears per the docs that the combination of `-ReuseSourceFolderStructure` **and** `-WithReplace` will actually do what I was hoping for.

I just tested and it appears to be correct.  Sorry for the erroneous bug report.  I do think there is an opportunity for making this clearer somewhere (maybe a parameter name change, although that would be breaking), but this solves my issue.  Thank you!

**Comment by andreasjordan** [comment] 2021-11-17 16:44
@Stuart-Moore : What do you think about adding more information to the description?

The parameter ReuseSourceFolderStructure has this documentation: "By default, databases will be migrated to the destination Sql Server's default data and log directories. You can override this by specifying -ReuseSourceFolderStructure. The same structure on the SOURCE will be kept exactly, so consider this if you're migrating between different versions and use part of Microsoft's default Sql structure (MSSql12.INSTANCE, etc)"

Maybe we should add "By default, databases will be restored to the destination SQL Server's default data and log directories. You can override this by specifying -ReuseSourceFolderStructure." to the description?
