### ISSUE TITLE
Export-SqlLogin should exclude database snapshots

### ISSUE THREAD

**Issue by arvindravish** [sqlcollaborative/dbatools#297] opened 2016-11-01 22:13 UTC
Logins for database snapshots are also scripted.

**Comment by ConstantineK** [comment] 2016-11-20 22:30
Hey @arvindravish,
I was thinking about this issue and had a few questions with regard to this as I dont use snapshots that often.

Why not?
Is it the fact that they may be a duplicate of another login that should already exist?

I was under the impression a snapshot, while being tied to the source, was a unique database and you could have unique permissions assigned to it, which you may want to migrate to your new snapshot on your new instance.

Just wondering some further details so I can dig into this, thanks!

**Comment by ConstantineK** [comment] 2016-11-26 14:25
Hey @arvindravish, I am going to close this until I get a response or further details why this is a good idea, I am not against it per-se but I don't fully understand why this shouldn't be the case or why this shouldn't be facilitated with a switch/flag.

**Closed by ConstantineK** 2016-11-26 14:25 UTC
