### ISSUE TITLE
Copy_DBaDatabase

### ISSUE THREAD

**Issue by dyard12** [sqlcollaborative/dbatools#3572] opened 2018-04-27 23:02 UTC
### General Troubleshooting steps

- [ ] Verified running the latest release of dbatools? YES
- [ ] Verified errors are not related to permissions? YES
Only 7 databases cant copy the rest about 30 are ok

### Version Information
 - Operating System (Name|Version): 
 - PowerShell Version: 
 - SQL Server (Edition|Version): <FROM 
Microsoft SQL Server 2008 (SP4) - 10.0.6000.29 (Intel X86) 
	Sep  2 2014 22:55:13 
	Copyright (c) 1988-2008 Microsoft Corporation
	Enterprise Edition on Windows NT 6.0 <X86> (Build 6002: Service Pack 2) (VM)

TO 
Microsoft SQL Server 2016 (SP1-GDR) (KB4057118) - 13.0.4210.6 (X64) 
	Dec 22 2017 15:00:27 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: ) (Hypervisor)
 -->

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 3:53:57 PM  Copy-DbaDatabase            Verbose                      Building file structure inventory for 1 databases.                                                             
4/27/2018 3:53:57 PM  Get-SqlFileStructure        Verbose                      DB                                                                                                    
4/27/2018 3:53:57 PM  Copy-DbaDatabase            Verbose                      ...                                                                                                            
4/27/2018 3:53:57 PM  Copy-DbaDatabase            Verbose                      Checking for accessibility.                                                                                    
4/27/2018 3:53:57 PM  Copy-DbaDatabase            Verbose                      Checking Availability Group status.                                                                            
4/27/2018 3:53:57 PM  Copy-DbaDatabase            Verbose                      Started: 04/27/2018 15:53:57.                                                                                  
4/27/2018 3:53:57 PM  Backup-DbaDatabase          Verbose                      Connecting to server                                                                                        
4/27/2018 3:53:57 PM  Backup-DbaDatabase          Verbose                      1 database to backup                                                                                           
4/27/2018 3:53:57 PM  Backup-DbaDatabase          Verbose                      Backup database [DB]                                                                                  
4/27/2018 3:53:57 PM  Backup-DbaDatabase          VeryVerbose                  Creating full backup                                                                                           
4/27/2018 3:53:57 PM  Backup-DbaDatabase          VeryVerbose                  Sorting Paths                                                                                                  
4/27/2018 3:53:57 PM  Backup-DbaDatabase          VeryVerbose                  Setting filename                                                                                               
4/27/2018 3:53:57 PM  Backup-DbaDatabase          Verbose                      Striping for Filecount of 3                                                                                    
4/27/2018 3:53:57 PM  Backup-DbaDatabase          Verbose                      Devices added                                                                                                  
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        System                       Active Parameterset: Last.                                                                                     
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        System                       Bound parameters: SqlInstance, Database, Last, IncludeCopyOnly                                                 
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        VeryVerbose     MSSQLSERVER  Connecting to server                                                                                        .                                                                                       
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        System                       Active Parameterset: Last.                                                                                     
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        System                       Bound parameters: SqlInstance, Database, LastFull, Raw, DeviceType, IncludeCopyOnly                            
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        VeryVerbose     MSSQLSERVER  Connecting to server                                                                                        .                                                                                       
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        Verbose                      Processing DB
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        Debug                        ...                                                                                                            
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        SomewhatVerbose              Executing sql query.                                                                                           
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        SomewhatVerbose              Processing as grouped output.                                                                                  
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        SomewhatVerbose              1 result-groups found.                                                                                         
4/27/2018 3:54:13 PM  Get-DbaBackupHistory        Debug                        FileSQL: SELECT backup_set_id, file_type as FileType, logical_name as LogicalName, physical_name as Physical...
4/27/2018 3:54:13 PM  Backup-DbaDatabase          Warning                      Backup Failed:  Exception setting "LastRecoveryForkGuid": "Cannot convert value "" to type "System.Guid". Er...
4/27/2018 3:54:13 PM  Copy-DbaDatabase            Verbose                      Resuse = False.                                                                                                
4/27/2018 3:54:13 PM  Restore-DbaDatabase         InternalComment              Starting                                                                                                       
4/27/2018 3:54:13 PM  Restore-DbaDatabase         Debug                        Parameters bound: SqlInstance, DatabaseName, ReuseSourceFolderStructure, NoRecovery, TrustDbBackupHistory, W...
4/27/2018 3:54:13 PM  Restore-DbaDatabase         Verbose                      Changing statement timeout to infinity                                                                         
4/27/2018 3:54:13 PM  Get-DbaDefaultPath          Verbose                      Attempting to connect to serverNew                                                                            
4/27/2018 3:54:13 PM  Restore-DbaDatabase         Warning                      No backups passed through. ...                                                                                 
4/27/2018 3:54:13 PM  Copy-DbaDatabase            Verbose                      Failed to restore DB to 
serverNew. Aborting routine for this database.                               
4/27/2018 3:54:13 PM  Copy-DbaDatabase            Verbose                      ...                                                                                                            
4/27/2018 3:54:13 PM  Copy-DbaDatabase            Verbose                      Migration started: 04/27/2018 15:53:57                                                                         
4/27/2018 3:54:13 PM  Copy-DbaDatabase            Verbose                      Migration completed: 04/27/2018 15:54:13                                                                       
4/27/2018 3:54:13 PM  Copy-DbaDatabase            Verbose                      Total Elapsed time: 00:00:16 
 - [ ] Attach output from PowerShell console (if possible/allowed)
WARNING: [Backup-DbaDatabase][15:54:13] Backup Failed:  Exception setting "LastRecoveryForkGuid": "Cannot convert value "" to type "System.Guid". Error: "Invalid cast from 'System.DBNull' to 
'System.Guid'.""
WARNING: [Restore-DbaDatabase][15:54:13] No backups passed through. 
 This could mean the SQL instance cannot see the referenced files, the file's headers could not be read or some other issue
### Problem to solve
<!Copy all databases not partial -->

**Comment by wsmelton** [comment] 2018-10-10 02:59
@dyard12 can you let is know if this issue still occurs on the latest release of the module?

I believe the conversion error has been fixed in a release since this issue was posted

**Comment by niphlod** [comment] 2018-10-24 19:16
@dyard12 : I'm going to close this as I cannot reproduce. Feel free to reopen if the issue is still there

**Closed** 2018-10-24 19:40 UTC
