### ISSUE TITLE
[Bug] - Copy-DbaAgentJob

### ISSUE THREAD

**Issue by talburo** [sqlcollaborative/dbatools#6413] opened 2020-03-11 17:46 UTC
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      4.0                                                                                     
WSManStackVersion              3.0                                                                                     
SerializationVersion           1.1.0.1                                                                                 
CLRVersion                     4.0.30319.42000                                                                         
BuildVersion                   6.3.9600.19170                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                    
PSRemotingProtocolVersion      2.2                                                                                     

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1
Version : 1.0.32

```

```powershell

LCID             Name             DisplayName                                                                          
----             ----             -----------                                                                          
1033             en-US            English (United States)                                                              

```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU3) (KB4458871) - 13.0.5216.0 (X64)   Sep 13 2018 22:16:01   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) 
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [x ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x ] Still buggy in powershell.exe

Setup as a SQL Agent Job.

#### Errors Received

No error 

#### Steps to Reproduce

powershell -Command "Get-DbaAgentJob -sqlinstance '<source_sql>' -EnableException | Where-Object {(($_.Name -notin 'WDBS Maint - Configure Standard Accounts', 'WDBS Maint - Create Build XML', 'WDBS Maint - DatabaseBackup - FULL', 'WDBS Maint - DatabaseBackup - LOG', 'WDBS Maint - DatabaseIntegrityCheck', 'WDBS Maint - Generate DR Report', 'WDBS Maint - DR Sync Server Objects', 'WDBS Maint - IndexOptimize', 'WDBS Maint - Update Statistics', 'WDBS Maint - Weekly Cleanup') -and $_.Name -notlike 'LSAlert*' -and $_.Name -notlike 'LSBackup*' -and $_.Name -notlike 'LSCopy*' -and $_.Name -notlike 'LSRestore*' -and $_.Name -notlike 'LiteSpeed Log Shipping*' -and $_.Name -ne 'syspolicy_purge_history' -and $_.Name -notlike 'SQL Sentry*' )} | Copy-DbaAgentJob -Destination '<destination_sql>' -DisableOnDestination -Force -EnableException"

#### Expected Behavior

Since I have -EnableException, I expect it to fail right away stating unable to copy job because it is dependent on a Proxy account.  

#### Actual Behavior

This was used in SQL Agent Job so I assume when the job was successful that all the jobs were copied successfully to destination server.  But that wasn't the case.  So I had to run the command manually in PowerShell console to see that it was skipping because of dependency of proxy account.

**Comment by wsuhoey** [comment] 2020-03-11 17:55
Please add a proper title.

You are on an old version of the dbatools module.
Please consider updating to the latest (1.0.101), using the script described at:
dbatools.io/cleanup
(This assumes you are not intentionally using the older version.)

Then try your command again.

**Comment by talburo** [comment] 2020-03-11 18:36
Sorry I am very new to this.  I am assuming I can’t run this script since I am not at least 1.0.62. 

Once I do update this, how do I make sure each of our servers are on the latest version?

**Comment by wsuhoey** [comment] 2020-03-11 18:48
Only 1.0.62+ is required to be able to run the one-liner `& "$((Get-InstalledModule dbatools).InstalledLocation)/cleanup.ps1"`.
You can still run the raw code provided in the `Script` section further below on the same page.

**Comment by talburo** [comment] 2020-03-11 19:10
I won't be able to use those commands cause we don't have PowerShell Gallery module on our servers.  I am using the offline method and manually the dbatools module on our server.  I have updated to the new version 1.0.101 and still get the same behavior.   Still skipping jobs because of dependency of proxy account.  Not sure what would cause -EnableException to occur when running this command.

**Comment by wsmelton** [comment] 2020-03-11 22:30
If you are using this in a SQL agent job you will need to review the job. 

We don't control whether the job well fail or not.

This is not a bug but deals with how you have the job configured and how you are calling the code. Provide that and we can help but I'm closing this until more is shown that it is an issue with the command itself.

**Closed by wsmelton** 2020-03-11 22:30 UTC
Labels: bugs_life

**Comment by wsuhoey** [comment] 2020-03-11 23:04
Try adding ```$ErrorActionPreference = 'Stop' # enables Agent Job to properly fail if PowerShell throws an error.``` at the top of your .ps1 script file that the Agent Job calls. I've had success with this method.

**Comment by talburo** [comment] 2020-03-12 12:55
There is no error that occurs, I am stating that I want it to throw an error if it wasn’t able to copy job over to destination server.  Instead of just providing a status that it skipped copying the job over to destination server because of a dependency.  I was hoping the –EnableException switch would throw an error if that occurs, but if that’s not the purpose of that switch then maybe I have to dump the output to a file then read the file to see if any jobs that were copied successfully to fail the job.

**Comment by wsmelton** [comment] 2020-03-12 13:15
Understood now and that is not the intention of the EnableException parameter. That parameter is used to throw error exceptions, not dependency exceptions.

**Comment by potatoqualitee** [comment] 2020-03-12 14:34
What you could do is test for status -match skipped then throw the error, but like Shawn said, this is working as designed. 

```
Get-DbaAgentJob -SqlInstance sql2016 | ForEach-Object { $copy = $PSitem | Copy-DbaAgentJob -Destination sql2017; if ($copy.Status -eq 'Skipped') { throw "ohno" } else { "awesome"} }
```
