### ISSUE TITLE
[Bug] Get-DbaAgReplica doesn't return accurate ComputerName property

### ISSUE THREAD

**Issue by danikuci1** [sqlcollaborative/dbatools#7267] opened 2021-04-27 18:56 UTC
#### Host used

- [x] powershell.exe
- [x] ISE
- [x] VS Code
- [ ] Other (please specify)

#### Errors Received

no error is generated

#### Steps to Reproduce

I've tested this on a few AG so I'm fairly confident it isn't an environment issue. 

Given an AG with two (or more) replicas, running `Get-DbaAgReplica -SqlInstance MyInstance` returns the appropriate number of objects. However, the `ComputerName` property of all these objects is the same.

#### Expected Behavior

I would expect `ComputerName` to be populated with the name of the computer, which is different for each node.

#### Actual Behavior

_here is an example output:_
```
ComputerName               : SERVERNAME1
InstanceName               : SQL_INST_01
SqlInstance                : SERVERNAME1\SQL_INST_01
AvailabilityGroup          : SHDB01-AG
Name                       : SERVERNAME1\SQL_INST_01
Role                       : Primary
ConnectionState            : Connected
RollupSynchronizationState : Synchronized
AvailabilityMode           : AsynchronousCommit
BackupPriority             : 50
EndpointUrl                : TCP://SERVERNAME1.DOMAIN.DOM:5022
SessionTimeout             : 10
FailoverMode               : Manual
ReadonlyRoutingList        : {}

ComputerName               : SERVERNAME1
InstanceName               : SQL_INST_01
SqlInstance                : SERVERNAME1\SQL_INST_01
AvailabilityGroup          : SHDB01-AG
Name                       : SERVERNAME2\SQL_INST_01
Role                       : Secondary
ConnectionState            : Connected
RollupSynchronizationState : Synchronizing
AvailabilityMode           : AsynchronousCommit
BackupPriority             : 50
EndpointUrl                : TCP://SERVERNAME2.DOMAIN.DOM:5022
SessionTimeout             : 10
FailoverMode               : Manual
ReadonlyRoutingList        : {}
```

As you can see it returns the info from two different servers with all the correct info, except the ComputerName is the same even though it isn't.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```
PowerShell Version        : 5.1.19041.906
dbatools latest installed : 1.0.145
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2012 (SP4-GDR) (KB4583465) - 11.0.7507.2 (X64)   Nov  1 2020 00:48:37   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
```

```sql
us_english
```

**Comment by wsmelton** [comment] 2021-05-01 21:44
This is because we auto-populate that property on all of our commands based on the parent instance of the SQL Server instance the code is executed against.

https://github.com/sqlcollaborative/dbatools/blob/7d0b20f844ee07482242aed483b36c91ca87fef6/functions/Get-DbaAgReplica.ps1#L92

The `ComputerName` property itself is not part of SMO and is a property that you could call proprietary to dbatools module. In essence this is a `by design` feature. I would not see any reason to modify this as it would break the pattern used in the module as a whole.

I believe an easy fix for this will be to simply have the `Replica` property moved into the defaults as it does not appear to be currently:

https://github.com/sqlcollaborative/dbatools/blob/7d0b20f844ee07482242aed483b36c91ca87fef6/functions/Get-DbaAgReplica.ps1#L89-L98

**Comment by andreasjordan** [comment] 2021-05-07 16:48
`Replica` is just the same as `Name` and is just a string.

But you can use the type `[DbaInstance]` to split `Name` and then use `ComputerName` from that type:
```
Get-DbaAgReplica -SqlInstance SRV1\SQL2017 | Select-Object -Property Name, Role, @{ name = 'ComputerName' ; expression = { ([DbaInstance]$_.Name).ComputerName } }
```

**Comment by andreasjordan** [comment] 2021-05-18 16:15
I will close this as "no bug" / "works as designed", but you can reopen it if you have further questions.

**Closed by andreasjordan** 2021-05-18 16:15 UTC
Labels: bugs_life
