### ISSUE TITLE
Install-DbaSqlWatch fails

### ISSUE THREAD

**Issue by devondba** [sqlcollaborative/dbatools#4725] opened 2018-11-30 15:17 UTC
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

There are two failures, with different reasons

```powershell
<#

Second Error:
Install-DbaSqlWatch -SqlInstance $SQLInstance -Database DBATools

Produces:

WARNING: [15:01:12][Publish-DbaDacPackage] Deployment failed | Could not deploy package.
Warning SQL72017: The unnamed foreign key between tables [dbo].[sql_perf_mon_snapshot_header] and
[dbo].[sql_perf_mon_config_snapshot_type] will be checked by checking the table.  Name the foreign key to avoid
checking the entire table and only check the new constraint.
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_verify_jobstep, Line 294 The
specified @database_name ('SQLWATCH') does not exist.
Error SQL72045: Script execution error.  The executed script:
IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_config_who_is_active_age]) = 0
    BEGIN
        INSERT INTO [dbo].[sql_perf_mon_config_who_is_active_age]
        SELECT 60;
    END

UPDATE swd
SET    [database_create_date] = db.[create_date]
FROM   [dbo].[sql_perf_mon_database] AS swd
       INNER JOIN
       sys.databases AS db
       ON db.[name] = swd.[database_name]
          AND swd.[database_create_date] = '1970-01-01';

EXECUTE [dbo].[sp_sql_perf_mon_add_database] ;

IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_server]) = 0
    BEGIN
        INSERT INTO dbo.sql_perf_mon_server
        SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')),
               CONVERT (sysname, @@SERVERNAME),
               CONVERT (sysname, @@SERVICENAME),
               CONVERT (VARCHAR (50), local_net_address),
               CONVERT (VARCHAR (50), local_tcp_port)
        FROM   sys.dm_exec_connections
        WHERE  session_id = @@spid;
    END

CREATE TABLE #sql_p


ComputerName : 
InstanceName : MSSQLSERVER
SqlInstance  : 
Database     : DBATools
Status       : (Failed)


Trying it with the default:

WARNING: [15:15:31][Publish-DbaDacPackage] Deployment failed | Could not deploy package.
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_add_jobserver, Line 88 The
specified @server_name ('WIN-D845KLQ97QE') does not exist.
Error SQL72045: Script execution error.  The executed script:
IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_config_who_is_active_age]) = 0
    BEGIN
        INSERT INTO [dbo].[sql_perf_mon_config_who_is_active_age]
        SELECT 60;
    END

UPDATE swd
SET    [database_create_date] = db.[create_date]
FROM   [dbo].[sql_perf_mon_database] AS swd
       INNER JOIN
       sys.databases AS db
       ON db.[name] = swd.[database_name]
          AND swd.[database_create_date] = '1970-01-01';

EXECUTE [dbo].[sp_sql_perf_mon_add_database] ;

IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_server]) = 0
    BEGIN
        INSERT INTO dbo.sql_perf_mon_server
        SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')),
               CONVERT (sysname, @@SERVERNAME),
               CONVERT (sysname, @@SERVICENAME),
               CONVERT (VARCHAR (50), local_net_address),
               CONVERT (VARCHAR (50), local_tcp_port)
        FROM   sys.dm_exec_connections
        WHERE  session_id = @@spid;
    END

CREATE TABLE #sql_p
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_add_jobserver, Line 88 The
specified @server_name ('WIN-D845KLQ97QE') does not exist.
Error SQL72045: Script execution error.  The executed script:
IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_config_who_is_active_age]) = 0
    BEGIN
        INSERT INTO [dbo].[sql_perf_mon_config_who_is_active_age]
        SELECT 60;
    END

UPDATE swd
SET    [database_create_date] = db.[create_date]
FROM   [dbo].[sql_perf_mon_database] AS swd
       INNER JOIN
       sys.databases AS db
       ON db.[name] = swd.[database_name]
          AND swd.[database_create_date] = '1970-01-01';

EXECUTE [dbo].[sp_sql_perf_mon_add_database] ;

IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_server]) = 0
    BEGIN
        INSERT INTO dbo.sql_perf_mon_server
        SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')),
               CONVERT (sysname, @@SERVERNAME),
               CONVERT (sysname, @@SERVICENAME),
               CONVERT (VARCHAR (50), local_net_address),
               CONVERT (VARCHAR (50), local_tcp_port)
        FROM   sys.dm_exec_connections
        WHERE  session_id = @@spid;
    END

CREATE TABLE #sql_p
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_add_jobserver, Line 88 The
specified @server_name ('WIN-D845KLQ97QE') does not exist.
Error SQL72045: Script execution error.  The executed script:
IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_config_who_is_active_age]) = 0
    BEGIN
        INSERT INTO [dbo].[sql_perf_mon_config_who_is_active_age]
        SELECT 60;
    END

UPDATE swd
SET    [database_create_date] = db.[create_date]
FROM   [dbo].[sql_perf_mon_database] AS swd
       INNER JOIN
       sys.databases AS db
       ON db.[name] = swd.[database_name]
          AND swd.[database_create_date] = '1970-01-01';

EXECUTE [dbo].[sp_sql_perf_mon_add_database] ;

IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_server]) = 0
    BEGIN
        INSERT INTO dbo.sql_perf_mon_server
        SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')),
               CONVERT (sysname, @@SERVERNAME),
               CONVERT (sysname, @@SERVICENAME),
               CONVERT (VARCHAR (50), local_net_address),
               CONVERT (VARCHAR (50), local_tcp_port)
        FROM   sys.dm_exec_connections
        WHERE  session_id = @@spid;
    END

CREATE TABLE #sql_p
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_add_jobserver, Line 88 The
specified @server_name ('WIN-D845KLQ97QE') does not exist.
Error SQL72045: Script execution error.  The executed script:
IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_config_who_is_active_age]) = 0
    BEGIN
        INSERT INTO [dbo].[sql_perf_mon_config_who_is_active_age]
        SELECT 60;
    END

UPDATE swd
SET    [database_create_date] = db.[create_date]
FROM   [dbo].[sql_perf_mon_database] AS swd
       INNER JOIN
       sys.databases AS db
       ON db.[name] = swd.[database_name]
          AND swd.[database_create_date] = '1970-01-01';

EXECUTE [dbo].[sp_sql_perf_mon_add_database] ;

IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_server]) = 0
    BEGIN
        INSERT INTO dbo.sql_perf_mon_server
        SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')),
               CONVERT (sysname, @@SERVERNAME),
               CONVERT (sysname, @@SERVICENAME),
               CONVERT (VARCHAR (50), local_net_address),
               CONVERT (VARCHAR (50), local_tcp_port)
        FROM   sys.dm_exec_connections
        WHERE  session_id = @@spid;
    END

CREATE TABLE #sql_p


InstanceName : MSSQLSERVER
Database     : SQLWATCH
Status       : (Failed)


This initially produced an error but after trying again it installed ok in it's own database, winner but most strange. I'm sure there's a simple answer.


As an addition, the uninstall command seems to fail too :(

PS C:\Users\me> unInstall-DbaSqlWatch -SqlInstance $SQLInstance
WARNING: [15:10:42][Uninstall-DbaSqlWatch] Failed to unpublish SqlWatch DACPAC from master on []. |
DacInstance with the specified instance_id does not exist.
PS C:\Users\me> unInstall-DbaSqlWatch -SqlInstance $SQLInstance -Database $DBDatabase
WARNING: [15:11:45][Uninstall-DbaSqlWatch] Failed to unpublish SqlWatch DACPAC from DBATools on []. |
DacInstance with the specified instance_id does not exist.

Although when I went to delete the stored procedures I was told they don't exist...so something may have happened afterall.

#>
```
## Environmental data

 - PowerShell: Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

 - - SQL Server: Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64)   Jun 17 2016 19:14:09   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by potatoqualitee** [comment] 2018-12-03 10:00
@marcingminski - can you take a look to see if this is on our side or with sqlwatch?

**Comment by marcingminski** [comment] 2018-12-03 10:37
First course of action I would suggest testing installation using SqlPackage.exe as in https://sqlwatch.io/docs/installation/ as this should highlight where the issue is. 
if the issue is with SQLWATCH please raise a bug in https://github.com/marcingminski/sqlwatch

The first error:
```
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_verify_jobstep, Line 294 The
specified @database_name ('SQLWATCH') does not exist.
```
Looks like it is expecting this to be in the SQLWATCH database. This used to be the case some time ago but fixed in the recent versions and now works with any database. This tells me this isn't the latest version?

The second error:
```
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_add_jobserver, Line 88 The
specified @server_name ('WIN-D845KLQ97QE') does not exist.
```
Suggests the installer is setting variable to hostname and not sql instance name? Are they same, not the same?

**Comment by devondba** [comment] 2018-12-03 11:53
Thanks @marcingminski , I'm afraid I can't find the installation .exe you mention, do you have a direct link to the file please?

To answer first question on second error, the installation was done via dbatools so it would depend which version that is using.

For the second question, SQL is installed as a default instance.

Please let me know how I can be of more help, thanks

Marytn

**Comment by marcingminski** [comment] 2018-12-03 12:06
SqlPackage.exe is shipped with SSMS (client tools) and it will be on your workstation if you have SSMS installed. Look in Program Files (x86)\Microsoft SQL Server\1xx\DAC

where the xx is version of SSMS installed. 

If you still cannot find it but have SSMS installed you can try deploying through SSMS GUI - Right click database, Deploy Data-Tier Application and load the SQLWATCH.dacpac 
https://sqlwatch.io/docs/installation/dacpac-deployment/dacpac-deployment-using-ssms/


Are you able to run Install-SqlWatch with -debug parameter, it should spit out bunch of lines, one of them will be URL it is downloading package from which should be the latest release:
https://github.com/marcingminski/sqlwatch/releases/download/SQLWATCH-v1.3.20/SQLWATCH_1.3.20.zip

**Comment by devondba** [comment] 2018-12-03 12:09
Ha ha, of course, sorry, I was thinking it was an installation file for the tool. I'll try that now and update you.

**Comment by devondba** [comment] 2018-12-03 12:16
Seems to indicate it's getting the latest:

DEBUG: 53453 | [12:15:06][Install-DbaSqlWatch] Checking GitHub for the latest release.
DEBUG: 53456 | [12:15:07][Install-DbaSqlWatch] Latest release is available at
https://github.com/marcingminski/sqlwatch/releases/download/SQLWATCH-v1.3.20/SQLWATCH_1.3.20.zip
DEBUG: 53463 | [12:15:07][Install-DbaSqlWatch] Downloading
https://github.com/marcingminski/sqlwatch/releases/download/SQLWATCH-v1.3.20/SQLWATCH_1.3.20.zip
DEBUG: 53473 | [12:15:16][Install-DbaSqlWatch] Copying C:\Users\me\AppData\Local\Temp\5\SqlWatch.zip to
C:\Users\me\AppData\Roaming\PowerShell\dbatools\SQLWATCH-v1.3.20\SQLWATCH_1.3.20.zip

**Comment by marcingminski** [comment] 2018-12-03 12:48
Great, can you please try installing dacpac using SqlPackage.exe or SSMS please so we can rule out dbatools?
I would like to ask you to do the following using SqlPackage.exe or SSMS:

1. install into your existing database DBATools
1. install into dedicated database SQLWATCH

(if you get collation error you may have to create SQLWATCH database manually and then run DACPAC to update it) https://sqlwatch.io/docs/known-issues-and-limitations/collation-conflict/

I am hoping to prove that:
1. the issue is with SQLWATCH and not dbatools
1. the issue is with installing SQLWATCH into another database and not into SQLWATCH database

**Comment by devondba** [comment] 2018-12-03 17:42
With a dac I can't install to the existing database, so tested with new db name, that went in fine. Using the default name also ran in fine.

Testing again using Install-DbaSqlWatch to default also ran in fine.

It's as if there is something about a new installation.

Uninstall doesn't seem to work, I wonder if it only works if installed via dacpac but that's what the function should do too I think:

PS C:\Users\mjadmin> Uninstall-DbaSqlWatch $Srv
WARNING: [17:37:13][Uninstall-DbaSqlWatch] Failed to unpublish SqlWatch DACPAC from master on [dbserver]. |
DacInstance with the specified instance_id does not exist.

That said the jobs were removed, just not the database.

**Comment by devondba** [comment] 2018-12-03 17:46
ok, after trying to uninstall it and reinstall it I get the same errors again:

Install-DbaSqlWatch $srv

...e ('WIN-D845KLQ97QE') does not exist.....

That is the old name of the server, I've updated SQL not to use that either. Again, when running that in a second time it works:

PS C:\Users\me> Install-DbaSqlWatch $srv

ComputerName : myserver
InstanceName : MSSQLSERVER
SqlInstance  : myinstance
Database     : SQLWATCH
Status       : (Complete)

**Comment by devondba** [comment] 2018-12-03 17:47
I'll not do anymore testing for now and wait to hear from you. As I can currently recreate the issue I'll leave things as they are so I can hopefully help.

**Closed** 2019-03-03 23:48 UTC
Labels: bugs_life, wontfix
