### ISSUE TITLE
[Bug] Connect-DbaInstance reports platform incorrectly when using a Linux Container

### ISSUE THREAD

**Issue by nocentino** [sqlcollaborative/dbatools#6038] opened 2019-09-12 15:05 UTC
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

#### dbatools Module version:

Name    : dbatools
Path    : /usr/local/share/powershell/Modules/dbatools/1.0.38/dbatools.psd1
Version : 1.0.38

Name    : dbatools
Path    : /usr/local/share/powershell/Modules/dbatools/0.9.477/dbatools.psd1
Version : 0.9.477

#### SQL Server: 
select @@VERSION

Microsoft SQL Server 2019 (RC1) - 15.0.1900.25 (X64) 	Aug 16 2019 14:20:53 	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS) <X64>

### Report

Connect-DbaInstance when targeting a  Linux container reports NT x64...see output below.

Connect-DbaInstance -SqlInstance $RestoreServer -SqlCredential $RestoreCredential
```
Name           Product              Version   Platform IsAzure IsClustered ConnectedAs
----           -------              -------   -------- ------- ----------- -----------
X.X.X.X Microsoft SQL Server 15.0.1900 NT x64   False   False       sa
```
#### Host used

- [ ] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

#### Expected Behavior

Expected to report the platform as Linux rather than NT

#### Actual Behavior

Reports NT x64 as the platform.

**Comment by wsmelton** [comment] 2019-09-13 16:28
Ah, has mistype in the code. Corrected and it returns information but is showing NT x64.

**Comment by wsmelton** [comment] 2019-09-13 16:40
```powershell
$loc = Get-InstalledModule -Name dbatools | select -first 1 -Property InstalledLocation
Add-Type -Path "$($loc.InstalledLocation)\bin\smo\coreclr\Microsoft.SqlServer.Smo.dll"
Add-Type -Path "$($loc.InstalledLocation)\bin\smo\coreclr\Microsoft.SqlServer.ConnectionInfo.dll"
Add-Type -Path "$($loc.InstalledLocation)\bin\smo\coreclr\Microsoft.SqlServer.Management.Sdk.Sfc.dll"
$servername = "localhost,1411"
$server = New-Object Microsoft.SqlServer.Management.Smo.Server $servername 
$message = "Enter the SQL Login credentials for the SQL Server" 
$server.ConnectionContext.LoginSecure = $false
$sqllogin = Get-Credential -Message $message 
$server.ConnectionContext.set_Login($sqllogin.username)
$server.ConnectionContext.set_SecurePassword($sqllogin.Password)
$server | select-object HostPlatform, Platform
```

Ok, so I think this is by design and not a bug. The platform of the machine I'm on and running Docker is NT x64.

**Comment by nocentino** [comment] 2019-09-13 18:18
When I run that code @wsmelton here's what I get:

```
HostPlatform Platform
------------   --------
Linux               NT x64
```

**Comment by wsmelton** [comment] 2019-09-13 19:13
Correct. The platform you are on is NT x64, because you are running on a Windows machine are you not? The host platform for SQL Server is Linux, but the platform you have Docker running is Windows.

I run that same code against a local instance on my Windows machine, the Platform shows `NT x64` and `HostPlatform` changes to Windows.

**Comment by nocentino** [comment] 2019-09-13 19:15
Nope, I'm on a Mac running Docker for Mac.

**Comment by wsmelton** [comment] 2019-09-13 19:19
You will need to upgrade to PowerShell 6.2.x and then install sqlserver module and run this to see if you get the same result:

```powershell
$loc = Get-InstalledModule -Name sqlserver | select -first 1 -Property InstalledLocation
Add-Type -Path "$($loc.InstalledLocation)\coreclr\Microsoft.SqlServer.Smo.dll"
Add-Type -Path "$($loc.InstalledLocation)\coreclr\Microsoft.SqlServer.ConnectionInfo.dll"
Add-Type -Path "$($loc.InstalledLocation)\coreclr\Microsoft.SqlServer.Management.Sdk.Sfc.dll"
$servername = "localhost,1411"
$server = New-Object Microsoft.SqlServer.Management.Smo.Server $servername 
$message = "Enter the SQL Login credentials for the SQL Server" 
$server.ConnectionContext.LoginSecure = $false
$sqllogin = Get-Credential -Message $message 
$server.ConnectionContext.set_Login($sqllogin.username)
$server.ConnectionContext.set_SecurePassword($sqllogin.Password)
$server | select-object HostPlatform, Platform
```

**Comment by nocentino** [comment] 2019-09-13 19:25
Still no dice...

```
PS /Users/aen> $loc = Get-InstalledModule -Name sqlserver | select -first 1 -Property InstalledLocation
PS /Users/aen> Add-Type -Path "$($loc.InstalledLocation)\coreclr\Microsoft.SqlServer.Smo.dll"
PS /Users/aen> Add-Type -Path "$($loc.InstalledLocation)\coreclr\Microsoft.SqlServer.ConnectionInfo.dll"
PS /Users/aen> Add-Type -Path "$($loc.InstalledLocation)\coreclr\Microsoft.SqlServer.Management.Sdk.Sfc.dll"
PS /Users/aen> $servername = "localhost,1433"
PS /Users/aen> $server = New-Object Microsoft.SqlServer.Management.Smo.Server $servername 
PS /Users/aen> $message = "Enter the SQL Login credentials for the SQL Server" 
PS /Users/aen> $server.ConnectionContext.LoginSecure = $false
PS /Users/aen> $sqllogin = Get-Credential -Message $message 

PowerShell credential request
Enter the SQL Login credentials for the SQL Server
User: sa
Password for user sa: ******************

PS /Users/aen> $server.ConnectionContext.set_Login($sqllogin.username)
PS /Users/aen> $server.ConnectionContext.set_SecurePassword($sqllogin.Password)
PS /Users/aen> $server | select-object HostPlatform, Platform

HostPlatform Platform
------------ --------
Linux        NT x64
```

**Comment by wsmelton** [comment] 2019-09-13 19:28
Bug to Microsoft submitted....

**Comment by nocentino** [comment] 2019-09-13 19:29
My work here is done :)

jk, thanks for sticking with it and working on this with me.

**Comment by potatoqualitee** [comment] 2019-09-14 15:40
yessssss thank you both. @wsmelton - you think they just forced the platform in `SqlServer` ?

**Comment by wsmelton** [comment] 2019-09-14 15:44
I think in ssms it is looking at hostplatform and they just level it as platform.

**Comment by wsmelton** [comment] 2020-01-08 17:02
Ticket was closed by MS as by design so we need to update our command(s) to use `HostPlatform` instead of `Platform`.

**Closed** 2020-01-10 09:42 UTC
