### ISSUE TITLE
Update-DbaInstance

### ISSUE THREAD

**Issue by Lwk874** [sqlcollaborative/dbatools#5332] opened 2019-04-02 20:07 UTC
The command is looking for the latest patch available in the build reference and not the latest in my patch repository.  I have 2016sp2 cu4 in my repository but the command looks to install 2016 sp2 cu5.  This is on version 0.9.800.  

Update-DbaInstance -ComputerName $s -Restart -Path \\SERVER\SQLPatches -Credential $cred -Confirm:$false

**Comment by potatoqualitee** [comment] 2019-04-02 20:08
Thank you for the report. Can you please paste the results of -Verbose? And then I'll ask the dev to take a look?

**Comment by Lwk874** [comment] 2019-04-03 21:56
Update-DbaInstance -ComputerName servername -Restart -Path \\SHARE\SQLPatches -verbose -Credential $cred


VERBOSE: [17:48:57][Resolve-DbaNetworkName] Resolving ServerName using .NET.Dns GetHostEntry
VERBOSE: [17:48:57][Resolve-DbaNetworkName] Resolving IP using .NET.Dns GetHostByAddress
VERBOSE: [17:48:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [17:48:57][Get-DbaCmObject] [ServerName] Retrieving Management Information
VERBOSE: [17:48:57][Get-DbaCmObject] [ServerName] Accessing computer using Cim over WinRM
VERBOSE: [17:48:57][Get-DbaCmObject] [ServerName] Accessing computer using Cim over WinRM - Success
VERBOSE: [17:48:57][Resolve-DbaNetworkName] Resolving ServerName using .NET.Dns GetHostEntry
VERBOSE: [17:48:57][Resolve-DbaBuild] Looking for 13.0.5233
VERBOSE: [17:48:57][Resolve-DbaBuild] We have 64 builds in store for this Release
VERBOSE: [17:48:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [17:48:57][Get-DbaCmObject] [ServerName] Retrieving Management Information
VERBOSE: [17:48:57][Get-DbaCmObject] [ServerName] Accessing computer using Cim over WinRM
VERBOSE: [17:48:57][Get-DbaCmObject] [ServerName] Accessing computer using Cim over WinRM - Success
VERBOSE: [17:48:57][Update-DbaInstance] Attempting to configure CredSSP for remote connections
VERBOSE: [17:48:57][Initialize-CredSSP] Configuring remote host to use CredSSP
VERBOSE: [17:48:58][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [17:48:58][Get-DbaCmObject] [ServerName] Retrieving Management Information
VERBOSE: [17:48:58][Get-DbaCmObject] [ServerName] Accessing computer using Cim over WinRM
VERBOSE: [17:48:58][Get-DbaCmObject] [ServerName] Accessing computer using Cim over WinRM - Success
VERBOSE: [17:48:58][Resolve-DbaBuild] Looking for 13.0.5233
VERBOSE: [17:48:58][Resolve-DbaBuild] We have 64 builds in store for this Release
VERBOSE: [17:48:59][Resolve-DbaBuild] Looking for 13.0.5292
VERBOSE: [17:48:59][Resolve-DbaBuild] We have 64 builds in store for this Release
VERBOSE: [17:48:59][Resolve-DbaBuild] Looking for SQL 2016 SP SP2 CU 
VERBOSE: [17:48:59][Resolve-DbaBuild] We have 64 builds in store for this Release
VERBOSE: [17:48:59][Get-SqlServerUpdate] No need to update SQL2016 to SP2 - it's already on the latest SP version
VERBOSE: [17:48:59][Update-DbaInstance] Attempting to configure CredSSP for remote connections
VERBOSE: [17:48:59][Initialize-CredSSP] Configuring remote host to use CredSSP
VERBOSE: [17:49:00][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [17:49:00][Get-DbaCmObject] [ServerName] Retrieving Management Information
VERBOSE: [17:49:00][Get-DbaCmObject] [ServerName] Accessing computer using Cim over WinRM
VERBOSE: [17:49:00][Get-DbaCmObject] [ServerName] Accessing computer using Cim over WinRM - Success
VERBOSE: [17:49:00][Resolve-DbaBuild] Looking for 13.0.5233
VERBOSE: [17:49:00][Resolve-DbaBuild] We have 64 builds in store for this Release
VERBOSE: [17:49:01][Resolve-DbaBuild] Looking for 13.0.5292
VERBOSE: [17:49:01][Resolve-DbaBuild] We have 64 builds in store for this Release
VERBOSE: [17:49:01][Get-SqlServerUpdate] Found applicable upgrade for SQL2016 to SP2CU6 (KB4488536)
VERBOSE: [17:49:01][Find-SqlServerUpdate] Using filter [SQLServer2016*-KB4488536-*x64*.exe] to check for updates in \\east-sql-tools\SQLPatches
WARNING: [17:49:01][Update-DbaInstance] Could not find installer for the SQL2016 update KB4488536

**Comment by nvarscar** [comment] 2019-04-10 13:50
This is by design, the command never scans your repository for available versions, it simply checks if the chosen version is present. If you want to install a specific version, you can explicitly specify that in parameters.

**Comment by potatoqualitee** [comment] 2019-04-25 20:50
thanks for your feedback, @nvarscar. marking this as resolved

**Closed by potatoqualitee** 2019-04-25 20:50 UTC

**Comment by Lwk874** [comment] 2019-05-17 16:14
Example 3 in the documentation reads like that is the functionality.  Thanks you for clarifying.
