### ISSUE TITLE
Get-DbaDatabaseFile returning wrong 'Growth'

### ISSUE THREAD

**Issue by OxyMethylene** [sqlcollaborative/dbatools#2471] opened 2017-10-19 12:33 UTC
Hello,

Using the command 'Get-DbaDatabaseFile' doesn't return the correct 'Growth'. Screenshots below.

### General Troubleshooting steps
- [x ] Verified running latest release of dbatools?
- [x ] Verified errors are not related to permissions?
- [x ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)

### Additional information
![sql_growth_1](https://user-images.githubusercontent.com/13507100/31770937-65629a8e-b4da-11e7-9cf1-3753e04e9271.png)

![sql_growth_2](https://user-images.githubusercontent.com/13507100/31770818-d7eb6438-b4d9-11e7-9b17-372534147468.png)

**Comment by ClaudioESSilva** [comment] 2017-10-19 13:40
Hi @OxyMethylene,
This is not a bug, the GUI show the value in a different unit.

The SMO report the size as number of 8-KB pages. Is the same way that `sys.master_files` shows.

From documentation (source: https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-master-files-transact-sql):

> If is_percent_growth = 0, growth increment is in units of 8-KB pages, rounded to the nearest 64 KB

This means that you have to multiply by 8 that value and dived by 1024 to get the amount of MB.

Regarding your example:
16384 * 8 / 1024 = 128MB

**Comment by niphlod** [comment] 2017-10-19 13:55
yep, extraction is correct there but since there is a "nice" `GrowthType` (percent/kb), maybe we can just make a smart move on `Growth` too to show the actual kb size when `GrowthType -eq 'kb'`  ??? ! ???

**Comment by OxyMethylene** [comment] 2017-10-20 07:10
Hi @ClaudioESSilva 

Thanks for the explination, it was indeed just a bit confusing on my part.

@niphlod 
Could be a nice addition to the command. However, it's just a nice to have.

Thanks both

**Comment by josh-simar** [comment] 2017-10-25 21:54
I'd like to take this one on. I think I have an approach that should satisfy the need. Just don't know how to assign myself to the issue.

**Comment by dbaduck** [comment] 2018-01-22 23:31
This is not fixed, it still shows the number of 8 KB in build 0.9.182.  In the query  it just shows df.Growth instead of df.Growth / 8 (if it is not percent). I have a code fix ready but wanted to ensure that it was desired to fix it.

**Comment by niphlod** [comment] 2018-02-26 22:23
fixed via https://github.com/sqlcollaborative/dbatools/pull/3168

**Closed by niphlod** 2018-02-26 22:23 UTC
