### ISSUE TITLE
Issue with Update-DbaInstance

### ISSUE THREAD

**Issue by ml222** [sqlcollaborative/dbatools#7198] opened 2021-03-17 12:09 UTC
#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Connecting to remote server <-ComputerName->failed with the following error message : WinRM cannot process the request. The following error occurred while using Kerberos authentication: Cannot find the com
                        puter <-ComputerName->. Verify that the computer exists on the network and that the name provided is spelled correctly. For more information, see the about_Remote_Troubleshooting Help topic. ---> System.Management.Automation
                        .Remoting.PSRemotingTransportException: Connecting to remote server <-ComputerName-> failed with the following error message : WinRM cannot process the request. The following error occurred while using Kerberos authenticatio
                        n: Cannot find the computer <-ComputerName->. Verify that the computer exists on the network and that the name provided is spelled correctly. For more information, see the about_Remote_Troubleshooting Help topic.
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : OpenError: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Update-DbaInstance,Stop-Function
ErrorDetails          : Connecting to remote server <-ComputerName-> failed with the following error message : WinRM cannot process the request. The following error occurred while using Kerberos authentication: Cannot find the computer <-ComputerName->. Verify that the computer exists on the network and that the name provided is spelled correctly. For more information, see the about_Remote_Troubleshooting Help topic.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, \\server\share\Powershell\Modules\dbatools\Version 1.0.141\dbatools-master\allcommands.ps1: line 87504
                        at Update-DbaInstance<Process>, \\server\share\Powershell\Modules\dbatools\Version 1.0.141\dbatools-master\allcommands.ps1: line 77853
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

Since the server specified as target when running Update-DbaInstance is using a service account with a registered HTTP SPN causing WinRM issues, to get things to work this command is issued:

`Set-DbaToolsConfig -Name 'psremoting.pssessionoption.includeportinspn' -Value $True`

before running

`Update-DbaInstance -ComputerName $ServerNames -Version $Version -Path $SQLUpdatePath -Restart -Confirm:$false -Credential $UserCredential -Authentication Kerberos`

When the dbatools version 1.0.137 module is imported this works just fine. But not in version 1.0.141.

UPDATE: Actually I'm also unable to run Update-DbaInstance specifying a server that does NOT have a service account with HTTP SPNs. This error is returned:

> WARNING: [15:42:32][Update-DbaInstance] Failed to enumerate files in -Path | Cannot bind argument to parameter 'Session' because it is null.

#### Expected Behavior

Running Update-DbaInstance without issues like in version 1.0.137, using the same command(s).

#### Actual Behavior

>WARNING: [12:59:40][Update-DbaInstance] Explicit -Credential might be required when running agains remote hosts and -Path is a network folder
WARNING: [12:59:40][Update-DbaInstance] Error while looking for SQL Server installations on <--ComputerName--> | Connecting to remote server <--ComputerName--> failed with the following error message : WinRM cannot process the request. The following error occurred while using Kerberos authentication: Cannot find the computer <--ComputerName-->. Verify that the computer exists on the network and that the name provided is spelled correctly. For more information, see the about_Remote_Troubleshooting Help topic.

### Environmental information

```
PowerShell Version        : 4.0
dbatools latest installed : 
Culture of OS             : sv-SE
```

**Comment by andreasjordan** [comment] 2021-05-18 16:43
@nvarscar : Have you had a look at this?

**Comment by nvarscar** [comment] 2021-05-18 21:06
No, but I'm looking into it now, thanks for the pageout.

**Comment by nvarscar** [comment] 2021-05-18 21:16
The most fitting source of an issue (timeline-wise) is https://github.com/sqlcollaborative/dbatools/commit/5c6f66d821c38fd228a18e57c69a8230ec4e8ad4 which changed the way the sessions are stored. This commit had an undiscovered (at the time issue), that was later fixed in https://github.com/sqlcollaborative/dbatools/pull/7247 . I'm wondering if it's related.
Can you confirm that the issue is still happening on the most recent version (1.0.148, for instance)?

**Comment by andreasjordan** [comment] 2021-07-02 09:47
@ml222 Can you please test with the latest version?

**Comment by potatoqualitee** [comment] 2021-07-28 08:29
@ml222 we've changed a bit in remoting since your issue. if you continue to have issues, please let us know and we'll reopen this issue.

**Closed by potatoqualitee** 2021-07-28 08:29 UTC
Labels: bugs life, waiting for user
