### ISSUE TITLE
Error while insatlling online method of DBAtools

### ISSUE THREAD

**Issue by Prabhadevi06** [sqlcollaborative/dbatools#6751] opened 2020-08-20 20:52 UTC
We followed below steps to install DBAtools via online method .and got the below errors .Firewall is open on the servers to download the module.

1.[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
2.[Net.ServicePointManager]::SecurityProtocol
3.Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
4.Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

PS C:\Users\xxxx> Install-Module dbatools

 

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet
 provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or
'C:\Users\xxxxx\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by
running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install
and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Install-PackageProvider : No match was found for the specified search criteria for the provider
'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package
has the tags.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21
+ ...     $null = PackageManagement\Install-PackageProvider -Name $script:N ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-Pac
   kageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackagePro
   vider

 

PackageManagement\Import-PackageProvider : No match was found for the specified search criteria and provider name
'NuGet'. Try 'Get-PackageProvider -ListAvailable' to see if the provider exists on the system.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7411 char:21
+ ...     $null = PackageManagement\Import-PackageProvider -Name $script:Nu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (NuGet:String) [Import-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.ImportPackageProv
   ider

 

WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Get-PackageProvider : Unable to find package provider 'NuGet'. It may not be imported yet. Try
'Get-PackageProvider -ListAvailable'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7415 char:30
+ ... tProvider = PackageManagement\Get-PackageProvider -Name $script:NuGet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...PackageProvider:GetPackageProvider) [Get-PackageProvi
   der], Exception
    + FullyQualifiedErrorId : UnknownProviderFromActivatedList,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPacka
   geProvider

 

Install-Module : NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201'
or newer version of NuGet provider is installed.
At line:1 char:1
+ Install-Module dbatools
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Module], InvalidOperationException
    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Install-Module

**Comment by wsmelton** [comment] 2020-08-20 21:47
The error is around the package manager on the machine, not with our module.

I'm not aware of why the registry changes you show done were needed. I would recommend restoring those to their original value.

You should only need item 1 in your list and then run install command. 

If you continue to get error I would install the latest release of PowerShellGet module on that machine. Then see if it will install modules from the PowerShell Gallery.

**Comment by andreasjordan** [comment] 2020-08-21 06:24
Based on my experience, the reason for `WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.` are uncorrect TLS settings, as microsoft,com only accepts strong encryption.

To test the TLS settings you can use this command:
```
Invoke-WebRequest -Uri 'https://go.microsoft.com/'
```

The result should start with:
```
StatusCode        : 200
StatusDescription : OK
Content           : 
                    
                    
                    <!DOCTYPE html>
                    <html lang="de-de" dir="ltr">
                    <head data-info="{&quot;v&quot;:&quot;1.0.7524.34520&quot;,&quot;a&quot;:&quot;df7c6cdd-c0f4-4121-afbb-676c4262e6ea&quot;,&quot;cn&quot;:&quot;One...
RawContent        : HTTP/1.1 200 OK
                    Pragma: no-cache
                    X-Activity-Id: df7c6cdd-c0f4-4121-afbb-676c4262e6ea
                    MS-CV: AgxmfTG3B0uOjpjm.0
                    X-AppVersion: 1.0.7524.34520
                    X-Az: {did:92e7dc58ca2143cfb2c818b047cc5cd1, rid: OneDe...
```

If this works, then this should work to set up Nuget and PSGallery:

```
Install-PackageProvider -Name Nuget -Force | Out-Null
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
```

**Comment by wsmelton** [comment] 2020-08-24 22:09
Closing the issue.

@Prabhadevi06 if you continue to have issues we can try and help the best we can but the issue is local to that machine.

**Closed by wsmelton** 2020-08-24 22:09 UTC
