### ISSUE TITLE
Set-DbaPowerPlan doesn't accept pipeline input from Test-DbaPowerPlan

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#5895] opened 2019-07-14 19:00 UTC
#### Powershell version:
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
#### dbatools module version:

```
gmo dbatools -List | select name, path, version | fl -force | Out-String


Name    : dbatools
Path    : C:\Users\andy\Documents\WindowsPowerShell\Modules\dbatools\1.0.21\dbatools.psd1
Version : 1.0.21

Name    : dbatools
Path    : C:\Users\andy\Documents\WindowsPowerShell\Modules\dbatools\1.0.20\dbatools.psd1
Version : 1.0.20
```
#### SQL Server: 
```
Microsoft SQL Server 2016 (SP2-GDR) (KB4505220) - 13.0.5101.9 (X64)   Jun 15 2019 23:15:58   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 
```
### Report
When attempting to use `Test-DbaPowerPlan | Set-DbaPowerPlan` in a manner similar to `Test-DbaMaxMemory | Set-DbaMaxMemory', an error is produced and the expected action does not happen

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)
#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: Method invocation failed because 
                        [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
                           at System.Management.Automation.ParserOps.CallMethod(IScriptExtent errorPosition, Object 
                        target, String methodName, PSMethodInvocationConstraints invocationConstraints, Object[] 
                        paramArray, Boolean callStatic, Object valueToSet)
                           at System.Management.Automation.ParserOps.ImplicitOp(Object lval, Object rval, String op, 
                        IScriptExtent errorPosition, String errorOp)
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 
                        arg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
TargetObject          : op_Addition
CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
FullyQualifiedErrorId : MethodNotFound
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Set-DbaPowerPlan<Process>, 
                        C:\Users\andy\Documents\WindowsPowerShell\Modules\dbatools\1.0.21\allcommands.ps1: line 62695
                        at Select-DefaultView<Process>, 
                        C:\Users\andy\Documents\WindowsPowerShell\Modules\dbatools\1.0.21\allcommands.ps1: line 77775
                        at Test-DbaPowerPlan<Process>, 
                        C:\Users\andy\Documents\WindowsPowerShell\Modules\dbatools\1.0.21\allcommands.ps1: line 69542
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce

`Test-DbaPowerPlan -ComputerName localhost | Set-DbaPowerPlan -ComputerName localhost`

#### Expected Behavior

* No error message
* Power Plan set to `RecommendedPowerPlan` from `Test-DbaPowerPlan`

#### Actual Behavior

```
Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'
At C:\Users\andy\Documents\WindowsPowerShell\Modules\dbatools\1.0.21\allcommands.ps1:62695 char:13
+             $InputObject += Get-DbaPowerPlan -ComputerName $ComputerN ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

**Comment by sirsql** [comment] 2019-08-01 00:07
You are already piping in the computer from Test-DbaPowerPlan into Set-DbaPowerPlan so there is no need to add the -ComputerName parameter.

Try:
`Test-DbaPowerPlan -ComputerName localhost | Set-DbaPowerPlan`
Alternatively you could call 
`Set-DbaPowerPlan -ComputerName localhost`
This would change the plan if it needed changing to High Performance, otherwise it would null op.

**Comment by andreasjordan** [comment] 2020-09-05 14:41
@potatoqualitee Why does this issue have a feature lable?

**Comment by wsmelton** [comment] 2020-09-05 16:37
Beacause it's a feature and not a bug on something that already exists.

**Comment by andreasjordan** [comment] 2020-09-05 16:40
> Beacause it's a feature and not a bug on something that already exists.

I just don't see the requested feature. But that's ok, I don't have to...

**Comment by andreasjordan** [comment] 2021-07-11 10:25
With that latest version, it does now - so I will close this.
We don't have an example for that, because Set-DbaPowerPlan in running Test-DbaPowerPlan itself to get all the information needed - so this is not the recommanded usage.

**Closed by andreasjordan** 2021-07-11 10:25 UTC
Labels: feature, waiting for team
