### ISSUE TITLE
Awesome Availability Groups Commands

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1712] opened 2017-07-17 16:06 UTC
### Problem to solve
Building set of commands around building and managing an Availability Group.

### Additional information
Let's make a list of ideas and corresponding command names

We can focus on both building blocks _and_ whole solutions.

The following complete solutions have been proposed:

- [ ] Finding the date of the most recent backup across all replicas of an AG database
- [ ] Restore a backups (with logs, etc) to all nodes; Add a restored DB to the AG
- [ ] Adding an existing DB to an AG, using existing backups

**Comment by wsmelton** [comment] 2017-07-18 21:03
Prerequisite to this will be the ability to do partial restores with the `Restore-DbaDatabase`. I would need the ability to start a restore without having to anchor with full backup first.

@Stuart-Moore

**Comment by wsmelton** [comment] 2017-07-24 06:31
@potatoqualitee @DevOpsFu (and @PowerDBAKlaas to make sure naming convention makes sense) 

Just putting this post as one we can edit to build out the list of commands we actually need

Commands:
- [x] Get-DbaAgReplica
- [x] Get-DbaAgDatabase
- [ ] Get-DbaAgListener
- [ ] Get-DbaAgReplicaState (based on SMO object to get latency info)
- [ ] Get-DbaAgHealth (based on XE session)
- [ ] Test-DbaAgHealth (seen use cases where based on how the AG was built the XE session does not get turned on)
- [ ] Set-DbaAgHadr (enable hadr for a given instance, initial step to building an AG is it has to be enabled for the instance; could have switch for -ExcludeRestart to say don't restart the instance but default it will enable it and then restart it to apply)
- [ ] Set-DbaAgPrimary (proposed in issue #1432 which has "server" in the name but thinking we don't need to include that?)
- [ ] New-DbaEndpoint (generic but required to build an AG; will also need to ensure the output of this command flows well for the AG build process)
- [ ] New-DbaAgGroup
- [ ] New-DbaAgListener (need to determine best process for this, scenarios like Azure IaaS you don't follow the same process as you would on-premise or in AWS)

**Comment by PowerDBAKlaas** [comment] 2017-07-24 09:41
Looks like a fine collection, @wsmelton 
Only the `New-DbaAgDatabase`, does it create a DB, or is it more an `Add-` or `Join-`?

**Comment by potatoqualitee** [comment] 2017-07-24 09:42
i do like join or add!

**Comment by wsmelton** [comment] 2017-07-24 15:58
I would be both, you have to add the database to the replica and then join it to the AG. You would join on each replica. So that name could go either way @potatoqualitee

**Comment by wsmelton** [comment] 2017-07-24 16:02
Although SSMS you see it as "Add" so maybe we need to go with `Add-DbaAgDatabase` ?

![image](https://user-images.githubusercontent.com/11204251/28532486-8881ff1a-705f-11e7-8b56-bd480ccdcd29.png)

**Comment by potatoqualitee** [comment] 2017-07-24 16:04
Interrrrresting! I've wondered how to standardize this. Even methods can be different. For instance, Add-DbaComputerCertificate requires .Import() but that conveys something different. 

I did see New Database... should we go with SSMS naming for our own namings? I like Add here for reasons listed above.

**Comment by wsmelton** [comment] 2017-07-24 16:09
You can get an idea of how AG is built with SMO [here](https://blogs.technet.microsoft.com/heyscriptingguy/2013/04/29/set-up-an-alwayson-availability-group-with-powershell/).

I have a cleaned up version of this where I had tried...oddly enough I found a way to generate an error in AGs that is not documented :)

**Comment by Stuart-Moore** [comment] 2017-07-24 16:41
Sorry @wsmelton , didn't see this till now :(

Do you mean you need to restore more files on top of a db in norecovery? That went in a couple of months ago. If you set -continue it looks at the last lsn restored on a db and then carries on from there ignoring fulls.

**Comment by wsmelton** [comment] 2017-07-24 16:57
Yeah, just caught that over the weekend. This would be restore the initial full and likely another log, then try to join the database to the AG. The database at that point is in restoring mode. If it does not join, meaning it comes back with not enough LSN we would need to restore another log backup to it.

If that is covered we are good to proceed .

**Comment by Stuart-Moore** [comment] 2017-07-25 06:25
Yep, it was designed to do that. I've some dbs with such a transaction log churn it can take me a half a day to get them synced up so wanted a fire and forget solution that would pick back up when I got dragged into a meeting and missed the AG create window

Restore the bulk normally:
Get-DBaBackupHistory -SqlInstance SourceInstance -Database Db1 -Last | Restore-DbaDatabase -SqlInstance TargetInstance -DatabaseName Db1 -NoRecovery -TrustDbBackupHistory
Then, keep running this to restore more logs:
Get-DBaBackupHistory -SqlInstance SourceInstance -Database Db1 -Last  | Restore-DbaDatabase -SqlInstance TargetInstance -DatabaseName Db1 -NoRecovery -Continue -TrustDbBackupHistory

Works fine with files being piped in as well, just has the header scan overhead.

Reminds me, I've a video script written. must record that at some point.

**Comment by wsmelton** [comment] 2018-07-16 02:07
I'm working on building out a project on GitHub. I'm going to create issues for the remaining commands so I can keep up with it all better and add them to a card on the project.

**Comment by wsmelton** [comment] 2018-07-16 02:11
Project created for tracking issues on new commands: https://github.com/sqlcollaborative/dbatools/projects/7

Going to close this one out for right now.

**Closed by wsmelton** 2018-07-16 02:11 UTC
Labels: Status: In Progress, Topic: Availability Groups, Type: Enhancement, Type: New Command, awesome_sauce
