### ISSUE TITLE
Invoke-DbaQuery ignores -queryTimeout parameter and hangs indefinitely

### ISSUE THREAD

**Issue by dgates82** [sqlcollaborative/dbatools#7227] opened 2021-04-02 18:07 UTC
#### Host used

- [x ] powershell.exe
- [x ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

None - Powershell script hangs instead of timing out the query as expected

#### Steps to Reproduce
```
$path = "c:\temp\test.sql"
$server = "localhost"
Invoke-DbaQuery -query "select * from CONSTITUENT" -SqlInstance $server -Database Shelby -QueryTimeout 15
```

#### Expected Behavior
The query to timeout after 15 seconds and return an error

#### Actual Behavior
The query continued to run until manually canceled (after 2 hours), at which point Powershell hung

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

PowerShell Version        : 5.1.14409.1018
dbatools latest installed : 1.0.133
Culture of OS             : en-US

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-GDR) (KB4583460) - 13.0.5103.6 (X64) 
	Nov  1 2020 00:13:28 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor)

```

```sql
us_english
```

**Comment by lancasteradam** [comment] 2021-04-10 21:43
@dgates82, I debugged the code and it appears to be working as expected. 

How much data is returned from your query? 

In the second note of the [remarks section](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtimeout#remarks) of the CommandTimeout property it mentions that the timeout is reset for each read call.

This sample code helps to illustrate what the documentation describes:

```
# Scenario 1: Query takes less than a second to return, but takes more than 1 second to transfer the data to the client. The timeout is not enforced because none of the network read calls have exceeded the timeout.
Measure-Command { $result = Invoke-DbaQuery -Query "select top 1000000 * from test;" -SqlInstance localhost -Database TestDB -QueryTimeout 1 }
"Row count returned is $($result.Count)`n"

# Scenario 2: Query takes longer than 1 second to return and so the QueryTimeout is enforced.
Measure-Command { $result = Invoke-DbaQuery -Query "select top 1000000 * from test; WAITFOR DELAY '00:00:02';" -SqlInstance localhost -Database TestDB -QueryTimeout 1 }
"Row count returned is $($result.Count)"
```

![dbatools 7227](https://user-images.githubusercontent.com/68036988/114285054-f8d42280-9a08-11eb-846d-719566184c4a.png)

It seems possible that when your command is run it starts to return data to the client before the timeout is exceeded. It then continues to do subsequent read calls to get all of the data and none of those read calls exceed the timeout. If a very large amount of data was being returned then it could explain why it got stuck on the client side, possibly due to memory issues.

**Comment by andreasjordan** [comment] 2021-05-18 16:39
I will close this as "no bug" / "works as designed", but you can reopen it if you have further questions.

**Closed by andreasjordan** 2021-05-18 16:39 UTC
Labels: bugs_life
