### ISSUE TITLE
[Bug] Regression detected fro SQL 2000

### ISSUE THREAD

**Issue by habibhammy** [sqlcollaborative/dbatools#6465] opened 2020-04-08 15:07 UTC
### Environmental information
```
#### PowerShell version:

Name                           Value                                                                                                                                                                             
----                           -----                                                                                                                                                                             
PSVersion                      5.1.14393.3471                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                           
BuildVersion                   10.0.14393.3471                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                               
SerializationVersion           1.1.0.1                                                                                                                                                                           


#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\dbatools.psd1
Version : 1.0.104

```

#### SQL Server:

```sql
Microsoft SQL Server  2000 - 8.00.2305 (Intel X86)   May 14 2012 16:24:50   Copyright (c) 1988-2003 Microsoft Corporation  Standard Edition on Windows NT 5.2 (Build 3790: Service Pack 2) 
```

```sql
us_english
```

### Report

Some commands of the DBATOOLS module are not working anymore with the SQL 2000 version.

It used to be working in the 1.0.84 version. We did an update of the module to the version 1.0.101 & to the latest version 1.0.104 and since then the script we use are not working any more with the SQL 2000 servers.

#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "ExecuteWithResults" with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or 
                        batch." ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> 
                        System.Data.SqlClient.SqlException: Cannot assign a default value to a local variable.
                        Must declare the variable '@depth'.
                        Incorrect syntax near the keyword 'WITH'.
                        Line 32: Incorrect syntax near 'MAX'.
                        Line 44: Incorrect syntax near ')'.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo 
                        memberInfo)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ExecutionFailureException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaFile<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\allcommands.ps1: line 27540
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

I'm getting the issue with the GET-DBADBFILE: 
```
$r = Get-DbaDbFile -SqlInstance SQLServer2000
```

#### Expected Behavior

Normaly we expected a result like the below : 
```
PS > $r = Get-DbadbFile -SqlInstance SQLServer2017

PS > $r
ComputerName             : SQLServer2017
InstanceName             : MSSQLSERVER
SqlInstance              : SQLServer2017
Database                 : master
FileGroupName            : PRIMARY
ID                       : 1
Type                     : 0
TypeDescription          : ROWS
LogicalName              : master
PhysicalName             : FakePath\master.mdf
State                    : ONLINE
MaxSize                  : Unlimited
Growth                   : 131072
GrowthType               : kb
NextGrowthEventSize      : 128.00 MB
Size                     : 4.44 MB
UsedSpace                : 4.31 MB
AvailableSpace           : 128.00 KB
IsOffline                : False
IsReadOnly               : False
IsReadOnlyMedia          : False
IsSparse                 : False
NumberOfDiskWrites       : 2535
NumberOfDiskReads        : 68
ReadFromDisk             : 8.30 MB
WrittenToDisk            : 20.79 MB
VolumeFreeSpace          : 8.41 GB
FileGroupDataSpaceId     : 1
FileGroupType            : FG
FileGroupTypeDescription : ROWS_FILEGROUP
FileGroupDefault         : True
FileGroupReadOnly        : False

```

#### Actual Behavior

```
PS > Get-DbaFile -SqlInstance SQLServer2000
Exception calling "ExecuteWithResults" with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or batch."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\allcommands.ps1:27540 char:13
+             $datatable = $server.ConnectionContext.ExecuteWithResults ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ExecutionFailureException
 
```

**Comment by wsmelton** [comment] 2020-04-08 17:02
This is not considered a bug. As time goes on and we update SMO to be compatibility with newer versions of SQL Server, the older versions are going to be left behind.

We have not directly updated commands that are not working against SQL Server 2000 because it is to much to maintain being that we cannot create 2k instance in our test environments.

**Comment by wsmelton** [comment] 2020-04-08 17:03
The error you are seeing is likely due to an update we did for SMO a few months back. I can almost guarantee once we update to the latest release (16.0) that came out with SSMS 18.5 you will find many more commands stop working against SQL Server 2000.

Closing as by design.

**Closed by wsmelton** 2020-04-08 17:03 UTC
Labels: bugs_life

**Comment by wsmelton** [comment] 2020-04-08 17:05
If you want to continue using the dbatools module against SQL Server 2000 going forward you will need to not update the module, or keep an older version around.

I believe version `1.0.98` contains the updated version of SMO, so using version `1.0.97` or lower should still work fine with 2k.

**Comment by habibhammy** [comment] 2020-04-08 18:33
Many Thanks for the clarifications. Indeed we will continue working with the version 1.0.84 that we are sure about till we complete the migration of the servers.
Best Regards.
