### ISSUE TITLE
keeping availability group logins in sync automatically

### ISSUE THREAD

**Issue by EbenRaja** [sqlcollaborative/dbatools#6958] opened 2020-11-05 13:12 UTC
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools
For some reason the code fails to pick SQL ID (SQL authenticated Id) and transfer it to secondary replicas , however windows ID is getting transferred, also if i feed the AG IP on $AvailabilityGroupName and it fails for my SQL agent service account. 
When i change the $AvailabilityGroupName to name instead of IP the windows ID gets trasnferred but SQL ID doesnt. 
This is not uniform across but facing in some of my win 2012 R2 and now on Win 2016 servers 
Any idea ?

**Comment by niphlod** [comment] 2020-11-05 13:42
please post the command you're using and the resulting failures, this question lacks every bit of detail needed to help you

**Comment by EbenRaja** [comment] 2020-11-05 15:06
WARNING: [06:53:44][Get-DbaAvailabilityGroup] Failure. | Login failed for user 
'my windows sqlagent service account '.
Error 
while syncing logins for Availability Group 'AGlistenername: Cannot bind 
argument to parameter 'SqlInstance' because it is null.'
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,SyncLoginsToReplica.ps1

**Comment by EbenRaja** [comment] 2020-11-05 15:07
this SQL agetn service account has sysadmin rights on DB and admin rights on server

**Comment by EbenRaja** [comment] 2020-11-05 15:19
SQL agent job runs the CMD exec command below and the .ps1 script is taken from dbatool blog only 
Powershell -file "D:\Microsoft SQL Server\MSSQL12.MSSQLSERVER\AG\SyncLoginsToReplica.ps1"
================
# define the AG name
$AvailabilityGroupName ='AGlistenername'
 
# internal variables
    $ClientName = 'AG Login Sync helper'
    $primaryInstance = $null
    $secondaryInstances = @{}
 

try {
    # connect to the AG listener, get the name of the primary and all secondaries
        $replicas = Get-DbaAgReplica -SqlInstance $AvailabilityGroupName 
        $primaryInstance = $replicas | Where Role -eq Primary | select -ExpandProperty name
        $secondaryInstances = $replicas | Where Role -ne Primary | select -ExpandProperty name
    # create a connection object to the primary
        $primaryInstanceConnection = Connect-DbaInstance $primaryInstance -ClientName $ClientName
    # loop through each secondary replica and sync the logins
        $secondaryInstances | ForEach-Object {
            $secondaryInstanceConnection = Connect-DbaInstance $_ -ClientName $ClientName
            Copy-DbaLogin -Source $primaryInstanceConnection -Destination $secondaryInstanceConnection -ExcludeSystemLogins 
        }
}
catch {
    $msg = $_.Exception.Message
    Write-Error "Error while syncing logins for Availability Group '$($AvailabilityGroupName): $msg'"
}

**Comment by nvarscar** [comment] 2020-11-05 18:33
You should rightfully focus on this one, the rest is just a result of not getting any data:

```
WARNING: [06:53:44][Get-DbaAvailabilityGroup] Failure. | Login failed for user 'my windows sqlagent service account '.
```

1. Double check that your SQL agent runs under the account that has proper permissions on the remote servers.
2. Try to run the script manually by opening Powershell using `runas` under the Sql Agent account.
3. Check your target server logs, login failures are logged by default. The error message is usually informative enough to find the root cause.

**Comment by EbenRaja** [comment] 2020-11-06 10:19
Point 2 and 3 helped to nail the issue, yes it has it on security logs, for some reason this issue crops on SQL2014 /Windows 2012R2 but i dont see the same on Windows 2016 /SQL2016. 
Again thanks Kirill for the assistance.

**Comment by nvarscar** [comment] 2020-11-06 18:26
Glad it worked for you. 
Closing the issue.

**Closed** 2020-11-06 18:25 UTC
Labels: Question
