### ISSUE TITLE
[Bug] Get-DbaService - No services found in relevant namespaces

### ISSUE THREAD

**Issue by RonniePitts** [sqlcollaborative/dbatools#7033] opened 2020-12-13 23:54 UTC
**Report**

Host used
[ X] powershell.exe
[X ] ISE
 VS Code
 Other (please specify)

Errors Received
Transcript started, output file is C:\Users\SOMEUSER\Documents\PowerShell_transcript.DESKTOP-4GBJ93T.YojLPlol.20201214111123.txt
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> Get-DbaService -ComputerName $env:COMPUTERNAME
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
>> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
>> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
>> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
WARNING: [11:11:31][Get-DbaService] No services found in relevant namespaces on DESKTOP-4GBJ93T. Please note that this function is available from SQL 2005 up.
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> Stop-Transcript

Steps to Reproduce
   1. Get-DbaService $env:ComputerName on a new PS session 
   2. Repeat same command now returns zero results and warning 

Expected Behavior
Services as per initial execution 

Actual Behavior
WARNING: [10:41:43][Get-DbaService] No services found in relevant namespaces on SOMECOMPUTER. Please note that this
function is available from SQL 2005 up.

Environmental information
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

PowerShell Version : 5.1.18362.1171
dbatools latest installed : 1.0.134
Culture of OS : en-AU

SQL Server:

us_english

Modules Active 
Script     1.0.134    dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, ...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...

**Comment by RonniePitts** [comment] 2020-12-14 00:03
Note, $stacktrace exists as well. 

$StackTrace
   at Sqlcollaborative.Dbatools.Connection.ManagementConnection.GetConnectionType(ManagementConnectionType ExcludedTypes, Boolean Force) in D:\Code\Github\dbatools\bin\projects\dbatools\dbatools\Connection\ManagementConnection.cs:line 629
   at CallSite.Target(Closure , CallSite , Object , Object , SwitchParameter )

**Comment by wsmelton** [comment] 2020-12-14 00:07
Please update your issue with the relevant information requested via our template or close and open a new issue.

**Comment by RonniePitts** [comment] 2020-12-14 00:22
Transaction Details - First Execution 

**********************
Windows PowerShell transcript start
Start time: 20201214111026
Username: AzureAD\SOMEUSER
RunAs User: AzureAD\SOMEUSER
Configuration Name: 
Machine: DESKTOP-4GBJ93T (Microsoft Windows NT 10.0.18363.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 11520
PSVersion: 5.1.18362.1171
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.18362.1171
BuildVersion: 10.0.18362.1171
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\SOMEUSER\Documents\PowerShell_transcript.DESKTOP-4GBJ93T.0kdJNBWX.20201214111026.txt
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> Get-DbaService -ComputerName $env:COMPUTERNAME
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> TerminatingError(): "Provider load failure "
>> TerminatingError(): "Provider load failure "
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
>> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."


ComputerName : DESKTOP-4GBJ93T
ServiceName  : PowerBIReportServer
ServiceType  : SSRS
InstanceName : PBIRS
DisplayName  : Power BI Report Server
StartName    : NT SERVICE\PowerBIReportServer
State        : Stopped
StartMode    : Disabled

ComputerName : DESKTOP-4GBJ93T
ServiceName  : MsDtsServer150
ServiceType  : SSIS
InstanceName :
DisplayName  : SQL Server Integration Services 15.0
StartName    : NT Service\MsDtsServer150
State        : Running
StartMode    : Automatic

ComputerName : DESKTOP-4GBJ93T
ServiceName  : MSOLAP$SQL2019
ServiceType  : SSAS
InstanceName : SQL2019
DisplayName  : SQL Server Analysis Services (SQL2019)
StartName    : NT Service\MSOLAP$SQL2019
State        : Running
StartMode    : Automatic

ComputerName : DESKTOP-4GBJ93T
ServiceName  : MSSQL$SQL2008
ServiceType  : Engine
InstanceName : SQL2008
DisplayName  : SQL Server (SQL2008)
StartName    : LocalSystem
State        : Stopped
StartMode    : Disabled

ComputerName : DESKTOP-4GBJ93T
ServiceName  : MSSQLFDLauncher$SQL2008
ServiceType  : FullText
InstanceName : SQL2008
DisplayName  : SQL Full-text Filter Daemon Launcher (SQL2008)
StartName    : NT AUTHORITY\LOCALSERVICE
State        : Stopped
StartMode    : Manual

ComputerName : DESKTOP-4GBJ93T
ServiceName  : MSSQLSERVER
ServiceType  : Engine
InstanceName : MSSQLSERVER
DisplayName  : SQL Server (MSSQLSERVER)
StartName    : NT Service\MSSQLSERVER
State        : Running
StartMode    : Manual

ComputerName : DESKTOP-4GBJ93T
ServiceName  : MSSQLServerOLAPService
ServiceType  : SSAS
InstanceName : MSSQLSERVER
DisplayName  : SQL Server Analysis Services (MSSQLSERVER)
StartName    : LocalSystem
State        : Running
StartMode    : Automatic

ComputerName : DESKTOP-4GBJ93T
ServiceName  : SQLAgent$SQL2008
ServiceType  : Agent
InstanceName : SQL2008
DisplayName  : SQL Server Agent (SQL2008)
StartName    : LocalSystem
State        : Stopped
StartMode    : Manual

ComputerName : DESKTOP-4GBJ93T
ServiceName  : SQLBrowser
ServiceType  : Browser
InstanceName :
DisplayName  : SQL Server Browser
StartName    : NT AUTHORITY\LOCALSERVICE
State        : Running
StartMode    : Automatic

ComputerName : DESKTOP-4GBJ93T
ServiceName  : SQLSERVERAGENT
ServiceType  : Agent
InstanceName : MSSQLSERVER
DisplayName  : SQL Server Agent (MSSQLSERVER)
StartName    : NT Service\SQLSERVERAGENT
State        : Stopped
StartMode    : Manual



PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> Stop-Transcript
**********************
Windows PowerShell transcript end
End time: 20201214111048
**********************

**Comment by RonniePitts** [comment] 2020-12-14 00:23
Second Execution 

**********************
Windows PowerShell transcript start
Start time: 20201214111123
Username: AzureAD\SOMEUSER
RunAs User: AzureAD\SOMEUSER
Configuration Name: 
Machine: DESKTOP-4GBJ93T (Microsoft Windows NT 10.0.18363.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 11520
PSVersion: 5.1.18362.1171
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.18362.1171
BuildVersion: 10.0.18362.1171
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\SOMEUSER\Documents\PowerShell_transcript.DESKTOP-4GBJ93T.YojLPlol.20201214111123.txt
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> Get-DbaService -ComputerName $env:COMPUTERNAME
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
>> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
>> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
>> TerminatingError(): "Multiple protocol connections were attempted, but no successful connections could be established with the specified computer."
WARNING: [11:11:31][Get-DbaService] No services found in relevant namespaces on DESKTOP-4GBJ93T. Please note that this function is available from SQL 2005 up.
PS C:\Users\SOMEUSER\OneDrive\Documents\Clients\PowerShell\dbatools-master> Stop-Transcript
**********************
Windows PowerShell transcript end
End time: 20201214111134
**********************

**Comment by RonniePitts** [comment] 2020-12-14 03:55
Problem is due to the ComputerManagement10 (SQL2008) namespace, uninstalling SQL 2008 resolves the problem. 

Below output before removing the ComputerManagement10 namespace. 

Note that the second attempts fails to report any  DCOM connection type within Get-DbaCmObject.



Verbose on first attempt: 

VERBOSE: [14:35:05][Resolve-DbaNetworkName] Resolving DESKTOP-4GBJ93T using .NET.Dns GetHostEntry
VERBOSE: [14:35:05][Resolve-DbaNetworkName] Resolving 192.168.7.4 using .NET.Dns GetHostByAddress
VERBOSE: [14:35:09][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:35:09][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Success
VERBOSE: [14:35:10][Resolve-DbaNetworkName] Resolving DESKTOP-4GBJ93T using .NET.Dns GetHostEntry
VERBOSE: [14:35:10][Get-DbaService] Getting SQL Reporting Server services on DESKTOP-4GBJ93T
VERBOSE: [14:35:10][Get-DbaReportingService] Getting Reporting Server namespace on DESKTOP-4GBJ93T
VERBOSE: [14:35:10][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Success
VERBOSE: [14:35:10][Get-DbaReportingService] Getting version from the namespace RS_PBIRS on DESKTOP-4GBJ93T.
VERBOSE: [14:35:10][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Success
VERBOSE: [14:35:10][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Success
VERBOSE: [14:35:10][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:35:10][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Success
VERBOSE: [14:35:11][Get-DbaService] Getting SQL Server namespace on DESKTOP-4GBJ93T
VERBOSE: [14:35:11][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Success
VERBOSE: [14:35:11][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement15 on DESKTOP-4GBJ93T.
VERBOSE: [14:35:11][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Success
VERBOSE: [14:35:11][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement14 on DESKTOP-4GBJ93T.
VERBOSE: [14:35:11][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Failed
VERBOSE: [14:35:11][Get-DbaService] Failed to acquire services from namespace ComputerManagement14. | Provider load
failure
VERBOSE: [14:35:11][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement10 on DESKTOP-4GBJ93T.
VERBOSE: [14:35:11][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:35:12][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:35:12][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM
VERBOSE: [14:35:14][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Failed
VERBOSE: [14:35:14][Get-DbaService] Failed to acquire services from namespace ComputerManagement10. | Multiple protocol
 connections were attempted, but no successful connections could be established with the specified computer.

**Second attempt**

VERBOSE: [14:33:51][Resolve-DbaNetworkName] Resolving DESKTOP-4GBJ93T using .NET.Dns GetHostEntry
VERBOSE: [14:33:51][Resolve-DbaNetworkName] Resolving 192.168.7.4 using .NET.Dns GetHostByAddress
VERBOSE: [14:33:56][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:33:56][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:33:56][Resolve-DbaNetworkName] Unable to get domain name from DESKTOP-4GBJ93T
VERBOSE: [14:33:56][Resolve-DbaNetworkName] Resolving DESKTOP-4GBJ93T using .NET.Dns GetHostEntry
VERBOSE: [14:33:56][Get-DbaService] Getting SQL Reporting Server services on DESKTOP-4GBJ93T
VERBOSE: [14:33:56][Get-DbaReportingService] Getting Reporting Server namespace on DESKTOP-4GBJ93T
VERBOSE: [14:33:56][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:33:56][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
VERBOSE: [14:33:56][Get-DbaReportingService] No SQLServer\ReportServer Namespace on DESKTOP-4GBJ93T. Please note that
this function is available from SQL 2005 up.
VERBOSE: [14:33:56][Get-DbaService] Getting SQL Server namespace on DESKTOP-4GBJ93T
VERBOSE: [14:33:56][Get-DbaCmObject] Configuration loaded | Cache disabled: True
VERBOSE: [14:33:56][Get-DbaCmObject] [desktop-4gbj93t] Retrieving Management Information
WARNING: [14:33:56][Get-DbaService] No services found in relevant namespaces on DESKTOP-4GBJ93T. Please note that this
function is available from SQL 2005 up.

**Comment by wsmelton** [comment] 2020-12-14 04:47
What versions of SQL Server tools were installed on the target machine?

**Comment by RonniePitts** [comment] 2020-12-14 04:53
> What versions of SQL Server tools were installed on the target machine?

Actually its 1.0.135. 

I've resolved the problem by temporary removing the local SQL 2008 instance (Dev Machine), it throws an exception when the SQL 2008 namespace exists but still outputs the table, second attempt to the method will fail completely.

Installing SQL 2008 and SQL 2019 instance should throw up the same issue.

**Comment by RonniePitts** [comment] 2020-12-14 04:54
sql server data tools 16.0.62010.06180

**Comment by andreasjordan** [comment] 2021-06-05 15:00
I think the problem is about disabling a protocol after a failure:

VERBOSE: [14:35:11][Get-DbaService] Getting SQL Server namespace on DESKTOP-4GBJ93T
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Success
VERBOSE: [14:35:11][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement15 on DESKTOP-4GBJ93T.
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Success
VERBOSE: [14:35:11][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement14 on DESKTOP-4GBJ93T.
VERBOSE: [14:35:11][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Failed
VERBOSE: [14:35:11][Get-DbaService] Failed to acquire services from namespace ComputerManagement14. | Provider load
failure
VERBOSE: [14:35:11][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement10 on DESKTOP-4GBJ93T.
VERBOSE: [14:35:14][Get-DbaCmObject] [desktop-4gbj93t] Accessing computer using Cim over DCOM - Failed
VERBOSE: [14:35:14][Get-DbaService] Failed to acquire services from namespace ComputerManagement10. | Multiple protocol
connections were attempted, but no successful connections could be established with the specified computer

So I think the root cause is that getting ComputerManagement14 failed. Getting ComputerManagement15 was ok, but ComputerManagement14 and ComputerManagement10 failed. After you uninstalled SQL Server 2008 (ComputerManagement10) there was only one failure which did not disable the protocol.

It looks like ComputerManagement14 is failing because there are no SQL Server 2017 instances installed.
Ok, wild guesses - will try to setup this in my lab.

@RonniePitts Are you still able to reproduce this? Then we can work on this together.

**Comment by andreasjordan** [comment] 2021-06-05 15:47
I added a verbose message to show which services were found in which namespace. All services are found in the highest namespace, the lower namespaces only report services with version equal or lower that the version of the namespace.

So I think it is totally useless to collect information from all namespaces.

I will introduce a hidden config to change this behavior so we can test this in the field.

**Comment by wsmelton** [comment] 2021-06-05 16:00
SSCM when multiple versions will only work generally using the highest version.

I don't think a hidden config is needed, it is waste of processing to go through every version found when we could pick the highest version and use it to query the machine, I would think.

**Comment by andreasjordan** [comment] 2021-06-05 16:03
OK, thanks for the quick response. PR is nearly finished, so I will remove the config now.

**Comment by andreasjordan** [comment] 2021-06-05 16:26
I had a SQL Server 2017 and 2019 installed, so I have namespaces 15 and 14. But I removed the instances and only have SQL Server 2016 and 2014 left on the maschine. That is the verbose output based on by pull request:

PS C:\Git\dbatools> Get-DbaService -ComputerName SRV1 -Verbose | ft

VERBOSE: [18:24:03][Resolve-DbaNetworkName] Resolving SRV1 using .NET.Dns GetHostEntry
VERBOSE: [18:24:03][Resolve-DbaNetworkName] Resolving 192.168.3.51 using .NET.Dns GetHostByAddress
VERBOSE: [18:24:03][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [18:24:03][Get-DbaCmObject] [srv1] Retrieving Management Information
VERBOSE: [18:24:03][Get-DbaCmObject] [srv1] Accessing computer using Cim over WinRM
VERBOSE: [18:24:04][Get-DbaCmObject] [srv1] Accessing computer using Cim over WinRM - Success
VERBOSE: [18:24:05][Resolve-DbaNetworkName] Resolving SRV1.Company.Pri using .NET.Dns GetHostEntry
VERBOSE: [18:24:05][Get-DbaService] Getting SQL Reporting Server services on SRV1.Company.Pri
VERBOSE: [18:24:05][Get-DbaReportingService] Getting Reporting Server namespace on SRV1.Company.Pri
VERBOSE: [18:24:05][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [18:24:05][Get-DbaCmObject] [srv1.company.pri] Retrieving Management Information
VERBOSE: [18:24:05][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM - Failed
VERBOSE: [18:24:06][Get-DbaReportingService] No SQLServer\ReportServer Namespace on SRV1.Company.Pri. Please note that this function is available from SQL 2005 up.
VERBOSE: [18:24:06][Get-DbaService] Getting SQL Server namespaces on SRV1.Company.Pri
VERBOSE: [18:24:06][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Retrieving Management Information
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM - Success
VERBOSE: [18:24:06][Get-DbaService] The following namespaces have been found: ComputerManagement15, ComputerManagement14, ComputerManagement13, ComputerManagement12.
VERBOSE: [18:24:06][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement15 on SRV1.Company.Pri.
VERBOSE: [18:24:06][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Retrieving Management Information
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM - Failed
VERBOSE: [18:24:06][Get-DbaService] Failed to acquire services from namespace ComputerManagement15. | The WS-Management service cannot process the request. The WMI service or the WMI provider returned an unknown error: HRESULT 0x80041013
VERBOSE: [18:24:06][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement14 on SRV1.Company.Pri.
VERBOSE: [18:24:06][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Retrieving Management Information
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM - Failed
VERBOSE: [18:24:06][Get-DbaService] Failed to acquire services from namespace ComputerManagement14. | The WS-Management service cannot process the request. The WMI service or the WMI provider returned an unknown error: HRESULT 0x80041013
VERBOSE: [18:24:06][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement13 on SRV1.Company.Pri.
VERBOSE: [18:24:06][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Retrieving Management Information
VERBOSE: [18:24:06][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM
VERBOSE: [18:24:07][Get-DbaCmObject] [srv1.company.pri] Accessing computer using Cim over WinRM - Success
VERBOSE: [18:24:07][Get-DbaService] Found service MSSQL$SQL2014 in namespace ComputerManagement13.
VERBOSE: [18:24:07][Get-DbaService] Found service MSSQL$SQL2016 in namespace ComputerManagement13.
VERBOSE: [18:24:07][Get-DbaService] Found service SQLAgent$SQL2014 in namespace ComputerManagement13.
VERBOSE: [18:24:07][Get-DbaService] Found service SQLAgent$SQL2016 in namespace ComputerManagement13.
VERBOSE: [18:24:07][Get-DbaService] Found service SQLBrowser in namespace ComputerManagement13.

ComputerName ServiceName      ServiceType InstanceName DisplayName                StartName                 State   StartMode
------------ -----------      ----------- ------------ -----------                ---------                 -----   ---------
SRV1         MSSQL$SQL2014    Engine      SQL2014      SQL Server (SQL2014)       COMPANY\SQLServer         Running Automatic
SRV1         MSSQL$SQL2016    Engine      SQL2016      SQL Server (SQL2016)       COMPANY\SQLServer         Running Automatic
SRV1         SQLAgent$SQL2014 Agent       SQL2014      SQL Server Agent (SQL2014) COMPANY\SQLServer         Running Automatic
SRV1         SQLAgent$SQL2016 Agent       SQL2016      SQL Server Agent (SQL2016) COMPANY\SQLServer         Running Automatic
SRV1         SQLBrowser       Browser                  SQL Server Browser         NT AUTHORITY\LOCALSERVICE Running Automatic


So I think it works ok, will open the pull request.

**Closed** 2021-06-11 08:04 UTC
Labels: bugs_life
