### ISSUE TITLE
[Bug] Invoke-DbaQuery not using SqlCredential with windows login in PowerShell 7

### ISSUE THREAD

**Issue by mcascone** [sqlcollaborative/dbatools#7514] opened 2021-07-07 21:12 UTC
### Report
`Invoke-DbaQuery` does not use the `-SqlCredential` param in PS7

#### Host used

- [x] powershell.exe
- [x] ISE
- [x] VS Code
- [ ] Other (please specify)

#### Errors Received

```
> $ERROR[0] | SELECT *

PSMessageDetails      :
Exception             : System.Exception: Login failed for user 'CONSILIO\mcascone1'.
                         ---> System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'CONSILIO\mcascone1'.
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate,
                        Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions
                        userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions
                        userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory,
                        TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory,
                        TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                        ClientConnectionId:7845abbd-19f5-49e1-a0ad-0322dfa158e5
                        Error Number:18456,State:1,Class:14
                           --- End of inner exception stack trace ---
TargetObject          : LNTVPDSQL210.CONSILIO.COM
CategoryInfo          : NotSpecified: (LNTVPDSQL210.CONSILIO.COM:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaQuery,Stop-Function
ErrorDetails          : Login failed for user 'CONSILIO\mcascone1'.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.169\allcommands.ps1: line 89798
                        at Invoke-DbaQuery<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.169\allcommands.ps1: line 49564
                        at <ScriptBlock>, C:\Users\mcascone1\Documents\github\consilio-pipeline-library\test\integration\RelPrimarySql.Integration.Tests.ps1: line 34
                        at <ScriptBlock>, C:\Users\mcascone1\Documents\github\consilio-pipeline-library\test\integration\RelPrimarySql.Integration.Tests.ps1: line 33
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

This command works in PS 5.1:
```
> $query = 'select 1'
> $cred = get-credential my-username
> Invoke-DbaQuery -SqlInstance $sqlservers -Query $query -SqlCredential $cred -Database 'EDDS'
Column1
      1
```

It does NOT work in PS7:

```
> Invoke-DbaQuery -SqlInstance $sqlservers -Query $query -SqlCredential $cred -Database 'EDDS'
WARNING: [16:07:41][Invoke-DbaQuery] Failure | Login failed for user 'CONSILIO\mcascone1'.
```

#### Expected Behavior

dba query succeeds exactly like in PS 5.1

#### Actual Behavior

I get an auth error, as if it is trying to connect with the target DB as the session user, and not the passed-in Credential. 

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```
```powershell
Get-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9445
Line |
9445 |          PackageManagement\Get-Package @PSBoundParameters | Microsoft. …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and module names 'dbatools'.


PowerShell Version        : 7.1.3
dbatools latest installed :
Culture of OS             : en-US
```

but:
```
> get-module dbatools

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.0.169               dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener…}
```

#### SQL Server:

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

**Comment by andreasjordan** [comment] 2021-07-08 12:54
Can you please try that with the new code path for connections? Enable it in that session with:
Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true

**Comment by mcascone** [comment] 2021-07-08 14:26
Sorry, but that didn't change anything:

```powershell
> $cred
UserName                                     Password
--------                                     --------
CONSILIO\SP_PIPELINE_ENG System.Security.SecureString

> Invoke-DbaQuery -SqlInstance $sqlservers -Query $query -SqlCredential $cred -Database 'EDDS'
WARNING: [09:23:51][Invoke-DbaQuery] Failure | Login failed for user 'CONSILIO\mcascone1'.
> Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true
> Invoke-DbaQuery -SqlInstance $sqlservers -Query $query -SqlCredential $cred -Database 'EDDS'
WARNING: [09:24:01][Invoke-DbaQuery] Failure | Login failed for user 'CONSILIO\mcascone1'.
```

**Comment by andreasjordan** [comment] 2021-07-08 14:36
What type is $sqlservers? Is it a string? Or something you got from Connect-DbaInstance?
Does `Connect-DbaInstance -SqlInstance $sqlservers -SqlCredential $cred` work?

**Comment by mcascone** [comment] 2021-07-08 16:02
`sqlservers` is just a string:

```powershell
> $sqlservers = 'my-sql-server.mydomain.COM'
```

similar result with the `Connect` cmd: works in 5, fails in 7:
```powershell 
# ps5
######
> $sqlservers = 'my-sql-server.mydomain.COM'
> Connect-DbaInstance -SqlInstance $sqlservers -SqlCredential $cred

ComputerName Name                           Product              Version   HostPlatform IsAzure IsClustered ConnectedAs
------------ ----                           -------              -------   ------------ ------- ----------- -----------
my-sql-server my-sql-server.mydomain.COM    Microsoft SQL Server 11.0.7507 Windows      False   False       mydomain\my-service-account

# ps7
#####
> $sqlservers
my-sql-server.mydomain.COM
> Connect-DbaInstance -SqlInstance $sqlservers -SqlCredential $cred
ConnectionError: C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.169\allcommands.ps1:89790
 Line |
89790 |          throw $records[0]
      |          ~~~~~~~~~~~~~~~~~
      | Login failed for user 'mydomain\my-user-account-not-my-service-account'.
```

**Comment by andreasjordan** [comment] 2021-07-08 16:09
So the account in $cred is an AD account? In that case the powershell session is not able to switch the security context before connecting with integrated security. So this might be an issue with the way powershell is installed or started. There is not much we can do about this.
As a workaround you can try to run powershell "as different account" and use the mydomain\my-service-account - have you tried that?

**Comment by mcascone** [comment] 2021-07-08 16:27
I'm not sure I understand. It works perfectly in PowerShell 5, with the explicitly set `SqlCredential`. Why doesn't the same command work in PowerShell 7?

**Comment by andreasjordan** [comment] 2021-07-08 16:31
Ok, I will go into detail. But first confirm, that $cred holds a domain account. Correct?

**Comment by mcascone** [comment] 2021-07-08 16:32
Thanks. Yes, it's an AD account.

**Comment by andreasjordan** [comment] 2021-07-08 16:41
So $cred holds username and password. Inside of Connect-DbaInstance (you can have a look at the source code) we store these information in the SMO (Server Managed Object - a class inside of a dll from Microsoft) to handle the connection.

The thing with connecting as anonther domain account is: The username/password is not transfered to the computer with the instance, but instead inside of your powershell session there is kind of a context switch like if you start a local program under a different account. And then this new context is just connecting to the instance with integrated security as if you would not use -SqlCredential.

Sometimes this switch is not successful, but the SMO does not throw an exception and goes on - now connecting with your normal account. This is what happens here.

There is nothing dbatools can do about this. So in the end we will close this as a no-bug...

But it might be a bug inside of the dll we use in combination with your powershell version and mybe the way this powershell is set up.

Maybe @wsmelton has more ideas.

**Comment by mcascone** [comment] 2021-07-08 16:44
So since it works in 5 but not in 7, are you suggesting I should log an issue against [PowerShell 7](https://github.com/PowerShell/PowerShell)?

**Comment by andreasjordan** [comment] 2021-07-08 16:46
It's maybe not PowerShell itself but the SMO. Let's wait if @wsmelton has an idea.

**Comment by mcascone** [comment] 2021-07-08 17:45
I just noticed this: Is it correct?

```powershell
> get-module dbatools -All

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.10.0.71  dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Write-Message}
Script     1.0.169    dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}  
```

**Comment by andreasjordan** [comment] 2021-07-08 17:47
Don't know, @potatoqualitee - please have a look.

**Comment by potatoqualitee** [comment] 2021-07-08 17:48
That is indeed correct. One is our DLL and one is our module.

This seems like an SMO Core issue, which would not be a PowerShell team issue but rather the sql server team at https://github.com/microsoft/sqlmanagementobjects.

There's a new version of SMO coming out likely within the next 24 hours, so we'll take another look once that's been released.

**Comment by mcascone** [comment] 2021-07-08 17:58
I really appreciate your attention to this!

**Comment by wsmelton** [comment] 2021-07-08 22:39
The `Invoke-DbaQuery` function depends on the Connection Context being passed to `Invoke-DbaAsync` which is an internal function. The server connection we create contains that property. We take the connection created by `Connect-DbaInstance` for this purpose:

https://github.com/sqlcollaborative/dbatools/blob/35fa1b5884a9a8b9108cb5306f487c07f094b350/functions/Invoke-DbaQuery.ps1#L352-L373

The `ConnectionContext` property is passed to the internal function and then we pull the connection object from that, this is where in lies the flaw of how `Invoke-DbaQuery` is written (among a few other things):

https://github.com/sqlcollaborative/dbatools/blob/35fa1b5884a9a8b9108cb5306f487c07f094b350/internal/functions/Invoke-DbaAsync.ps1#L162-L175

The `SqlConnectionObject` does not carry the username and password for a Windows Authentication account because SQL Connection Strings don't support it. The connection string therefore is changed to use `Integrated Security=true`. That is not SMO specific because at this point we are switching to utilizing the `SQLClient` library.

You can view this by running the following:

```powershell
$cred = Get-Credential <account to connect to SQL>
$connection = Connect-DbaInstance -SqlInstance <your server> -SqlCredential $cred
$connection.ConnectContext | select TrueLogin, ConnectAsUsername, ConnectAsUser
```

Output example:

```console
[PS 7.1.3] [17:24:53.982] [ 24.0ms ] C:\Windows\System32
[14] > whoami
lab\labadmin
[PS 7.1.3] [17:24:58.981] [ 36.0ms ] C:\Windows\System32
[15] > $connection = Connect-DbaInstance -SqlInstance sql -SqlCredential $cred
[PS 7.1.3] [17:25:02.439] [ 72.0ms ] C:\Windows\System32
[16] > $connection.ConnectionContext | select TrueLogin, ConnectAsUserName, ConnectAsUser

TrueLogin    ConnectAsUserName ConnectAsUser
---------    ----------------- -------------
lab\labadmin vaultapp@lab               True
```

![image](https://user-images.githubusercontent.com/11204251/124998173-8d065380-e011-11eb-8d40-1c9d234720d0.png)

Now look at the `SqlConnectionObject` and you will see your Windows Account is dropped and not included anymore:

```powershell
$connection.ConnectionContext.SqlConnectionObject
```

Output:

```console
StatisticsEnabled                : False
ConnectionString                 : Data Source=sql;Integrated Security=True;MultipleActiveResultSets=False;Encrypt=Fals
                                   e;TrustServerCertificate=False;Application Name="dbatools PowerShell module -
                                   dbatools.io"
ConnectionTimeout                : 15
AccessToken                      :
Database                         : master
DataSource                       : sql
PacketSize                       : 8000
ClientConnectionId               : 6fa3e1e9-70f2-4edb-be51-ebc57ffb7112
ServerVersion                    : 15.00.2000
State                            : Open
WorkstationId                    : GUI
Credential                       :
FireInfoMessageEventOnUserErrors : False
Site                             :
Container                        :
```

![image](https://user-images.githubusercontent.com/11204251/1215-47e32100-e013-11eb-93e8-f62a731a57b3.png)

In the end, this is all by design :wink:

**Comment by potatoqualitee** [comment] 2021-07-09 08:56
But wait, I'm confused. How does it work in PS5.1 but not PS7, even with the same code path?

**Comment by andreasjordan** [comment] 2021-07-09 08:58
Maybe inside of the SMO, there are different paths for each PS version?

**Comment by potatoqualitee** [comment] 2021-07-09 09:03
Yeah, I'm wondering if it was changed in Core. If it hasn't been fixed in the next SMO update that we get, I'll file a bug.

**Comment by wsmelton** [comment] 2021-07-09 12:07
https://github.com/sqlcollaborative/dbatools/blob/35fa1b5884a9a8b9108cb5306f487c07f094b350/internal/functions/Invoke-DbaAsync.ps1#L143-L156

**Comment by andreasjordan** [comment] 2021-07-09 12:10
But that is only used with `-As PSObject` or `-As PSObjectArray`.

**Comment by wsmelton** [comment] 2021-07-09 12:15
`Invoke-DbaAsync` does not have the physical ability to use a SQL Connection with a Windows Account. SqlClient itself does not support it and the internal command is not using anything with SMO.

**Comment by andreasjordan** [comment] 2021-07-09 12:21
Maybe `Invoke-DbaQuery` / `Invoke-DbaAsync` need an update to better handle connections. It is on my list as soon as we only have the new code path in `Connect-DbaInstance` - so maybe later this year.

**Comment by potatoqualitee** [comment] 2021-07-09 14:03
🤔  I wonder if Microsoft.Data.SqClient supports it!

**Comment by niphlod** [comment] 2021-07-09 14:07
IMHO it either never works or it works. It's true that sqlclient doesn't support creating a connection impersonating a different user, but technically we do something a little bit different, which is to pass sqlcommand an already opened connection. Is it documented as supported ? not really. But, again, it either works or it doesn't, can't be a "spotty" pattern where for some it works and for other it doesn't.

**Comment by wsmelton** [comment] 2021-07-09 14:19
Yep, and to really know why there is a difference between Windows PS and PS 7 would require internal knowledge of many things MS will never share with us 😁

**Comment by mcascone** [comment] 2021-07-09 15:46
I really, really appreciate the deep dive into this and all the attention you all have paid to it. Where does all of this leave us? 
- L144 from [@wsmelton's post](https://github.com/sqlcollaborative/dbatools/issues/7514#issuecomment-877139171) looks very much like a possible cause. 
- Does PS7, SMO, or somewhere else need an issue logged for this? 
- Do we need to wait for it to get to the top of @andreasjordan's [list](https://github.com/sqlcollaborative/dbatools/issues/7514#issuecomment-877147080)?
- Is there any kind of workaround for PS7?

**Comment by andreasjordan** [comment] 2021-07-09 16:00
L144 is not executed in your case...

**Comment by andreasjordan** [comment] 2021-07-09 16:02
If `Connect-DbaInstance -SqlInstance $sqlservers -SqlCredential $cred` does not work, the issue has nothing to do with `Invoke-DbaQuery`.

**Comment by mcascone** [comment] 2021-07-09 16:24
> L144 is not executed in your case...

What I mean is, there's a difference in the code for PS5 and PS7.

**Comment by wsmelton** [comment] 2021-07-09 16:36
L144 won't apply based on the example command you are running @mcascone. It is only when you are using the `-As` object.

If you run the example code I provided you can see if the Connection object in PS7 is not showing you the `ConnectAsUserName`. As Simone noted it has done this process from day one, very likely it has never worked in PS7 and likely never will. 

The workaround for PS7 if you need to run the code in PowerShell as that user. You can do this using `Start-Process ... -Credential` or something of that nature.

**Comment by potatoqualitee** [comment] 2021-07-10 07:28
@andreasjordan has been making a lot of advancements with the way he connects to SQL Server. I've got faith we can figure this out but it may take some help from Microsoft if it's a bug fix. I'm still waiting for the new SMO to be published. 

Until then, another potential workaround is to use `$server.Query()`

```
$server = Connect-DbaInstance -SqlInstance sql2012
$server.Query($sql)
```

That should work unless you've got some advanced parsing in your scripts.

**Comment by andreasjordan** [comment] 2021-07-10 11:58
As `Connect-DbaInstance` is the failing part (https://github.com/sqlcollaborative/dbatools/issues/7514#issuecomment-876559833), `.Query()` is not a possible workaround.
Only possibility I see is starting the session using the target account (https://github.com/sqlcollaborative/dbatools/issues/7514#issuecomment-877312474).

**Comment by wsmelton** [comment] 2021-07-10 12:03
If the user need for the run as doesn't have access to master then the login attempt will fail. Was it tested with specifying the database when you run connect command?

**Comment by mcascone** [comment] 2021-07-10 19:02
Yes, I specify the database name in the command.

**Comment by andreasjordan** [comment] 2021-07-11 16:29
Maybe that helps finding the root cause: https://github.com/sqlcollaborative/dbatools/discussions/7490#discussioncomment-990420

**Comment by potatoqualitee** [comment] 2021-07-11 16:46
Ohh, can repro. This will be fun.

![image](https://user-images.githubusercontent.com/8278033/125203327-3b133700-e278-11eb-923c-0e93a13b4281.png)


![image](https://user-images.githubusercontent.com/8278033/125203331-40708180-e278-11eb-9ca2-8ef18296e615.png)

**Comment by potatoqualitee** [comment] 2021-07-11 17:03
Look what I found! 🤔 

```
$server.ConnectionContext.SqlConnectionObject | Get-Member Credential


   TypeName: System.Data.SqlClient.SqlConnection

Name       MemberType Definition
----       ---------- ----------
Credential Property   System.Data.SqlClient.SqlCredential Credential {get;set;}
```

https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcredential?view=dotnet-plat-ext-5.0

Going investigate

**Comment by andreasjordan** [comment] 2021-07-12 08:51
Will open a PR with a test shortly.

**Comment by potatoqualitee** [comment] 2021-07-14 16:34
This one is fixed in dev 👍🏼  will release in about 5 days. it's a whopping library change so i want to make sure it's very tested.

**Closed by potatoqualitee** 2021-07-14 16:34 UTC
Labels: bugs life, smo, v1.1.0

**Comment by mcascone** [comment] 2021-07-15 11:53
Amazing! What a display of talent and collaboration! Thank you all!

**Comment by mcascone** [comment] 2021-08-20 15:24
Hi all, unfortunately this doesn't seem to be fixed in the latest release?

```powershell
> get-module dbatools

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.1.11                dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgD…

> $cred = Get-Credential mycompany\my_SPECIAL_creds

PowerShell credential request
Enter your credentials.
Password for user mycompany\my_SPECIAL_creds: ***************

> Invoke-DbaQuery  -database myDB -Query 'select 1' -SqlInstance myInstance -SqlCredential $cred
WARNING: [10:10:32][Invoke-DbaQuery] [myInstance] Failed during execution | Error connecting to [myInstance]: Login failed for user 'mycompany\my_USER_creds'.
```

@potatoqualitee

**Comment by andreasjordan** [comment] 2021-08-20 15:35
For background information please see #7725 and #7726.

As a workaround please first open a non-pooled connection with `$server = Connect-DbaInstance -SqlInstance myInstance -SqlCredential $cred -NonPooledConnection` and use this in `Invoke-DbaQuery  -database myDB -Query 'select 1' -SqlInstance $server`.

**Comment by mcascone** [comment] 2021-08-20 16:11
@andreasjordan that works, in PS7! It feels similar to creating a `PSSession` to reuse throughout a session - I assume the `$server` connection can be treated the same way, reused without reconnecting?

**Comment by andreasjordan** [comment] 2021-08-20 16:13
Yes.
