### ISSUE TITLE
Get-DbaService does not return SSRS 2017 service (probably also not SSRS 2016 too)

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#4375] opened 2018-10-30 16:45 UTC
### Before submitting a bug report:

- [X] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [X] Verified this bug is not already reported in an issue
- [X] Verified errors are not related to permissions
- [X] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
```powershell
Get-DbaService -ComputerName $server -Type SSRS
```

## Expected Behavior

ComputerName : MYSERVER
ServiceName  : SQLServerReportingServices
ServiceType  : SSRS
InstanceName : MSSQLSERVER
DisplayName  : SQL Server Reporting Services (MSSQLSERVER)
StartName    : MYDOMAIN\SomeServiceAccount
State        : Running
StartMode    : Automatic

## Actual Behavior

WARNING: [09:39:31][Get-DbaService] No Sql Services found on myserver.mydomain.com

## Environmental data

                                                                                                                 
PSVersion                      5.1.17134.228                                                                                                               
PSEdition                      Desktop                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                     
BuildVersion                   10.0.17134.228                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                             
WSManStackVersion              3.0                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                         
SerializationVersion           1.1.0.1-->
```
Get-Module dbatools -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                 
---------- -------    ----                                ----------------                                                                                 
Script     0.9.495    dbatools                            {Select-DbaObject, Start-DbaMigration, Copy-DbaDatabase, Copy-DbaLogin...}```

**Comment by niphlod** [comment] 2018-10-30 16:51
duplicate of #3826 and #3349

**Comment by wsuhoey** [comment] 2018-10-30 16:52
I believe the fix is to add an entry for `SQLServerReportingServices` to the line ```if ($service.ServiceName -in ("MSSQLSERVER", "SQLSERVERAGENT", "ReportServer", "MSSQLServerOLAPService"))``` because the service name changed for SSRS 2017 (and probably 2016 but can't confirm that since I don't have a SSRS 2016 instance running, and no one else in slack #ssrs channel responded to my ask.

Get-Service -ComputerName ComputerWith2014orOlder | Where-Object Name -Like '*report*' | Select-Object Name # should return `ReportServer`

Get-Service -ComputerName ComputerWith2016orNewer | Where-Object Name -Like '*report*' | Select-Object Name # should return `SQLServerReportingServices`

**Closed by niphlod** 2018-10-30 16:51 UTC

**Comment by wsuhoey** [comment] 2018-10-30 16:52
Huh, I did a search for Get-DbaService so of course those dupes niph found didn't come up for me.

**Comment by potatoqualitee** [comment] 2018-10-30 18:15
that's a total of 3 - @nvarscar - would you be able to take a look?

**Comment by nvarscar** [comment] 2018-10-30 18:22
I will!
