### ISSUE TITLE
Inconsistent output of Get-DbaDatabaseState function

### ISSUE THREAD

**Issue by ie-zero** [sqlcollaborative/dbatools#648] opened 2017-02-05 18:10 UTC
### Is this a *feature* OR *bug*: 
_Bug_ - Impact Low 

Get-DbaDatabaseState function exhibits inconsistent behavior based on the order the input parameter values are passed.

### System Details

- Operating system name and version: Windows 7
- Output from `$PSVersionTable`:

|Name   |Value|                                                                
|---------|--------------------------|                                                                            
|PSVersion|                      5.0.10586.117  |
|PSCompatibleVersions|           {1.0, 2.0, 3.0, 4.0...}  |
|BuildVersion                 |  10.0.10586.117 |                                                             
|CLRVersion                    | 4.0.30319.42000 |                                                                            
|WSManStackVersion      |        3.0               |                                                                         
|PSRemotingProtocolVersion|      2.3            |                                                                            
|SerializationVersion           |1.1.0.1        |

- Output of dbatools version:
0.8.695

- SQL Server version for source/target
SQL Express (I do not believe it is relevant though) 

### Steps to Reproduce
 Let assume the following scenario ABC\InstanceA is a valid SQL Server instance and DEF is not. 

Execution 1, the server appearing first on the -SqlInstance list, i.e. ABC\InstanceA, is accessible
```PowerShell
Get-DbaDatabaseState -SqlInstance 'ABC\InstanceA', DEF -Exclude ICalData

SqlInstance  : ABC\InstanceA
InstanceName : InstanceA
ComputerName : ABC
DatabaseName : ICalData
RW           : READ_WRITE
Status       : ONLINE
Access       : MULTI_USER

WARNING: Can't connect to DEF
```

Execution 2, the server appearing first on the -SqlInstance list, i.e. DEF, is not accessible
```PowerShell
Get-DbaDatabaseState -SqlInstance DEF, 'ABC\InstanceA' -Exclude ICalData

Get-DbaDatabaseState : A parameter cannot be found that matches parameter name 'Exclude'.
At line:1 char:60
+ ... DatabaseState -SqlInstance DEF, 'ABC\InstanceA' -Exclude ICalDat ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-DbaDatabaseState], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-DbaDatabaseState
```

### Speculation
The most possible cause of this behavior is the way we handle dynamically the -Databases and -Exclude input parameters

**Comment by cvdiermen** [comment] 2017-03-08 18:27
Please don't pay attention to the commit I sent earlier. Sofar I was not into Dynamic Params and the way they are used in this function. Did some reading since then and now realize that the issue is most likely caused by the fact that the function Get-ParamSqlDatabases simply does not work for servers which are not accessible. In that case both (dynamic) parameters (-Database and -Exclude) cannot be populated. It seems to me the error message states this very clear.  Only when you can connect to the first server you specify, you can use the dynamic params, otherwise you can't.

**Comment by niphlod** [comment] 2017-03-13 20:13
this has to do with every command using dynamicparams, it's just the way they work. closing and moving forward as dynamicparams is already scheduled to be replaced with a better solution.

**Closed by niphlod** 2017-03-13 20:13 UTC
Labels: bug
