### ISSUE TITLE
Test-DbaTempDbConfig fails when using localhost for instance

### ISSUE THREAD

**Issue by SQLCanuck** [sqlcollaborative/dbatools#7649] opened 2021-07-29 18:21 UTC
### Verified issue does not already exist?

Yes

### What error did you receive?

writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: The target principal name is incorrect --->
                        Microsoft.Data.SqlClient.SqlException: A connection was successfully established with the
                        server, but then an error occurred during the login process. (provider: SSL Provider, error: 0
                        - The target principal name is incorrect.) ---> System.ComponentModel.Win32Exception: The
                        target principal name is incorrect
                           --- End of inner exception stack trace ---
                           at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean
                        breakConnection, Action`1 wrapCloseInAction)
                           at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject
                        stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at Microsoft.Data.SqlClient.TdsParserStateObject.SNIWritePacket(SNIHandle handle, SNIPacket
                        packet, UInt32& sniError, Boolean canAccumulate, Boolean callerHasConnectionLock)
                           at Microsoft.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate)
                           at Microsoft.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean
                        canAccumulate)
                           at Microsoft.Data.SqlClient.TdsParser.TdsLogin(SqlLogin rec, FeatureExtension
                        requestedFeatures, SessionData recoverySessionData, Nullable`1 fedAuthFeatureExtensionData,
                        SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.Login(ServerInfo server, TimeoutTimer
                        timeout, String newPassword, SecureString newSecurePassword)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo,
                        String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer
                        timeout, Boolean withFailover, Boolean isFirstTransparentAttempt, Boolean disableTnir)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo,
                        String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance,
                        SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout,
                        SqlConnectionString connectionOptions, SqlCredential credential, String newPassword,
                        SecureString newSecurePassword, Boolean redirectedUserInstance)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity
                        identity, SqlConnectionString connectionOptions, SqlCredential credential, Object
                        providerInfo, String newPassword, SecureString newSecurePassword, Boolean
                        redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData
                        reconnectSessionData, ServerCertificateValidationCallback serverCallback,
                        ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken,
                        SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean
                        applyTransientFaultHandling)
                           at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions
                        options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool,
                        DbConnection owningConnection, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool
                        pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey,
                        DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject,
                        DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection
                        owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject,
                        UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection,
                        DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject,
                        TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&
                        connection)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection
                        owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions,
                        DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection
                        outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry,
                        DbConnectionOptions userOptions)
                           at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry,
                        SqlConnectionOverrides overrides)
                           at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           --- End of inner exception stack trace ---
TargetObject          : localhost
CategoryInfo          : ConnectionError: (localhost:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Test-DbaTempDbConfig,Stop-Function
ErrorDetails          : The target principal name is incorrect
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.2\allcommands.ps1:
                        line 90221
                        at Test-DbaTempDbConfig<Process>, C:\Program
                        Files\WindowsPowerShell\Modules\dbatools\1.1.2\allcommands.ps1: line 79455
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

### Steps to Reproduce

# Use dbatools 1.1.0 or above
Test-DbaTempDbConfig -SqlInstance localhost

### Are you running the latest release?

Yes

### Other details or mentions

When noticed the failures happening, I re-tested with an older version 1.0.173 and the error does not occur.  The issue seems to have been introduced with version 1.1.0.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.1971                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.1971                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU11) (KB5003249) - 15.0.4138.2 (X64)   May 27 2021 17:34:14   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by potatoqualitee** [comment] 2021-07-29 19:30
hey @SQLCanuck - it looks like you're using Network Encryption and the wrong hostname? Are you forcing network encryption? Can you try it with the name associated with the certificate? ]

**Comment by SQLCanuck** [comment] 2021-07-29 19:39
Hi @potatoqualitee,
Yes we do force network encryption, though it is being executed locally on the server.  The execution will work if I use the server name, however it does work using localhost if I use a version before 1.1.0

**Comment by potatoqualitee** [comment] 2021-07-29 19:47
ah sweet, i think it's because the updated libraries we now use are more mature and less forgiving -- I'm surprised it worked before. I will close this as not a bug and recommend using the required hostname. Alternatively, adding localhost to your certificate SAN may work as well (tho I'm not so sure that'd be recommended if it does work)

**Comment by SQLCanuck** [comment] 2021-07-29 19:47
@potatoqualitee
Appears this may be a more general regression issue.  I quickly tested Get-DbaDefaultPath and again it fails for localhost when using 1.1.0 or above, but works for version 1.0.173

**Closed by potatoqualitee** 2021-07-29 19:47 UTC
Labels: bugs life

**Comment by SQLCanuck** [comment] 2021-07-29 19:49
@potatoqualitee  thanks for the information.  May I suggest updating the documentation, as localhost is used in a lot of it, or place a note regarding the limitations when using encryption.

**Comment by SQLCanuck** [comment] 2021-07-29 19:51
I feel that this should work though, as using localhost has no issues via SSMS when locally on the server of course.

**Comment by potatoqualitee** [comment] 2021-07-29 20:07
SSMS is still using the older SMO and we're using the newer SMO, so I imagine SSMS's behavior will change in the future as well when they make the switch.

Ahh yes, from https://productsupport.red-gate.com/hc/en-us/articles/360014370757-The-target-principal-name-is-incorrect

>The Microsoft.Data.SqlClient that our tools use to connect to SQL Server has been updated and now defaults to Trust Server Certificate = False in situations where previously defaulted to true. 

So you can make an initial connection using `$server = Connect-DbaInstance -SqlInstance localhost -TrustServerCertificate` then `Get-DbaDatabase -SqlInstance $server`

I also checked our own docs in Connect-DbaInstance and it says

> Beginning in .NET Framework 4.5, when TrustServerCertificate is false and Encrypt is true, the server name (or IP address) in a SQL Server SSL certificate must exactly match the server name (or IP address) specified in the connection string. Otherwise, the connection attempt will fail. For information about support for certificates whose subject starts with a wildcard character (*), see Accepted wildcards used by server certificates for server authentication.

If you are interested, I am open to a PR that allows you to set that config permanently. This is a PR that added a similar setting for MultiSubnetFailover https://github.com/sqlcollaborative/dbatools/pull/7631

**Comment by SQLCanuck** [comment] 2021-07-29 20:14
Thank you for all the information and assistance!  In my case I will simply swap the code to use $env:ComputerName in place of localhost.  I was mostly concerned there may have been a regression bug introduced.

**Comment by potatoqualitee** [comment] 2021-07-29 20:25
oh! we already support it

`Set-DbatoolsConfigValue -FullName 'sql.connection.trustcert' -Value $true -Register`

**Comment by SQLCanuck** [comment] 2021-08-02 02:09
@potatoqualitee to give you an update, we also make use of the SqlServerDsc module.  However, the updated Microsoft.Data.SqlClient provided in DbaTools creates a dependency conflict.  Which means the use of localhost references in DSC code also now no longer works for SQL Server.  This makes it a much larger problem, as it would mean creating a separate DSC for every server (to remove localhost references) rather than maintaining a single DSC for all servers.  The only solutions I can think of currently are to add "localhost." to the certificate SAN, revert to an older DbaTools or not enforcing encrypted communications.

**Comment by potatoqualitee** [comment] 2021-08-02 09:35
Yeah, all 3 seem like reasonable solutions. I'm not sure when Microsoft will be moving to Microsoft.Data for the PowerShell things. You may want to file an issue on the SqlServerDsc repo. One big issue, though, is that the SqlServer module is still on System.Data, so I imagine they won't be very motivated to migrate until at least the SqlServer module is updated.
