### ISSUE TITLE
[Bug] ][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types

### ISSUE THREAD

**Issue by KrishnP92** [sqlcollaborative/dbatools#6897] opened 2020-10-01 15:14 UTC
#### Host used

- [1] powershell.exe
- [1] ISE
- [0] VS Code
- [0] Other (please specify)

#### Errors Received

```
Test-DbaRepLatency -sqlinstance mysqlinstance 
WARNING: [16:07:28][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:28][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:28][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:28][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:28][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:28][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:29][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:29][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:29][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:29][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:29][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:29][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:29][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
WARNING: [16:07:29][Connect-ReplicationDB] Could not load replication libraries | Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
New-Object : Cannot find type [Microsoft.SqlServer.Replication.ReplicationServer]: verify that the assembly containing this type is loaded.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:73892 char:26
+ ... repServer = New-Object Microsoft.SqlServer.Replication.ReplicationSer ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
 
The property 'ConnectionContext' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:73895 char:13
+             $repServer.ConnectionContext = $server.ConnectionContext. ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
WARNING: [16:07:29][Test-DbaRepLatency] Error occurred while establishing connection to wlr3-01 | Cannot bind argument to parameter 'SqlInstance' because it is null.

$Error[0]|Select *

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Cannot bind argument to parameter 'SqlInstance' because it is null. ---> System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'SqlInstance' because it is null.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : InvalidData: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Test-DbaRepLatency,Stop-Function
ErrorDetails          : Cannot bind argument to parameter 'SqlInstance' because it is null.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 84071
                        at Test-DbaRepLatency<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 73905
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```
PowerShell Version        : 5.1.14409.1018
dbatools latest installed : 1.0.121
Culture of OS             : en-GB
```

#### SQL Server:

```sql
Microsoft SQL Server 2012 (SP4-GDR) (KB4532098) - 11.0.7493.4 (X64)   Dec 24 2019 19:33:24   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor) 
```

```sql
us_english

```

**Comment by KrishnP92** [comment] 2020-10-01 15:17
I get the error as above when running from certain servers (from, not against). The servers unable to run the command are running windows server 2012 & 2016, where as I can run without issue on Windows 10 and Windows Server 2019. The install was completed online, rather than offline

**Comment by andreasjordan** [comment] 2021-06-05 14:04
Sorry, has been lost from sight. Is this still a problem with the current version?

**Comment by andreasjordan** [comment] 2021-06-09 17:12
I think this is duplicate of #6548, so I will close this one.

**Closed by andreasjordan** 2021-06-09 17:12 UTC
Labels: bugs_life, waiting for user
