### ISSUE TITLE
Unable to find type [sqlcollective.dbatools.dbaSystem.MessageLevel].

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#1047] opened 2017-04-14 08:20 UTC
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [ x] *bug*:

## System Details

- Operating system name and version: Windows 10
- Output from `$PSVersionTable`:

```
Name                           Value                                                       
----                           -----                                                       
PSVersion                      5.1.14393.953                                               
PSEdition                      Desktop                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                     
BuildVersion                   10.0.14393.953                                              
CLRVersion                     4.0.30319.42000                                             
WSManStackVersion              3.0                                                         
PSRemotingProtocolVersion      2.3                                                         
SerializationVersion           1.1.0.1  
```

- Output of dbatools version:

```
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                   
---------- -------    ----                                ----------------                                                                   
Script     0.8.945    dbatools                            {Start-SqlMigration, Copy-SqlDatabase, Copy-SqlLogin, Copy-SqlServerAgent...}      


```

- SQL Server version for source/target

this occurs when running test-dbaidentityusage against a 2003 server (as it calls the Stop-Function)

#### Example:
Removed all and any dbatools folders from psmodulepath (;-) ) Install-module dbatools

Test-DbaIdentityUsage -SqlInstance sql2005ser2003

Get the error

3. Received following error

Unable to find type [sqlcollective.dbatools.dbaSystem.MessageLevel].
At line:111 char:9

### Import - Attach dbatools logs
No Can do!! - But error.xml attached
get-dbaconfig
Unable to find type [sqlcollective.dbatools.Configuration.Config].
At line:52 char:5
+     [sqlcollective.dbatools.Configuration.Config]::Cfg.Values | Where ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (sqlcollective.d...guration.Config:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 

[error.zip](https://github.com/sqlcollaborative/dbatools/files/921733/error.zip)

**Comment by FriedrichWeinmann** [comment] 2017-04-14 13:13
Heya, thanks for the error report.
I've read the logs and there's something rotten in the state of Denmark:

The library never loaded for you.

```
Add-Type : Object reference not set to an instance of an object.
At line:4035 char:9
+         Add-Type @paramAddType
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.AddTypeCommand
```

Now, why the import worked at all is a bit of a mystery - it really shouldn't be doing anything of the sort. On the other hand, it also shouldn't have this error, it's ... fairly implausible, really. The error-log proves it, mind you, so I don't doubt it, it's just ... so totally off the probability-charts ...

Would you mind running this command:
`([appdomain]::CurrentDomain.GetAssemblies() | Where-Object FullName -match "Microsoft\.Management\.Infrastructure").Location | Measure-Object`
And posting the results?

I'll continue working on this tonight, gotta hit the road right now, sorry.

**Comment by FriedrichWeinmann** [comment] 2017-04-16 00:40
Hi,

that is ... odd - there really should only be one count. It maybe that my filter is not good enough. I've updated it a little and ran it against my system: Still working as desired on my end. Can you run this?

`([appdomain]::CurrentDomain.GetAssemblies() | Where-Object FullName -match "^Microsoft\.Management\.Infrastructure, |^System\.Numerics, " | Where-Object Location).Location`

This should now return exactly two paths. And this:

`([appdomain]::CurrentDomain.GetAssemblies() | Where-Object FullName -match "^Microsoft\.Management\.Infrastructure, |^System\.Numerics, " | Where-Object Location).Location | Measure-Object`

Should have a count of 2.

Cheers,
Fred

**Comment by potatoqualitee** [comment] 2017-04-18 09:12
Hey @FriedrichWeinmann - I had an issue with an import of a new version. Is it possible to add something to the psm1 that forcibly removes the old libraries from memory before reimporting?

**Comment by FriedrichWeinmann** [comment] 2017-04-18 12:24
Heya @potatoqualitee ,

no, it isn't. Simply put, _there is no way_ to remove a library from memory, you _have_ to start a new process. C# Processes in general are capable of that, but not PowerShell.

That's why the best we can do is write a warning (which the current versions should) on version mismatch and recommend a restart of the console.

**Comment by potatoqualitee** [comment] 2017-04-18 12:36
Makes sense! I didn't get a warning, just "type doesn't exist" or something like that. Am using the master branch.

**Comment by FriedrichWeinmann** [comment] 2017-04-18 12:38
Yeah,the warning isn't in master yet.
I think it's still hanging in https://github.com/sqlcollaborative/dbatools/pull/1050
Kinda lost track where that feature went

**Comment by SQLDBAWithABeard** [comment] 2017-04-18 12:40
OK, so that suddenly gave a chink in my lickle brain

I can reproduce this - I have VSCode open and import-module all fine. I then open ISE and boom error. This is an issue for me as whilst I generally code in VSCode these days, I will often present in Code with ISE open just in case, or if I was presenting in ISE I would have a backup Tab open with my demos just in case

If I have two ISE tabs open and try ot import into both I get the error in the second one

A - Does that make sense
B - Is that fixable?

**Comment by potatoqualitee** [comment] 2017-04-18 12:40
Merged 👍

**Comment by FriedrichWeinmann** [comment] 2017-04-18 12:44
I'll game it out on the ISE. MIght have the time right now, will be on the road for most of the day though :(

**Comment by FriedrichWeinmann** [comment] 2017-04-18 12:50
Nope, couldn't reproduce your issue on garbo. Seriously, can you reproduce the thing and run the two commands I posted, then screenshot the results?

**Comment by SQLDBAWithABeard** [comment] 2017-04-18 13:14
Always just 2 results 

C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Management.Infrastructure\v4.0_1.0.0.0__31bf3856ad364e35\Micr
osoft.Management.Infrastructure.dll
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll

Attached screen cast


[dbatools error .zip](https://github.com/sqlcollaborative/dbatools/files/929746/dbatools.error.zip)

**Comment by FriedrichWeinmann** [comment] 2017-04-18 13:30
That's a serious case of odd.
Thanks for the screencast. The behavior doesn't really make sense but it's good to know. I'll try to repro - I've got a straight tutorial on how to now (said video) - and hopefully I can eliminate it.
I really want to understand what's happening here - reliability is one of my highest goals and unexplained oddities like this don't help in that regard.
I'll try to get back to you tonight with the results.

**Comment by SQLDBAWithABeard** [comment] 2017-04-18 13:42
You are more than welcome my friend. I too would like to get it resolved as I have 1,2,3 many presentations including dbatools in the next month!!!

**Comment by FriedrichWeinmann** [comment] 2017-04-18 22:23
Alright, I've fully recreated the environment in the dbatools lab (exactly the same powershell build on exactly the same .NET patch level. Same module version). Tried it on x64 and x86, just in case.
It just works.
Drilling down the error xml provided by you, Add-Type is throwing an error it shouldn't be able to throw (I've tried everything I could to make it produce the same error - in vain).

By my own logic, there is no reasonable way for this to fail.
The only thing I can think of right now would be to check your system files and .NET health (There's a good fixit for the latter and sfc.exe for the former)

**Comment by potatoqualitee** [comment] 2017-04-18 22:27
are you trying with the ISE, @FriedrichWeinmann? I've found it to be incredibly ... painful and unstable.

**Comment by SQLDBAWithABeard** [comment] 2017-04-20 05:25
ok - sfc \scannow found 0 errors and so did the .NET fixit and the error is still there :-(

**Comment by wsmelton** [comment] 2017-04-20 13:43
Just as a reference for this and future....

The Integrated Console for PowerShell that is created in VS Code by the PowerShell Extension is not the same host process as running PowerShell. That is a custom built console host the extension is building, they referenced in the release of it that the experience falls between the PowerShell ISE and PowerShell.exe.

I would also recommend updating to the latest module and verifying if the error still exist. I used to get an error in VS Code around one of those types not loading but no longer. I also can't reproduce your issue on my Windows 10 machine, at least with 0.8.947 version of the module.

**Comment by FriedrichWeinmann** [comment] 2017-04-20 14:35
Well, taking things in order:
 - Yes, I tried with ISE. The ISE is something I myself never use and frequently curse, but in order to try and reproduce this, I did. Couldn't. Would work right away.
 - Then I'm officially stumped. I cannot reproduce this and your console is erroring at a location and in a way that should not be possible. I can throw around some more guesses, such as uninstalling the latest updates and reinstalling them again, but that's it. Hm ... one final thing I could think of - it seriously should never be the issue, but it's something easily done - you could edit your library.ps1 and convert the splatting into a regular cmdlet call. Shouldn't be the cause, likely won't help ... as I said, I'm effectively reduced to guessing, sorry :(. A possible workaround for the presentations would be to set up a VM for them. Or a complete reinstall. The script code is sound anyway, so it can really only be a local environment issue. Hm, maybe in your profile something or do you have PowerShell policies? Anything that makes it non-standard?
 - Yepp, the different hosts have always been a lot of fun. One of the reasons I use the default powershell.exe in my toolkit is to avoid issues with that. The main reason, really.

**Comment by wsmelton** [comment] 2017-04-20 14:42
Oh, another thing to check might be AV software. I watched some security stuff on PowerShell that Lee Holmes presented earlier this month. In that video he stated that Windows 10 offers up the ability for AV software to now see what is being done within PowerShell.exe calls, so if something "malicious" is occurring they can capture it and possibly prevent it. Just a shot in the dark, but try turning your AV off and repeat your test.

**Comment by FriedrichWeinmann** [comment] 2017-04-20 15:28
True, that might be worth checking. It's not the right exception for direct AV intervention through the V5 security integration, but it may be the/an issue anyway. Not likely given the symptoms, but at least I am at the grasping-for-straws phase.

**Comment by FriedrichWeinmann** [comment] 2017-04-27 20:09
Alright, managed to reproduce the exception, _should_ be fixed in the current development build. Can you confirm that, @SQLDBAWithABeard ?

**Comment by SQLDBAWithABeard** [comment] 2017-04-28 14:31
Confirmed - build 0.8.950 in the dev branch does not throw the error and things work as expected (in a quick test of presentation demos :-)

**Comment by FriedrichWeinmann** [comment] 2017-04-28 16:21
Excellent, thanks for the confirm. In this case I shall shrug at the PowerShell team and what they did there that something like that can happen - shouldn't have, really - but shall be satisfied with the workaround.
I'll close this issue as resolved. Should it ever happen again, please absolutely tell me about it (Ideally open this case again and write me directly on Slack, just to be sure)

**Closed by FriedrichWeinmann** 2017-04-28 16:21 UTC
Labels: bug
