### ISSUE TITLE
Start-SqlMigration SetSourceReadOnly doesn't work

### ISSUE THREAD

**Issue by Purclot** [sqlcollaborative/dbatools#630] opened 2017-02-02 18:07 UTC
### System Details

- Operating system name and version: Windows Server 2012 DataCenter Evaluation
- Output from `$PSVersionTable`:

```
Name                              Value                           
----                           -----                           
PSVersion                 5.0.10586.117                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                       
BuildVersion             10.0.10586.117                                                
CLRVersion                     4.0.30319.42000                                               
WSManStackVersion              3.0                                       
PSRemotingProtocolVersion      2.3                                      
SerializationVersion           1.1.0.1            
```

- Output of dbatools version:

```Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      694    -1      
```
- SQL Server version for source/target
2008R2/2012; 2016

### Steps to Reproduce

`Start-SqlMigration -Verbose -Source Server2\DEV2012_1 -Destination Server2\DEV2016_1 -DetachAttach -Reattach -SetSourceReadOnly -Force`

### Action Results
```
######### Database: ReportServer$DEV2008_1 #########
VERBOSE: Checking for accessibility
VERBOSE: Checking Availability Group status
Started: 02/02/2017 14:10:16
Setting database to read-only
Update-SqldbReadOnly : Could not change readonly status for ReportServer$DEV2008_1 on Server2\DEV2008_1
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.8.694\functions\Copy-SqlDatabase.ps1:1102 char:17
+ ...            $result = Update-SqldbReadOnly $sourceserver $dbname $true
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Update-SqlDbReadOnly
Update-SqldbReadOnly : Could not change readonly status for ReportServer$DEV2008_1 on Server2\DEV2008_1
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.8.694\functions\Copy-SqlDatabase.ps1:1102 char:17
+ ...            $result = Update-SqldbReadOnly $sourceserver $dbname $true
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Update-SqlDbReadOnly

WARNING: Couldn't set database to read-only. Aborting routine for this database
######### Database: ReportServer$DEV2008_1TempDB #########
```

### Expected Results

1. The migration works fine, only the Database: ReportServer$MySqlServer (tested with 2008R2 and 2012) will not be set "Read-Only" on the source server. 

It's not a big deal for me at all, maybe just try to correct the "try/catch" block in the function: Copy-SqlDatabase?

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

Thanks for your comments
Purclot Avignon

**Comment by wsmelton** [comment] 2017-02-02 18:38
@Purclot The error you got was by design, the command was not able to mark the database as read-only. 

The only thing being done when you use `-SourceReadOnly` is an internal function is called `Update-SqlDbReadOnly` that is simply executing the T-SQL statement: `ALTER DATABASE [$dbname] SET READ_ONLY WITH NO_WAIT`. That statement failed to execute for that database for some reason and therefore did not migrate that database.

**Comment by Purclot** [comment] 2017-02-02 18:48
@wsmelton: thanks. I know what happend was only not sure if it was intended. But: the database was successfully migrated(!), only  not set read-only on source server - what is completely fine with me.

**Comment by wsmelton** [comment] 2017-02-02 18:56
AH, ok. Did not catch that...we may need to address that then. Would you expect it if it could NOT be set to read-only that it should not be migrated? 

If that is the case we can likely fix that pretty easily.

**Comment by Purclot** [comment] 2017-02-02 19:14
@wsmelton: 1) the problem emerges only with the ReportServer$Instance-DB (is created during the sql installation process). 2) I'd simply change the try/catch block saying "hey, the ReportServer-DB was imported but not set read-only on the source". Maybe some un-experienced PowerShell-User seeing the error message get the impression "all" went wrong..

**Comment by potatoqualitee** [comment] 2017-07-23 17:16
Thanks for the report!

I just fixed this and it will be included in the next release which is likely within the next 24 hours

![image](https://user-images.githubusercontent.com/8278033/28501390-47c4cad6-6fdb-11e7-9309-32374d55b864.png)

![image](https://user-images.githubusercontent.com/8278033/28501392-58b2d130-6fdb-11e7-97f1-ba86701d5dc1.png)

Sorry it took so long 💔

**Closed** 2017-07-23 17:33 UTC
Labels: Type: Bug
