### ISSUE TITLE
Export-SqlLogin outputs incorrect results

### ISSUE THREAD

**Issue by arvindravish** [sqlcollaborative/dbatools#298] opened 2016-11-02 00:33 UTC
When exporting multiple logins, the results script is incorrect 
 Export-SqlLogin -SqlServer server -Logins login1, login2

Create Database user commands look duplicated for the same user

**Comment by wsmelton** [comment] 2016-11-02 00:55
Can you provide more details around version of SQL Server, and possible an example for each login you were trying to export?

As well, how was the outputted script incorrect, just the fact that it appeared duplicated?

**Comment by cjsommer** [comment] 2016-11-02 01:58
I can verify this issue. I tried on SQL 2012 with 3 logins on my test machine. The problem is around the code block that creates the CREATE USER statement. It would always print the CREATE USER statement for the first alphabetically listed login for me.

Pretty sure the problem is around line 325 and the lop that follows it.

`if ($databases.length -eq 0) { $databases = $sourcelogin.EnumDatabaseMappings() }`

The first time through, $databases is -eq 0 so it does the enumeration and populates $databases for the first login. For the next user, $databases is no longer -eq 0 so it uses the same $databases as the first login for each remaining user. I was able to resolve this by adding a $databases = $null after line 377. This ensures that $databases is re-populated for each iteration of that loop.

I don't think this should have any other impact but I'm not sure. I'm sure Chrissy will take a look at it as well. HTH

**Comment by PowerDBAKlaas** [comment] 2016-11-04 15:34
Maybe I'm missing something, but it seems this is the only line $databases is set.
Why is the `if ($databases.length -eq 0)` needed?
As @cjsommer says, the first iteration $databases.length is 0, the next iterations it is not.
I think the if statement can be removed.
If it shouldn't be, `if ($databases)` would be simpler, and as @cjsommer suggested, setting it to $null also solves the problem. But I do prefer this just before the real assignment, instead of the end of the foreach block.

**Comment by ctrlbold** [comment] 2016-11-04 15:36
if ($databases) is not only simpler, but prettier. Unfortunately, I haven't found it to work as expected across every environment, so I tend to be more explicit and specify length. Also, not comment on the databases part because I don't have time to look today. Carry on, please ;)

**Comment by cjsommer** [comment] 2016-11-04 15:46
@PowerDBAKlaas I thought about that after I posted my first look into this. I also thought it might make sent to take the if ($databases.length -eq 0) check out completely. I just didn't know if that had any other impact at the time.

**Comment by ConstantineK** [comment] 2016-11-27 15:10
This should be fixed in #339 if it is merged.

**Closed** 2016-12-09 03:01 UTC
