### ISSUE TITLE
Please add a -NoProgress switch for Update-DbaInstance

### ISSUE THREAD

**Issue by mikepetrak** [sqlcollaborative/dbatools#6702] opened 2020-08-03 15:51 UTC
Hi everyone,

Can you please add a -NoProgress switch for Update-DbaInstance so I can run it in a Windows Scheduled task? See Import-DbaCsv that has this switch.

Thanks for the tip, @wsuhoey!

Mike Petrak

**Comment by wsmelton** [comment] 2020-08-03 16:03
We don't control that via a switch in the command. You would control this at the session level for PowerShell using `$ProgressPreference`.

More information on this can be found in the docs: [about_Preference_Variables](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables)

**Comment by mikepetrak** [comment] 2020-08-03 16:04
Thanks, @wsmelton . I was considering that too from https://thinkpowershell.com/hide-powershell-progress-bars/ .

**Comment by wsuhoey** [comment] 2020-08-03 16:36
There is one command that has -NoProgress via switch in our commands:

https://github.com/sqlcollaborative/dbatools/blob/development/functions/Import-DbaCsv.ps1

See lines 123-124 which shows the parameter in CBH.
See line 276 which identifies it as a switch.
See lines 618-625 which tells the code how to suppress it.

    .PARAMETER NoProgress
    The progress bar is pretty but can slow down imports. Use this parameter to quietly import.
    ...
    [switch]$NoProgress,
    ...
                        # Add rowcount output
                        $bulkCopy.Add_SqlRowsCopied( {
                                $script:totalrows = $args[1].RowsCopied
                                if (-not $NoProgress) {
                                    $timetaken = [math]::Round($elapsed.Elapsed.TotalSeconds, 2)
                                    Write-ProgressHelper -StepNumber 1 -TotalSteps 2 -Activity "Importing from $file" -Message ([System.String]::Format("Progress: {0} rows in {2} seconds", $script:totalrows, $percent, $timetaken)) -ExcludePercent
                                }
                            })

Since the code in `Update-DbaInstance` does use `Write-ProgressHelper`, similar logic could be incorporated.

**Comment by wsmelton** [comment] 2020-08-03 20:09
Whether the import command uses it or not is irrelevant, and that command will be fixed to remove the parameter as well.

**Comment by wsuhoey** [comment] 2020-08-03 21:26
I don't understand, why remove the parameter `-NoProgress` from `Import-DbaCsv`? @potatoqualitee added it to the command with the command's re-work. I don't understand why you are so against it?

**Comment by wsmelton** [comment] 2020-08-03 21:37
Why add additional overhead for code testing and management when the proper mechanism for managing progress output is built into every version of PowerShell?

**Comment by wsuhoey** [comment] 2020-08-04 23:27
@mikepetrak confirmed that he was able to get `Update-DbaInstance` to work in a scheduled task by using `$ProgressPreference`. So I concede about both adding and removing the `-NoProgress` parameter.

**Closed** 2020-08-04 23:27 UTC
