### ISSUE TITLE
Export-DbaXESessionTemplate - adding AutoStartUp parameter to export

### ISSUE THREAD

**Issue by mikedavem** [sqlcollaborative/dbatools#3690] opened 2018-06-18 08:10 UTC
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

Export-DbaXESessionTemplate doesn't export AutoStartUp value. 

I would like to export one XE session with AutoStartUp value = True but Export-DbaXESessionTemplate doesn't export it correctly. After further investigations it seems the issue comes from **[Microsoft.SqlServer.Management.XEvent.XEStore]::SaveSessionToTemplate($xes, $filename, $true)** which not reports this session parameter into the XML file.

### Latest version of dbatools as of writing

Version 0.9.347

Thanks

**Comment by andreasjordan** [comment] 2021-05-20 12:25
If the problem is inside of [Microsoft.SqlServer.Management.XEvent.XEStore]::SaveSessionToTemplate, then I don't see how we can help here. 
Have you tried to use `Export-DbaXESession`?

I will close this for now, but you can reopen it if you have further questions.

**Closed by andreasjordan** 2021-05-20 12:25 UTC
Labels: Feature
