### ISSUE TITLE
[Bug] Export-DbaDbRole throwing String cannot be of zero length. error

### ISSUE THREAD

**Issue by kewlhand** [sqlcollaborative/dbatools#6101] opened 2019-10-10 17:46 UTC
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                                                  
----                           -----                                                                                                                                                  
PSVersion                      5.1.17763.592                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                
BuildVersion                   10.0.17763.592                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                                




#### dbatools Module version:


Name    : dbatools
Path    : C:\Users\<username>\<ODFB path name>\Documents\WindowsPowerShell\Modules\dbatools\1.0.52\dbatools.psd1
Version : 1.0.52

Name    : dbatools
Path    : C:\Users\<username>\<ODFB path name>\Documents\WindowsPowerShell\Modules\dbatools\1.0.38\dbatools.psd1
Version : 1.0.38

```

#### SQL Server: 

```sql
/*Microsoft SQL Server 2017 (RTM-CU16) (KB4508218) - 14.0.3223.3 (X64)   Jul 12 2019 17:43:08   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: )  */
```

#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Errors Received

 System.Management.Automation.MethodInvocationException: 
                        Exception calling "Replace" with "2" argument(s): "String cannot be of zero length.
                        Parameter name: oldValue" ---> System.ArgumentException: String cannot be of zero length.
                        Parameter name: oldValue
                           at System.String.ReplaceInternal(String oldValue, String newValue)
                           at System.String.Replace(String oldValue, String newValue)
                           at CallSite.Target(Closure , CallSite , Object , String , String )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                        funcContext, Exception exception)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
                           --- End of inner exception stack trace ---
TargetObject          : SERVERNAME
CategoryInfo          : ConnectionError: (SERVERNAME:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Export-DbaDbRole,Stop-Function
ErrorDetails          : String cannot be of zero length.
                        Parameter name: oldValue
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.52\allcommands.ps1: line 81320
                        at Export-DbaDbRole<Process>, C:\Users\username\Documents\WindowsPowerShell\Modules\dbatools\1.0.52\allcommands.ps1: line 12118
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```




#### Steps to Reproduce

<!--
If you have confirmed this issue can be reproduced, please provide the exact steps (T-SQL, PowerShell, ext)
-->
Export-DbaDbRole -Database DatabaseName -SqlInstance ServerName -FilePath C:\test\test.sql  -Role Public
#### Expected Behavior

<!--
What did you expect to happen?

-->
generate a file with a TSQL Script to recreate the role with associated permissions.

#### Actual Behavior

<!--
What happened?

-->
No file was generated and a warning was produced

**Comment by jpomfret** [comment] 2019-10-15 18:40
I am not able to replicate this on SQL Server 2017 and dbatools version 1.0.53 (not exact match for issue). I did notice that you have two module versions listed, can you try a new powershell session then `import-module dbatools -RequiredVersion 1.0.52` make sure get-module only lists one dbatools version and then retest? 

I'm wondering if it is broken in the older version you have there.

**Comment by kewlhand** [comment] 2019-10-16 12:45
Jess, I am still able to reproduce the issue, against various sql server versions from 2008R2 up.
![DbaTools Error](https://user-images.githubusercontent.com/40072334/66920352-17628480-eff1-11e9-8198-aa9acb6f308d.png)

The error happens when I'm trying to export all roles as well.

![DBAToolsError_NoRoleSpecified](https://user-images.githubusercontent.com/40072334/66920353-17628480-eff1-11e9-9f4a-19e61c5d14d4.png)

**Comment by kewlhand** [comment] 2019-10-16 13:03
Also, I just installed the 1.0.53 version and I am still able to repro the issue.
![DbaToolsError_1 0 53](https://user-images.githubusercontent.com/40072334/66921763-d4ee7700-eff3-11e9-8a22-8fe5b00efa25.png)

**Comment by wsmelton** [comment] 2019-10-16 14:15
What happens if you run `Get-DbaDbRole .. -Role Public` ?

**Comment by sqllensman** [comment] 2019-10-26 06:34
The reason it is difficult to reproduce is because it will not occur if the code is run directly against the Functions code.
The error is due to some issue creating the allcommands.ps1 file.


This file is NOT a faithful representation of the code inside the individual function code.
Aside from removing the comments it is also stripping out some code that was being used to effectively parameterise the SQL commands used within this Function

In the Export-DbaDbRole.ps1 code in functions directory the $roleSQL variable is assigned as:

$roleSQL = "SELECT
                        N'<#RoleName#>' as RoleName,

and $userSQL

$userSQL = "SELECT roles.name as RoleName, users.name as Member
                    FROM sys.database_principals users
                    INNER JOIN sys.database_role_members link
                        ON link.member_principal_id = users.principal_id
                    INNER JOIN sys.database_principals roles
                        ON roles.principal_id = link.role_principal_id
                    WHERE roles.name = N'<#RoleName#>'"

The RoleName is effectivly being parameterised as <#RoleName#>

This is then configured via
$query = $roleSQL.Replace('<#RoleName#>', "$($dbRole.Name)")
and 
$query = $userSQL.Replace('<#RoleName#>', "$($dbRole.Name)")

In the allcommands.ps1 file these code lines appear as:

        $roleSQL = "SELECT
                        N'' as RoleName,

        $userSQL = "SELECT roles.name as RoleName, users.name as Member
                    FROM sys.database_principals users
                    INNER JOIN sys.database_role_members link
                        ON link.member_principal_id = users.principal_id
                    INNER JOIN sys.database_principals roles
                        ON roles.principal_id = link.role_principal_id
                    WHERE roles.name = N''"

$query = $roleSQL.Replace('', "$($dbRole.Name)")

$query = $userSQL.Replace('', "$($dbRole.Name)")


This same error is affecting the command Export-DbaServerRole and possibly other commands that may be using the pattern <#Name#> as a pseudo parameter.

The fix for this would require some other pattern of code pattern to be used to parametrise queries.
I am happy to take guidance on this as it requires a convention that will not be stripped out by process that creates the allcomands.ps1

**Closed** 2019-10-28 05:11 UTC
