### ISSUE TITLE
SMO assemblies prevents dbatools from loading on machine with no SSMS installed

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1290] opened 2017-05-21 04:05 UTC
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [X] *bug*:

With the ability to now install the sqlserver module separate from SSMS media this alters how the SMO assemblies can be imported for the module. This [line of code](https://github.com/sqlcollaborative/dbatools/blob/development/dbatools.psm1#L26) in the psm1 file is the culprit that has to be dealt with since the assemblies for SQL Server are no longer loaded into the GAC.

The method to load SMO that I can figure out is to go by the path: 
```powershell
add-type -Path 'C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.0.17099\Microsoft.SqlServer.Smo.dll'
```

Would have to also include any function that references or tries to load a specific namespace as well. Example of this would be `Get-DbaXEventSession`.

## System Details
- Operating system name and version: Window Server 2012 R2
- Output from `$PSVersionTable`: 5.0
- Output of dbatools version: 0.8.957
- SQL Server version for source/target: SQL Server 2014

## Steps to Reproduce
1. "New" server with no SSMS or any part of SQL Server installed.
2. Run `Install-Module sqlserver`
3. Run 'Install-Module dbatools`
4. Run `Import-Module dbatools`
5. Received following error
```PS C:\Windows\system32> ipmo dbatools
ipmo : Can't load SMO assemblies. You must have SQL Server Management Studio installed to proceed.
At line:1 char:1
+ ipmo dbatools
+ ~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Can't load SMO ...led to proceed.:String) [Import-Module], RuntimeExc
   eption
    + FullyQualifiedErrorId : Can't load SMO assemblies. You must have SQL Server Management Studio installed to proce
   ed.,Microsoft.PowerShell.Commands.ImportModuleCommand
```
![image](https://cloud.githubusercontent.com/assets/11204251/26281048/d0d03800-3daf-11e7-907e-2232917bd3cb.png)

## Expected Results
1. "New" server with no SSMS or any part of SQL Server installed.
2. Run `Install-Module sqlserver`
3. Run 'Install-Module dbatools`
4. Run `Import-Module dbatools`
5. Module imports.

**Comment by potatoqualitee** [comment] 2017-05-21 10:48
Not a bug, total feature ;) It's working as intended. 

Adding dynamic support for SqlServer assemblies would be a lil bit tricky - the path would have to be figured out dynamically because `(Get-Module sqlserver).ModuleBase` won't work without importing the module. The module does load in 0.5 seconds which isn't bad, but it's also 400ms longer than importing the assemblies and right now, we're hurting on import speeds. That should be resolved in not this release but the next.

**Comment by wsmelton** [comment] 2017-05-21 17:45
This works fine for me: `(Get-Module sqlserver -ListAvailable).ModuleBase`

![image](https://cloud.githubusercontent.com/assets/11204251/26286142/5834036c-3e23-11e7-81c2-00046c345494.png)

**Comment by potatoqualitee** [comment] 2017-05-21 20:39
119ms, not bad!

**Comment by potatoqualitee** [comment] 2017-07-23 19:28
fixed!

**Closed by potatoqualitee** 2017-07-23 19:28 UTC
Labels: Type: Enhancement
