### ISSUE TITLE
Rename-DbaDatabase, new function

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1775] opened 2017-07-20 08:58 UTC
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

------
In the need of something that renames a database, optionally renaming underlying files too.
PS: remember to suggest to backup master afterwards

**Comment by potatoqualitee** [comment] 2017-07-20 13:30
awesome!

**Comment by potatoqualitee** [comment] 2017-07-23 13:24
Dupe of #289 which contains more info

**Closed by potatoqualitee** 2017-07-23 13:24 UTC
Labels: awesome_sauce
