### ISSUE TITLE
Add-DbaAgListener parameter for Listener Name

### ISSUE THREAD

**Issue by timrhomberg** [sqlcollaborative/dbatools#5000] opened 2019-01-23 15:39 UTC
---
name: Feature request
about: A extra Parameter for the Listener Name in Add-DbaAgListener 

---

### Summary of new feature

For the Function Add-DbaAgListener is at moment not possible to define a Listener Name. It takes every time the Name from the availability Group, but i have different names for the availability Group and the listener. So i want a extra Field to define a Listener Name.

**Comment by wsmelton** [comment] 2019-01-23 16:48
https://github.com/sqlcollaborative/dbatools/blob/b912f7e04738377f59bfdb314dbdfc1dff5a437a/functions/Add-DbaAgListener.ps1#L94-L100

We actually have code to handle passing in a name it was just missed adding as a parameter itself. SO quick fix for this will be to just add in `[string]$Name` to the parameter block and help. Then the test file will also need to have this parameter added.

**Comment by timrhomberg** [comment] 2019-01-23 18:41
Thank You for your quick Response. Can you tell me by when this will be implemented?

**Comment by wsmelton** [comment] 2019-01-23 19:04
No sure can't....it will likely be this week but can't promise anything.

**Comment by wsmelton** [comment] 2019-01-26 16:31
So @potatoqualitee we will have to consider how we add the name as the actual parameter. This has the same issue with piping AGs in on how to handle each AG with a name. 

For piping support we would have to have the name mapped to the AG, so accept a hashtable input for something like `-ListenerToAg` or something. Otherwise the listener name can only be provided when you are working with one AG (which verifies if more than one AG is provided, we will have to make it fail).

**Comment by wsmelton** [comment] 2019-01-27 03:16
The problem is the command accepts multiple AGs. We need to update the command to only accept one AG at a time. You would not want to create a listener with the same name and IP on all the AGs of a given instance; though I don't think that is even allowed.

**Closed** 2019-03-22 11:08 UTC
Labels: bugs_life
