### ISSUE TITLE
Copy-SqlPolicyManagement - Copies Conditions but not Policies

### ISSUE THREAD

**Issue by CharterSteel** [sqlcollaborative/dbatools#1049] opened 2017-04-14 17:22 UTC
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [X ] *bug*:

## System Details

Operating system name and version:
Windows Server 2016 Standard
WindowsBuildLabEx : 14393.953.amd64fre.rs1_release_inmarket.170303-1614
WindowsCurrentVersion : 6.3

Output from $PSVersionTable:
```
Name Value

PSVersion 5.1.14393.953
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.14393.953
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
```

- Output of dbatools version:
```
Script     0.8.945    dbatools 
```
- SQL Server version for source/target
13.0.4202.2

#### Example:
1. Before running command I manually delete Policies and Conditions on target. I verify no entries in syspolicy tables by running:
```sql
select * from syspolicy_policies where is_system  = 0
select * from syspolicy_policies_internal where is_system =0
select * from syspolicy_conditions where is_system =0
select * from syspolicy_conditions_internal where is_system =0
select * from syspolicy_object_sets where is_system =0  
select * from syspolicy_object_sets_internal where is_system =0 
```
2. I run the following:
`Copy-SqlPolicyManagement -Source vmsk1 -Destination vmsk2  -Verbose -Force`

3. I receive no errors, and the conditions are copied. However the policies are not copied. I have attached the verbose output
[CopyPolicyVerboseOutput.txt](https://github.com/sqlcollaborative/dbatools/files/922557/CopyPolicyVerboseOutput.txt)

4. It appears the conditions are being created twice. I notice the policy creation code includes dependencies, so that may be why.

### Import - Attach dbatools logs
No logs are created, presumably because no error is thrown

**Comment by potatoqualitee** [comment] 2018-12-17 19:16
no, bot, still open

**Comment by alevyinroc** [comment] 2019-02-24 18:36
Is this a duplicate of #1040 ?

**Comment by CharterSteel** [comment] 2019-02-25 14:16
I am working from memory of something almost two years ago, and my test configuration is long gone.

I do think they were two separate things, but maybe related. #1040 was about policy categories not being copied over which affected whether you could see the policies in SSMS.

#1049 was about conditions being copied, but not the policies. Categories not being copied over may be at the root of both, but not sure.

John Hise
Manufacturing Systems Intelligence Architect x2261

**Comment by potatoqualitee** [comment] 2019-03-18 01:15
yayyy closed

**Closed by potatoqualitee** 2019-03-18 01:15 UTC
Labels: bugs_life
