### ISSUE TITLE
[Bug] Invoke-DbaQuery doesn't close connections which it creates

### ISSUE THREAD

**Issue by Jaykul** [sqlcollaborative/dbatools#6210] opened 2019-11-19 16:49 UTC
#### PowerShell version:

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
#### dbatools Module version:
```
Name    : dbatools
Path    : C:\Users\joel\Documents\PowerShell\Modules\dbatools\1.0.72\dbatools.psd1
Version : 1.0.72
```

#### SQL Server: 

```
Microsoft SQL Azure (RTM) - 12.0.2000.8
   Oct 12 2019 22:46:48
   Copyright (C) 2019 Microsoft Corporation
```

### Report

As stated above, Invoke-DbaQuery creates connections but does not close them. At least when working against Azure SQL

Run any simple query against an Azure SQL database in a loop, **over 100 times**.

For what it's worth, the little I know: 
- the default Maximum size of an ADO.NET connection pool is 100
- I'm using SQL Azure. This bug doesn't seem to affect us when it's not Azure
- You can reproduce this just running `Connect-DbaInstance` in a loop if you don't call `.ConnectionContext.Disconnect()` on the connections it outputs.
- Adding the database name has no effect on _this_ bug.

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```

writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred                           because all pooled connections were in use and max pool size was reached. ---> System.Exception: Timeout expired.  The timeout period                           elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool                          size was reached. ---> System.Management.Automation.MethodInvocationException: Exception calling "Connect" with "0" argument(s):                                "Failed to connect to server TCP:ausc1-frg9sqlwttqrx.database.windows.net,1433." --->
                        Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server
                        TCP:ausc1-frg9sqlwttqrx.database.windows.net,1433. ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed                          prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size                             was reached.
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry,                                DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory                                 connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect(WindowsIdentity impersonatedIdentity)
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at Connect-DbaInstance<Process>(Closure , FunctionContext )
                           --- End of inner exception stack trace ---
                           --- End of inner exception stack trace ---
TargetObject          : ausc1-frg9sqlwttqrx.database.windows.net
CategoryInfo          : NotSpecified: (ausc1-frg9sqlwttqrx.database.windows.net:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaQuery,Stop-Function
ErrorDetails          : Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled                          connections were in use and max pool size was reached.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.22\allcommands.ps1: line 80172
                        at Invoke-DbaQuery<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.22\allcommands.ps1: line 44943
                        at <ScriptBlock>, <No file>: line 2
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

Literally run any query (against a *.database.windows.net server) in a loop over 100 times to exhaust the default connection pool size:

```PowerShell
foreach($c in 1..102) {
    Invoke-DbaQuery -SqlInstance "joel-test.database.windows.net" -SqlCredential $Credential -query "SELECT @@VERSION"
}
```

#### Expected Behavior

I should see 102 lines of 

```
Column1
-------
Microsoft SQL Azure (RTM) - 12.0.2000.8 ...
```

#### Actual Behavior

I see 100 lines of output, followed by two warnings after we exceed the limit of the pool and can no longer connect. E.g.:
```
WARNING: [16:39:17][Invoke-DbaQuery] Failure | Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have
occurred because all pooled connections were in use and max pool size was reached.
```

**Comment by awickham10** [comment] 2019-11-19 18:06
I stumbled across this today as well. It seems like this only happens when using the ```SqlCredential``` parameter.

**Comment by wsmelton** [comment] 2019-11-19 19:16
Passing a credential will also cause separate connection pools to be created..even if you are using the same credential.

**Comment by Jaykul** [comment] 2019-11-19 21:38
@wsmelton - I don't believe that is the case when passing a `-SqlCredential` to these cmdlets (as you can see more clearly from the repros on #6211). Despite the parameter name, dbaTools **never** creates a `SqlCredential` object. Instead, the `PSCredential` is put into the connection string (not added as a credential to the SqlConnection object) which means the connection string is exactly the same each time, so all the connections share **one pool** and use it up. If it created a different pool for each we might (eventually) run out of memory, but it wouldn't fill the pool up (so I would never have noticed that this was wrong). It would still be a bug that the connection's not closed, though 😉

@awickham10 as opposed to using a token? If you're using a token (or -Tenant or -AuthenticationType "AD Universal with MFA Support" or ClientSecret, etc. all of which result in generating a token), then you're in a far worse spot! As far as I can tell, this results in _generating a **new token** every time it has to reconnect_ (which is every time #6211). To do that it's making web requests and parsing json, etc. Then, on top of that, because you have a different token in the connection string every time, you create a new connection pool every time. If you're doing that, you should definitely be filing a bug 🤨 and should consider `-NonPooledConnection` since there's no point in the overhead of a connection pool if it's _impossible_ to reuse connections.

**Comment by awickham10** [comment] 2019-11-19 22:15
I was experiencing it using Windows authentication with domain joined computers.

**Comment by Jaykul** [comment] 2020-03-19 00:51
For what it's worth: I ended up having to pull in the code from [`Invoke-SqlCmd2`](https://github.com/sqlcollaborative/Invoke-SqlCmd2) to one of our modules to replace our need for `Invoke-DbaQuery` because of this and the related bug #6211 bug.  We found that it _also_ had **this** bug. I've fixed that and will send a PR to _that_ repo with the fix -- and some tests.

The root cause is that you're creating objects that are `IDisposable` and not calling `Dispose()` on them. One of them is holding on to the connection to the SQL Server. I'm pretty sure that will be the fix here, too:
- Dispose the SqlConnection (closing it isn't enough)
- Dispose the SqlCommand
- Dispose the SqlDataAdapter

**Comment by ahardin13** [comment] 2020-05-27 15:50
I encountered this while working on a script that runs multiple Invoke-DbaQuery commands inside a loop.  I am working around it by running the Clear-DbaConnectionPool command inside the loop.  So far it seems to be working without impact.

**Comment by iampeterdaniels** [comment] 2020-09-24 14:39
I believe I ran into this today.  Azure SQL DB target using SQL Auth/SqlCredentials.  Ran out of pool connections.  I'll try your Clear-DbaConnectionPool fix, @ahardin13

**Comment by niphlod** [comment] 2020-09-24 16:45
I think I nailed it but need further directions. 
Changing a small bit of Connect-DbaInstance makes this open one connection only

```
$oneconnect = Connect-DbaInstance -SqlInstance "mydb.database.windows.net" -SqlCredential $Credential

foreach($c in 1..102) {
   Invoke-DbaQuery -SqlInstance $oneconnect  -query "SELECT @@VERSION"
}
```
this is true even if you add `-Database master` on one or both.

Now, the hard part ..... Should repeated calls like this
```
Connect-DbaInstance -SqlInstance "mydb.database.windows.net" -SqlCredential $Credential
Connect-DbaInstance -SqlInstance "mydb.database.windows.net" -SqlCredential $Credential
Connect-DbaInstance -SqlInstance "mydb.database.windows.net" -SqlCredential $Credential
Connect-DbaInstance -SqlInstance "mydb.database.windows.net" -SqlCredential $Credential
```
create new connections or reuse them ?

Because it _seems_ that the fact that 
```
Invoke-DbaQuery -SqlInstance "mydb.database.windows.net" -SqlCredential $Credential -query "SELECT @@VERSION"
```
(irregardless of specifying the database) do ehxaust the connpool is due to the fact that repeated Connect-DbaInstance calls (with the same params) open new connections.

@wsmelton , @potatoqualitee : can you weight in ?

**Comment by wsmelton** [comment] 2020-09-24 17:08
What method could/would be used to see if a connection already existed for the SQL instance?

I feel that any call to Connect should be explicit to make another connection. However, I'd note that `Invoke-DbaQuery` only makes one call to `Connect-DbaInstance`.

**Comment by andreasjordan** [comment] 2020-09-24 19:56
I have my Azure DB up and running, so I played a little bit on this one here.

Every command does this:
```
$server = Connect-DbaInstance -SqlInstance $instance
```

And there are two different cases:
1. $instance is a full server smo
2. $instance is just a [DbaInstanceParameter]

In the first case, $instance is just transfered to $server and so no new connection is opened.
In the second case, a new full server smo is build and "sometimes" a new connection is opened.

So when is this "sometimes"?
In the non-Azure-world, a new connection is only opened when the connection string changes. So the dll manges the connections in pools. 
In Azure it looks different, as far as my tests show. Even when the connections string does not change, a new connection is opened.

Is there a way around? I tried the hints from @Jaykul (https://github.com/sqlcollaborative/dbatools/issues/6210#issuecomment-600929627).
Disposing the SqlCommand and the SqlDataAdapter alone does not help, but disposing the connection in Invoke-DbaQuery right after Invoke-DbaAsync alone works: `$server.ConnectionContext.SqlConnectionObject.Dispose()`

So back to the two different cases. What about handling them different within the commands. The Connect-DbaInstance has to return the info, if $server is a new object or just the old $instance. If it is a new object, it was created within the command and has to be disposed within the command. The user has no chance to do so later, because it is not returned. Ok, every command must be changed and this is only for the Azure objects, as connection pooling works with non-Azure.

Other idea: can the command (or Connect-DbaInstance) just put the newly created $server object in a global array or something, so that the user (or other commands) can get to them and issue the .Dispose()?

Ok, a lot of unstructured ideas - I will stop here...

**Comment by niphlod** [comment] 2020-09-25 06:36
> I feel that any call to Connect should be explicit to make another connection. However, I'd note that `Invoke-DbaQuery` only makes one call to `Connect-DbaInstance`.

yeah, the point is users expect that multiple calls of `Invoke-DbaQuery` with the same target do not exhaust the connpool. Granted, there are a few subtleties that makes the problem with Azure db target a little worse than it should be.

> In Azure it looks different, as far as my tests show. Even when the connections string does not change, a new connection is opened.

and that is my finding, too. BUT, somehow, with that simple fix to  `Connect-DbaInstance`, repeated calls to `Invoke-DbaQuery` that use a "full server smo" (aka `$oneconnect`) just reuse one connection. And it makes the loop a hella-lot speedier (supposedly because indeed the connection is not reestablished each time). This _leads_ me to think that in _that_ usecase, Dispose(ing) is not needed.
I'm okay(ish) with commands Dispose()ing the conn (should go back to the connpool, right, not close the whole thing ?) but I'm trying to figure out if there is a way to avoid micromanaging in lower-level commands what _supposedly_  `Connect-DbaInstance` should do, which ultimately is "doing a lot of work" but relying on the fact that an equal connstring should not create a new connection but reuse an existing one. Before going to bed I was thinking that the **TCP:** hostname part of the connstring was the culprit.

**Comment by andreasjordan** [comment] 2020-09-25 06:56
If you pass a full server smo of an Azure connection to Connect-DbaInstance this is the only code that is run (my test version of the code with more Debug):

```
            if ($connstring -match $AzureDomain -or $instance.ComputerName -match $AzureDomain -or $instance.InputObject.ComputerName -match $AzureDomain) {
                Write-Message -Level Debug -Message "We are about to connect to Azure"
                # so far, this is not evaluating
                if ($instance.InputObject.ConnectionContext.IsOpen) {
                    Write-Message -Level Debug -Message "Connection is already open, test if database has to be changed"
                    $currentdb = $instance.InputObject.ConnectionContext.ExecuteScalar("select db_name()")
                    if (($Database -and ($Database -eq $currentdb))) {
                        Write-Message -Level Debug -Message "Same database, so return instance.InputObject"
                        $instance.InputObject
                        continue
```

**Comment by niphlod** [comment] 2020-09-25 07:12
yeah, and adding a small fix (if $Database is not passed, set it to "master", after $currentdb) closes the "issue" of Invoke-DbaQuery exhausting the connpool when reusing a full server smo. Now my "target" is .... how to make it not exhaust the connpool when passed the same set of sqlinstance, credentials and database ?

**Comment by andreasjordan** [comment] 2020-09-25 08:28
I thinks that's a problem inside the dll - because it works for non-Azure.
One idea (I have no time to test at the moment): Try to shorten the connection string. Maybe there are parts that prevent the connection pooling but can be left out.
And I also deleted `$null = $serverconn.Connect()` because in the non-Azure-world this prevents the connection pooling. This line seems not be needed - it works without.

**Comment by wsmelton** [comment] 2020-09-25 12:01
The server.Connect() is there for an explicit reason. This was there for use with credentials because SMO will try to connect as the console user when the desire is to connect using a credential if I recall.

Please run your test using a credential where your account running the session has no rights to the instance.

**Comment by wsmelton** [comment] 2020-09-25 12:14
I'd also note all this discussion on `Connect-DbaInstance` should be moved to #6211 as a good bit has already been discussed.

**Comment by niphlod** [comment] 2020-09-25 12:16
yup, I'm trying to address both, that one got a bit stale.

**Comment by andreasjordan** [comment] 2020-09-26 10:09
@niphlod I made one (big?) step: Azure and non-Azure both create new connections, if we use a connection string to build the smo. So this has nothing to do with Azure, but with building the smo. I will go on and work with non-Azure and try to find a way to use a connection string without opening a new connection.

**Comment by andreasjordan** [comment] 2020-09-26 12:18
Here is some code to show the difference:

```
Import-Module -Name dbatools -MinimumVersion 1.0.121

# Version 1: Let Smo.Server handle the connection
#################################################

$credentialSa = New-Object -TypeName System.Management.Automation.PSCredential('sa', ("P@ssw0rd" | ConvertTo-SecureString -AsPlainText -Force))
$fullSmoName = 'sqlix.ordix.de\pstest,14331'  # At Connect-DbaInstance "$instance.FullSmoName" is used
$server = New-Object Microsoft.SqlServer.Management.Smo.Server $fullSmoName
$server.ConnectionContext.ApplicationName = 'Test Smo.Server V0'
$connstring = $server.ConnectionContext.ConnectionString
$server.ConnectionContext.LoginSecure = $false
$server.ConnectionContext.set_Login($credentialSa.UserName)
$server.ConnectionContext.set_SecurePassword($credentialSa.Password)  # No connection is opened jet
$server.ConnectionContext.SqlConnectionObject.Open()  # This connects to the SQL Server
$server.ConnectionContext.ProcessID  

# We use the same connection string again, so pooling should work
$processIds = @()
1..10 | ForEach-Object -Process {
    $server = New-Object Microsoft.SqlServer.Management.Smo.Server $fullSmoName
    $server.ConnectionContext.ApplicationName = 'Test Smo.Server V1'
    $connstring = $server.ConnectionContext.ConnectionString
    $server.ConnectionContext.LoginSecure = $false
    $server.ConnectionContext.set_Login($credentialSa.UserName)
    $server.ConnectionContext.set_SecurePassword($credentialSa.Password)  # No connection is opened jet
    $server.ConnectionContext.SqlConnectionObject.Open()  # Do we get another connection?
    $processIds += $server.ConnectionContext.ProcessID  # No! It works as expected
}
$processIds -join ' '

# And that works with dbatools aswell
$processIds = @()
1..10 | ForEach-Object -Process {
    $server = Connect-DbaInstance -SqlInstance $fullSmoName -SqlCredential $credentialSa -ClientName 'Test Smo.Server V2'
    $processIds += $server.ConnectionContext.ProcessID
}
$processIds -join ' '


# Version 2: We use SqlClient.SqlConnection, Common.ServerConnection and Smo.Server
###################################################################################

$connstring = 'Data Source=sqlix.ordix.de\pstest,14331;User ID=sa;Password=P@ssw0rd;Application Name="Test SqlClient.SqlConnection V0"'
$sqlconn = New-Object System.Data.SqlClient.SqlConnection $connstring
$serverconn = New-Object Microsoft.SqlServer.Management.Common.ServerConnection $sqlconn
$server = New-Object Microsoft.SqlServer.Management.Smo.Server $serverconn  # No connection is opened jet
$server.ConnectionContext.SqlConnectionObject.Open()  # This connects to the SQL Server
$server.ConnectionContext.ProcessID

# We use the same connection string again, so pooling should work
$processIds = @()
1..10 | ForEach-Object -Process {
    $connstring = 'Data Source=sqlix.ordix.de\pstest,14331;User ID=sa;Password=P@ssw0rd;Application Name="Test SqlClient.SqlConnection V1"'
    $sqlconn = New-Object System.Data.SqlClient.SqlConnection $connstring
    $serverconn = New-Object Microsoft.SqlServer.Management.Common.ServerConnection $sqlconn
    $server = New-Object Microsoft.SqlServer.Management.Smo.Server $serverconn
    $server.ConnectionContext.SqlConnectionObject.Open()  # Do we get another connection?
    $processIds += $server.ConnectionContext.ProcessID  # Yes! Not every time, but most times we run this block, we get a new connection. That is not what we expect.
}
$processIds -join ' '

# What can we do? If we (and not the smo) explicitly open a connection, we have to take care and close it.
$processIds = @()
1..10 | ForEach-Object -Process {
    $connstring = 'Data Source=sqlix.ordix.de\pstest,14331;User ID=sa;Password=P@ssw0rd;Application Name="Test SqlClient.SqlConnection V2"'
    $sqlconn = New-Object System.Data.SqlClient.SqlConnection $connstring
    $serverconn = New-Object Microsoft.SqlServer.Management.Common.ServerConnection $sqlconn
    $server = New-Object Microsoft.SqlServer.Management.Smo.Server $serverconn
    $server.ConnectionContext.SqlConnectionObject.Open()  # Do we get another connection?
    $processIds += $server.ConnectionContext.ProcessID  # No!
    $server.ConnectionContext.SqlConnectionObject.Close() # Because we close it, so it gets back to the connection pool
}
$processIds -join ' '
```

My output:

![image](https://user-images.githubusercontent.com/66946165/94340563-20cade00-0003-11eb-87a5-ce2f52be75c6.png)

**Comment by andreasjordan** [comment] 2020-09-26 12:33
But the best is yet to come:

```
# Try to use version 1 with Azure
#################################

$credentialSa = New-Object -TypeName System.Management.Automation.PSCredential('user1', ("P@ssw0rd" | ConvertTo-SecureString -AsPlainText -Force))
$fullSmoName = 'sqlserver-db-dbatools.database.windows.net,1433'  # At Connect-DbaInstance "$instance.FullSmoName" is used
$server = New-Object Microsoft.SqlServer.Management.Smo.Server $fullSmoName
$server.ConnectionContext.ApplicationName = 'Test Azure Smo.Server V0'
$server.ConnectionContext.DatabaseName = 'database-db-dbatools'
$connstring = $server.ConnectionContext.ConnectionString
$server.ConnectionContext.LoginSecure = $false
$server.ConnectionContext.set_Login($credentialSa.UserName)
$server.ConnectionContext.set_SecurePassword($credentialSa.Password)  # No connection is opened jet
$server.ConnectionContext.SqlConnectionObject.Open()  # This connects to the SQL Server
$server.ConnectionContext.ProcessID  

$processIds = @()
1..10 | ForEach-Object -Process {
    $server = New-Object Microsoft.SqlServer.Management.Smo.Server $fullSmoName
    $server.ConnectionContext.ApplicationName = 'Test Azure Smo.Server V1'
    $server.ConnectionContext.DatabaseName = 'database-db-dbatools'
    $connstring = $server.ConnectionContext.ConnectionString
    $server.ConnectionContext.LoginSecure = $false
    $server.ConnectionContext.set_Login($credentialSa.UserName)
    $server.ConnectionContext.set_SecurePassword($credentialSa.Password)
    $server.ConnectionContext.SqlConnectionObject.Open()  # Do we get another connection?
    $processIds += $server.ConnectionContext.ProcessID  # No! It works as expected
}
$processIds -join ' '
```

It works with Azure SQL Databases! On my machine... But with a user that has no access to the master database.

So the question is: Why do we ever want to use explicit connections with SqlClient.SqlConnection and Common.ServerConnection, and not just let the Smo.Server handle the connections?

**Comment by potatoqualitee** [comment] 2020-09-26 13:22
@andreasjordan - if i recall, i was reusing the code proposed by Microsoft as I don't know enough about SMO. But it could also be the dual domain issue or I may have needed it for it to work with MFA? do you have a lab that could test those scenarios?

**Comment by andreasjordan** [comment] 2020-09-26 13:28
I don't have a lab with dual domains. Maybe we can first focus on azure and try to change the code there to build the smo without first build a connection.
Because it has a big impact: Can we have a config item "experimental feature" and have dual code: Only use the new way if users activate this in the config? This way we can ship the code to interested users with a lot of different azure environments and they can test it.

**Comment by niphlod** [comment] 2020-09-28 06:41
@andreasjordan : great find! at least we do have a reproducible case. 
@potatoqualitee : I guess we can also start the fixes to make sure a new connection is not opened when a single Connect-DbaInstance is used with multiple Invoke-DbaQuery calls and propose that "form" for users in the need of calling it in a tight loop when the target is Azure, so in the meantime they get to use it ^_^

**Comment by TheRockStarDBA** [comment] 2020-10-02 01:25
Any update here ? I am having same issue 

```
Exception calling Open with 0 argument(s): Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. Exception calling Open with 0 argument(s): Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. Exception calling Open with 0 argument(s): Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. You cannot call a method on a null-valued expression. Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. System.Management.Automation.RuntimeException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. ---> System.Exception: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. ---> System.Management.Automation.MethodInvocationException: Exception calling Open with 0 argument(s): Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Connect-DbaInstance<Process>(Closure , FunctionContext )
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
```

**Comment by andreasjordan** [comment] 2020-10-02 06:32
Hi @TheRockStarDBA : Yes, the first improvements are part the the new version 1.0.123. The command is still not perfect, more updates are planned. I would like to hear from you if your case is already solved with the new version. If not, please provide more details about your situation and the commands you use.

**Comment by mkellerman** [comment] 2021-01-30 09:34
Sorry to jump in, but this Issue has become stale. And no idea the current state of the issue. I use Invoke-DbaQuery in some scripts, and provide it with a $SqlInsance object returned by the Connect-DbaInstance. I have 30-50 connections established lingering around on my local mssql dev db, where only my single script is running.

Can this be avoided?

**Comment by sdecker** [comment] 2021-04-21 19:28
@mkellerman It's a little hacky but you can Clear-DbaConnectionPool until this bug is fixed.

**Comment by sdecker** [comment] 2021-04-21 19:33
@TheRockStarDBA To be clear this bug affects any function in DbaTools that uses Connect-DbaInstance or the internal wrapper Connect-SqlInstance.

**Comment by sdecker** [comment] 2021-04-21 20:04
@andreasjordan  I'm testing with 1.0.145 and the issue still persists as noted by the original repro case from @Jaykul

**Comment by andreasjordan** [comment] 2021-04-21 20:25
Have you used the experimental code path (see last example in the docs)?



Am 21.04.2021 22:04 schrieb sdecker ***@***.***>:

@andreasjordan<https://github.com/andreasjordan> I'm testing with 1.0.145 and the issue still persists as noted by the original repro case from @Jaykul<https://github.com/Jaykul>

**Comment by sdecker** [comment] 2021-04-21 20:43
I did not use the experimental code path. Sorry missed that. I will try it now. But I also found that the problem goes away if I add  $server.ConnectionContext.Disconnect() at the end of the 
        foreach ($instance in $SqlInstance) {
section.

**Comment by sdecker** [comment] 2021-04-21 21:19
@andreasjordan I confirm that with sql.connection.experimental I cannot reproduce the simple use case on the same DB.  I'm going to setup 200 DBs on my test setup now because I think it will still fail with more than 100 unique DBs on Azure Sql. Basically in which case all functions that use create a connection themselves need to use the $newConnection logic like Test-DbaRestoreVersion implements.

**Comment by andreasjordan** [comment] 2021-04-22 07:10
@sdecker You can do that with:
```
Set-DbatoolsConfig -FullName sql.connection.experimental -Value $true -Passthru | Register-DbatoolsConfig
```

My plan is to set this code path as the default later. So please give feedback if there are any problems or limitations with this setting.

**Comment by sdecker** [comment] 2021-04-22 22:03
Sorry for not being clear. I know how to make the experimental feature permanent on my system. I was asking what I can do to help move it from experimental to the installed default. I am pleasantly surprised that this experimental fix also works with connection to mutliple DBs with other commands like Get-DbaDbSpace

$SecurePW = ConvertTo-SecureString 'Just4Now' -AsPlainText -Force
foreach($c in 1..110) {
   $cred = New-Object System.Management.Automation.PSCredential("testpooldb$($c)",$SecurePW)
   Get-DbaDbspace -SqlInstance $InstanceInfo.InstanceName -SqlCredential $cred -Database $cred.UserName | ft
}
I've tested various commands and so far not seeing any issues.

**Comment by andreasjordan** [comment] 2021-04-23 05:59
Hi @sdecker : Thanks for your offer to help!

Have a look at the source code at https://github.com/sqlcollaborative/dbatools/blob/master/functions/Connect-DbaInstance.ps1 and search for "TODO". There are still some questions we have to answer and some decisions we have to make. 
Then we need the final ok from @potatoqualitee .

**Comment by andreasjordan** [comment] 2021-05-19 07:26
I will close this for now, but you can reopen it if you have further questions.

**Comment by potatoqualitee** [comment] 2021-07-14 16:49
This is finally fixed in dev! 🥳  will release to PS Gallery in 5 days, after testing

**Closed by potatoqualitee** 2021-07-14 16:49 UTC
Labels: bugs life, confirmed, solution provided, v1.1.0
