### ISSUE TITLE
[Bug] Copy-DbaLinkedServer is improperly using the database administrative connection, which blocks other connections

### ISSUE THREAD

**Issue by golfguru** [sqlcollaborative/dbatools#6372] opened 2020-02-21 00:43 UTC
### Environmental information

PowerShell version: 

PSVersion                      5.1.14393.3383
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3383
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.97\dbatools.psd1
Version : 1.0.97

#### SQL Server: 

2 different versions of SQL, and it's behaving exactly the same

Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

Microsoft SQL Server 2014 - 12.0.2000.8 (X64)   Feb 20 2014 20:04:26   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

### Report

Using powershell.exe

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

No errors are received, the script runs successfully, it's just causing an issue on the SQL side of things

#### Steps to Reproduce

Using a 2-node Always-On Availability Group in SQL Server, run the following command in powershell:  Copy-DbaLinkedServer -source Node1 -destination Node2

#### Expected Behavior

We expected the command to setup the linked servers on Node2 exactly as they are on Node1.

#### Actual Behavior

This does happen, the linked servers are created on Node2, exactly as they are on Node1, however right after running the command, we start getting messages from our Idera Diagnostics Manager server, with the following information:

"SQLdm Alert (Critical) - Error log recorded 1 alertable message on KNXCS7DB

2/19/2020 6:00:08 PM, SQL Server Error Log on KNXCS7DB is Critical.

SQL Server instance KNXCS7DB recorded 1 error log message requiring attention. The message are shown below in context (if applicable): OK 2/19/2020 7:56:19 PM Server The Service Broker endpoint is in disabled or stopped state. Critical 2/19/2020 7:54:02 PM Logon Error: 17810, Severity: 20, State: 2. OK 2/19/2020 7:54:02 PM Logon Could not connect because the maximum number of '1' dedicated administrator connections already exists. Before a new connection can be made, the existing dedicated administrator connection must be dropped, either by logging off or ending the process. [CLIENT: 127.0.0.1] 

SQL Server Error Log: When configuring this alert, specify which SQL error severities (0-30) correspond to Critical, Warning, or OK. Use the advanced options to specify text matches and set log size limits. The number of SQL Server error log events requiring attention will be reflected in the alert. "

So the Copy-DbaLinkedServer command is using the DAC (dedicated administrator connection) for some reason and not releasing it properly so that connections to the server start to get rejected. We are using a several other commands as well, without causing this issue. The other commands we are using are:
Copy-DbaLogin -Source Node1 -Destination Node2
Sync-DbaLoginPermission -source Node1 -destination Node2
Copy-DbaDbMail -source Node1 -destination Node2
Copy-DbaAgentOperator -source Node1 -destination Node2
Copy-DbaSpConfigure -source Node1 -destination Node2

None of the other commands are causing the issue described above, they all work as expected and don't use the DAC, or if they are they're releasing the connection properly.

**Comment by wsuhoey** [comment] 2020-02-21 01:16
Please give this issue a proper title.

**Comment by wsmelton** [comment] 2020-02-21 03:41
So a few things to note:

1. Yes, the copy linked server command does use DAC connection and the others don't...this is how we actually decrypt the passwords saved in the linked server configuration. (Any command that calls [Get-DecryptedObject](https://github.com/sqlcollaborative/dbatools/blob/development/internal/functions/Get-DecryptedObject.ps1) will utilize the DAC connection on the instance. None of the other commands you listed will have a reason to use this internal function.)
1. The code we have closes the connection, so you need to show that our connection is not being closed properly. (You are the first to report this as an issue and this command has been used by a number of users.)
1. Is there a delay from Idera DM in that the times shown were actually during our code being executed?

**Comment by golfguru** [comment] 2020-02-21 04:25
Shawn, thank you for your quick response on this. For the points you mention, It's good to know that any of the commands using the Get-DecryptedObject will use the DAC. I'll keep that in mind for future use. As for points 2 & 3, there could very well be a delay from Idera in that the messages are from when the code is actually executing. I will check in to the timing further and get back to you on those points, as you could very well be right. Thanks for pointing me in the right direction and for the info on the Get-DecryptedObject command using the DAC

**Comment by Jedelahu** [comment] 2021-04-30 13:44
I’m having a similar error using Copy-DbaLinkedServer. It works but does set off SQL alert “Severity 020 Fatal Error in Current Process”  with the message of;

 “DESCRIPTION:	Could not connect because the maximum number of '1' dedicated administrator connections already exists. Before a new connection can be made, the existing dedicated administrator connection must be dropped, either by logging off or ending the process. [CLIENT: ::1]

Using Dbatools v1.0.142

Thoughts?

**Comment by andreasjordan** [comment] 2021-05-19 09:11
`Copy-DbaLinkedServer` is started by `Start-DbaMigration` and `Sync-DbaAvailabilityGroup`. Both commands have a parameter `-Exclude` where you can exclude objects from syncing. If you don't have linked servers or if you don't need to sync them regularly, you can use `-Exclude LinkedServers` to work around this problem.

I will close this as "no bug" / "works as designed", but you can reopen it if you have further questions.

**Closed by andreasjordan** 2021-05-19 09:11 UTC

**Comment by Franky1522** [comment] 2022-04-04 11:07
I have the same problem, When I used Copy-DbaLinkedServer with only 1 linked Server, I received this alert. I check if I have new Linked Server everyday so I received this alert daily. Any Fix to this problem?

**Comment by andreasjordan** [comment] 2022-04-04 11:13
Just to be sure: Are you on the latest version of dbatools?
And how should we fix the problem? There can only be one DAC. If there is already a DAC, there is nothing we can do about it.

**Comment by Franky1522** [comment] 2022-04-04 11:44
Yes, I did last week. And I have just done it again.
I dont know how solve the problem. But I dont understand why the process generates more than 1 DAC connection.
It`s curious because if I execute it a second time after a short time, the alert does not go off.

**Comment by wsmelton** [comment] 2022-04-04 11:54
Please open a new one and provide all the requested details with your issue.
