### ISSUE TITLE
Update-dbatools - Always installs to $PROFILE/../Modules/Powershell

### ISSUE THREAD

**Issue by dwierenga** [sqlcollaborative/dbatools#273] opened 2016-10-18 20:21 UTC
Although the install.ps1 cmdlet accepts a $Path parameter, the Update-DBATools command does not pass any arguments to the install script.  

Therefore, calling Update-DBATools always results in the module being installed to a parent path of your powershell $PROFILE, regardless of where you currently have the module installed.

**Comment by wsmelton** [comment] 2016-10-18 21:17
If you install the module from the PowerShell gallery using `Install-Module` it will be installed under `C:\Program Files\Windows PowerShell\Modules\dbatools`. 

So if you are using the Package Management commands to install the module, you will need to keep using those to update or remove the module. 

We may just need to add a check to see where the module is installed instead of defaulting to the user's profile path.

**Comment by ctrlbold** [comment] 2016-10-19 11:45
Thanks @dwierenga. update-dbatools was intended primarily to support non-gallery installs. In order to support Gallery, looks like we'll have to 

    try { 
        Get-InstalledModule -Name dbatools
        Update-Module dbatools 
    }
    catch { 
        Do regular routine 
    }

**Comment by niphlod** [comment] 2017-02-16 00:41
@ctrlbold : pinging against staleness... if there is a solution it should be in the next release or in the n+1 one.

**Comment by niphlod** [comment] 2017-03-13 21:35
@ctrlbold : ping+1 . IMHO this got solved with all the recent jabberish with incorrect encoding and @ck sweat. Please close this if we're all good.

**Comment by potatoqualitee** [comment] 2017-07-23 13:15
checking, @niphlod

**Comment by potatoqualitee** [comment] 2017-07-23 13:17
This has indeed been resolved!

**Closed by potatoqualitee** 2017-07-23 13:17 UTC
Labels: Type: Bug
