### ISSUE TITLE
Find-DbaDatabaseGrowthEvent doesn't ignore trace files

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1390] opened 2017-06-04 07:30 UTC
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details

No idea what's going on here but the SQL query to find database growth events is somehow looking at my trace on sql2016.

PS C:\github\dbatools> Find-DbaDatabaseGrowthEvent -SqlInstance $singleServer -Database AutoGrowth

````
ComputerName : 
InstanceName : 
SqlInstance  : 
EventClass   : 567
DatabaseName : 16
Filename     : 2
Duration     : File 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Log\log_27.trc' is not a 
               recognizable trace file.
StartTime    : 1
EndTime      : 1
ChangeInSize : 1

````

**Comment by wsmelton** [comment] 2017-06-05 00:55
I can't duplicate this with my 2016 instance from the dev branch. What does your verbose output look like, or the debug (includes the query)?

**Comment by wsmelton** [comment] 2017-06-05 01:40
Not that it will fix it, but formatted the command and adjusted the query to include more output...also added the pretty Query() method (https://github.com/sqlcollaborative/dbatools/pull/1392).

**Comment by ClaudioESSilva** [comment] 2017-07-23 21:30
Today I have used this command a bunch of times and always without a problem.
Even so, I tried to reproduce the issue. I could but in very hard way.

I picked up a file that is not a .trc one (in this case was an .xel (extended events)), and changed the extension to .trc - This shows the exact same error you received
![image](https://user-images.githubusercontent.com/19521315/28502991-f56634c6-6ff5-11e7-9e98-492767e270f7.png)

If we try to point to a non-existing file the error is different:
![image](https://user-images.githubusercontent.com/19521315/28503010-36a4e806-6ff6-11e7-91e9-90f7c893f17c.png)

In my opinion we bump on very strange error.. only if we have done a copy of the file we would be able to understand the error.

I suggest close this as "can't reproduce" and if it strikes again we open with "deja vu" label 😄 

What do you think @wsmelton, @potatoqualitee ?

**Comment by ClaudioESSilva** [comment] 2017-07-23 21:32
Oh by the way, the issue title is not accurate. We need the trace file (the default trace file) to get this info.

**Comment by ClaudioESSilva** [comment] 2017-12-13 22:51
@potatoqualitee Can we close this as "can't reproduce"?
We will reopen if we get new info.

**Comment by potatoqualitee** [comment] 2017-12-14 17:42
dang, sorry, i posted this during a super busy time. if you were able to reproduce, is it possible to ignore using where?

**Comment by potatoqualitee** [comment] 2018-11-12 15:13
Two can't repros - I'll reopen if I run into it again and have more info

**Closed** 2018-11-12 15:13 UTC
Labels: bugs_life
