### ISSUE TITLE
[Bug] - Import-DbaCsv does not close the session after finishing execution

### ISSUE THREAD

**Issue by DanielSSilva** [sqlcollaborative/dbatools#6620] opened 2020-06-25 14:32 UTC
### Environmental information

```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.3
PSEdition                      Core
GitCommitId                    7.0.0-rc.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.78\dbatools.psd1
Version : 1.0.78



```

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64) 	Oct 28 2019 19:56:59 	Copyright (C) 2019 Microsoft Corporation	Developer Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS) <X64>
```
Aditional info: running inside a container

### Report

After running Import-DbaCsv, if I run `sp_who` it still shows an active connection (although the status is `sleeping`).
Went to check again after ~10minutes and the connection is no longer there (but I'm assuming that it was SQL who killed it).

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Steps to Reproduce

Import some csvs to the database, ie:

```powershell
 Import-DbaCsv -Path $logFiles -Delimiter '|' -SqlInstance "Localhost" -SqlCredential $credentials -Database logHolder -Table LogsTable
```

#### Expected Behavior

The connection should be closed after finishing the execution of the command.

#### Actual Behavior

The connection was still open after the command execution, preventing me to, for example, delete the database without killing the session first.

**Comment by wsmelton** [comment] 2020-06-25 20:53
This wouldn't be a bug, by my view, it is by design because the module depends on connection pooling be default.

You can use connection command to explicitly open and close the connection.

**Comment by nvarscar** [comment] 2020-07-17 18:42
Connection pooling is indeed a default SMO behaviour. The workaround here would be to use a non-pooled connection, by either providing a connection string explicitly requesting such connection, or using -NonPooledConnection switch in `Connect-DbaInstance`. I'm closing this one unless there are any objections.

**Closed by nvarscar** 2020-07-17 18:42 UTC
Labels: bugs_life
