### ISSUE TITLE
Get-DbaSqlBuildReference - Offline server issue

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1105] opened 2017-04-27 20:45 UTC
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details
Line 162 and 164 throw an exception if the SQL Server is offline. Complains of not being able to call a method on a null object.

**Comment by niphlod** [comment] 2017-04-27 21:24
already fixed in development via https://github.com/sqlcollaborative/dbatools/commit/1cb2eb9464105652c48fb1677a7f399db44f434e ... and its in current master too ^_^

**Comment by niphlod** [comment] 2017-04-27 21:25
duplicate of #1057 , which is already fixed .

**Closed by niphlod** 2017-04-27 21:25 UTC

**Comment by potatoqualitee** [comment] 2017-04-27 21:34
aw ooops! you are right! I totally didnt update - it was my offline server.t hank you and sorry

**Comment by niphlod** [comment] 2017-04-27 21:35
better to have a bug reported and closed in 40 minutes (even if it's a false report) than nobody at all looking at the code and testing s**t out ^_^
