### ISSUE TITLE
[Bug]Import-dbacsv locks csv file if the file can not be imported

### ISSUE THREAD

**Issue by omicronx90** [sqlcollaborative/dbatools#7162] opened 2021-02-22 13:42 UTC
#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```powershell
Import-DbaCsv -Path "$filetoprocess" -SqlInstance $sqlinstance -Database $databasename -Table $destinationtable -Delimiter "," -EnableException
```

```console
WARNING: Error message: Violation of PRIMARY KEY constraint 'PK_Gas_Composition_Data'. Cannot insert duplicate key in object 'dbo.Ga
s_Composition_Data'. The duplicate key value is (2001-06-21, Somewhere Else).
The statement has been terminated.

#### Steps to Reproduce

Provide a list of steps to reproduce and any code required. Sanitize code if needed.
```powershell
#Variables MAKE CHANGES HERE#################################
$servername = "ausappd01"
$databasename = "SCENE"
$importpath = "D:\FlatFileIImports"
$sqlinstance = "ausappd01\MSSQLSERVER"
$directory = Get-ChildItem D:\FlatFileIImports | select Name
$flatfilearchive = "D:\FlatFileArchive"
$badfilepath = "D:\FlatFileArchive\BadFiles"
$badfiles = New-Object System.Collections.Generic.List[System.Object]
$processedfiles = New-Object System.Collections.Generic.List[System.Object]
##################################################################
$a = Get-DbaUptime -SqlInstance $sqlinstance

#Function: Get-TableNames
#Purpose: Query Database for Tables
Function Get-TableNames(){
$srv = new-object microsoft.sqlserver.management.smo.server '.';
foreach ($db in $srv.Databases) {
   foreach ($tbl in $db.tables) {
      if ($db.Tables.Parent -like "*$databasename*"){
      $a =  $db.Tables.Parent.Tables
      return $a
      #$tbl | select parent, name;
      }
   }
}
}#End Function

#Get Tables out of the database
$tables = Get-TableNames 

#Loop the SQL tables and dir structure and match for import
foreach ($table in $tables){
   $destinationtable = $table.Name
   if ($directory -match $destinationtable){
   
        write-host "Found Matching Table " $destinationtable `n

        #Check and Create Archive Dir
        if(![System.IO.File]::Exists("D:\FlatFileArchive\$destinationtable")){
            # file with path $path doesn't exist
            New-Item -Path D:\FlatFileArchive\$destinationtable -ItemType Directory -ErrorAction Continue
        }else{
            write-host "`n Archive Already Directory Exists `n"
        }

        Write-host "**********Begin Import SQL IMPORT for Table dbo.$destinationtable ******** `n" 
        $filepath= $importpath + "\" + $destinationtable
        write-host "File Import Path" $filepath
        $csv = Get-ChildItem $filepath | select Name
        if ($csv -eq $null){
        write-host "NO Files Found to Process Write to Log `n"
        }else{

        foreach ($csvfile in $csv){
         $errorlvl = $null
         $filetoprocess = $filepath + "\" +$csvfile.Name
         $filearchive = $flatfilearchive + "\" + $destinationtable

         Write-Host "`n SQL IMPORT Process File" $filetoprocess
        
          #SQL IMPORT
           ## Import CSV into SQL
          try{
     
          Import-DbaCsv -Path "$filetoprocess" -SqlInstance $sqlinstance  -Database $databasename -Table $destinationtable -Delimiter "," -EnableException
          
          }
          catch{
          $errorlvl = $_
          Write-Warning "Error message: $_"
          write-host "Collect Bad Files to Process"
          $badfiles.Add("$filetoprocess")


          }
          
          if ($errorlvl -eq $null){
          #Archive the file
          Move-Item -Path $filetoprocess -Destination $filearchive -Force -Verbose
          $processedfiles.Add($filetoprocess)
          }
         }#Endfor
   
        }#Endelse
        }#Endif

}#endfor

function Process-BadFiles(){

foreach ($file in $badfiles){


Move-Item $file -Destination $badfilepath -Force -Verbose

}#endfor

}#endfuction

Write-host "`n These are the processed Files"
$processedfiles
Write-host "`n These are the bad Files"
$badfiles
Process-BadFiles
```

#### Expected Behavior
I should be able to move the file that could not imported when an error was thrown

#### Actual Behavior

I get a file in use error when trying to move the file in the catch statement

```console
D:\FlatFileIImports\Gas_Composition_Data\Gas_Composition_Data1 - Copy.csv
VERBOSE: Performing the operation "Move File" on target "Item: D:\FlatFileIImports\Gas_Composition_Data\Gas_Composition_Data1 - Copy
.csv Destination: D:\FlatFileArchive\BadFiles\Gas_Composition_Data1 - Copy.csv".
Move-Item : The process cannot access the file because it is being used by another process.
At C:\Scripts\SCENE-ImportData-TEST.ps1:114 char:1
+ Move-Item $file -Destination $badfilepath -Force -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\FlatFileIImp...ata1 - Copy.csv:FileInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
<!--
  Import-DbaCsv -Path "$filetoprocess" -SqlInstance $sqlinstance  -Database $databasename -Table $destinationtable -Delimiter "," -EnableException
          
          }
          catch{
          $errorlvl = $_
          Write-Warning "Error message: $_"
          write-host "Collect Bad Files to Process"
          $badfiles.Add("$filetoprocess")
-->
```
### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.14393.3866
dbatools latest installed : 1.0.139
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64) 
	Aug 15 2017 10:23:29 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: ) (Hypervisor)
```

```sql
us_english
```

**Comment by nvarscar** [comment] 2021-02-22 18:32
Please add Expected Behavior and Actual Behavior as per issue template

**Comment by omicronx90** [comment] 2021-02-23 04:01
> Please add Expected Behavior and Actual Behavior as per issue template

I have updated the template is the update ok ?

**Comment by RandyInMarin** [comment] 2021-03-09 17:34
This is an annoying issue during development because closing PowerShell ISE does not release the file lock.  When the ISE is closed, the ISE window is closed but the process is still open with the lock.  Somehow this issue prevents the process from closing normally.  As a work around, this script will close the orphaned powershell ise processes and release the locks.  

`Get-Process -Name 'powershell_ise' | 
    Where {$_.Id -ne $PID -and $_.MainWindowHandle -eq 0} | 
    Stop-Process`

**Closed** 2021-03-11 09:53 UTC
Labels: bugs_life
