### ISSUE TITLE
Copy-DbaLogin fails when an AD login on source is invalid

### ISSUE THREAD

**Issue by frank687** [sqlcollaborative/dbatools#3184] opened 2018-01-31 18:56 UTC
### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): 6.3.9600 Microsoft Windows 8.1 Enterprise
 - PowerShell Version: 5.0.10586.117
 - SQL Server (Edition|Version):  Both are  12.0.5556.0 & EnterpriseOrDeveloper 

## Steps to Reproduce
Source server must have a login that has been removed from AD.
Target server must not have that login.
`Copy-DbaLogin -Source Server1 -Destination Server2 -EnableException`

![image](https://user-images.githubusercontent.com/25494820/35641422-cc4f5ece-0685-11e8-8fb1-1c76343011cf.png)

 - [X] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [X] Attach output from PowerShell console (if possible/allowed)

**Comment by wsmelton** [comment] 2018-10-10 03:38
@frank687 maybe I'm missing something but I see this as by design. Copy commands do not have logic included (and would be out of scope) to have it validate if any given AD login is valid. We do not handle dependencies in the copy/migration commands. I would see this needing testing before you go to copy the logins, and a normal maintenance task for security to find logins no longer valid/in use.

We do have command that let you handle that ahead of time, so you could filter the result: `Test-DbaWindowsLogin`.

**Closed by wsmelton** 2018-10-10 03:38 UTC
